import test from 'node:test';import assert from 'node:assert/strict';import {Policy,sidebar,ok,fail} from '../host/policy.mjs';import {makeCounter} from '../fixtures/counter.mjs';import {makeCanvas,catalog as canvasCatalog} from '../fixtures/canvas.mjs';
const target={targetId:'target',pageInstanceId:'page',origin:'http://127.0.0.1:4314',appId:'demo-counter',documentId:'demo-document',title:'Fixture'};
async function setup(){const page=makeCounter();let calls=0;const p=new Policy(async(t,op,call)=>{if(op==='invoke'){calls++;return page.invoke(call);}return ok(await page[op]());},{timeout:50});p.bind({...target});p.heartbeat();await p.execute(sidebar,'host_list_tools',target);return {p,page,calls:()=>calls};}
const call=(amount=1,key='key-1',revision=0)=>({...target,call:{requestId:'r',documentId:'demo-document',toolName:'demo_increment',arguments:{amount},expectedRevision:revision,idempotencyKey:key}});
async function approved(p,args,client=sidebar,allow=true){const pending=p.execute(client,'host_call_tool',args);await new Promise(r=>setImmediate(r));for(const a of p.pending.values())p.decide(a.id,allow);return pending;}
test('fixture discovery, context, approved increment, semantic retry, conflict, stale revision',async()=>{const {p}=await setup();assert.equal((await p.execute(sidebar,'host_get_context',target)).data.revision,0);assert.equal((await approved(p,call())).data.value,1);const retry=call();retry.call.requestId='r2';assert.equal((await approved(p,retry)).data.value,1);assert.equal((await approved(p,call(2))).error.code,'IDEMPOTENCY_CONFLICT');assert.equal((await approved(p,call(1,'key-2'))).error.code,'STALE_CONTEXT');});
test('denied approval never dispatches',async()=>{const s=await setup();assert.equal((await approved(s.p,call(),sidebar,false)).error.code,'APPROVAL_DENIED');assert.equal(s.calls(),0);assert.equal((await s.page.getContext()).revision,0);});
test('UI inactive denies writes',async()=>{const {p}=await setup();p.uiUntil=0;assert.equal((await p.execute(sidebar,'host_call_tool',call())).error.code,'APPROVAL_DENIED');});
test('reload / changed origin invalidate approval',async()=>{for(const origin of [target.origin,'https://evil.example']){const {p,calls}=await setup();const run=p.execute(sidebar,'host_call_tool',call());await new Promise(r=>setImmediate(r));p.bind({...target,pageInstanceId:'new',origin});assert.equal((await run).error.code,'STALE_CONTEXT');assert.equal(calls(),0);}});
test('guest close and stale target',async()=>{const {p}=await setup();p.invalidate(target.targetId);assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'TARGET_CLOSED');p.bind({...target,pageInstanceId:'new'});assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');});
test('pair scope visibility revoke expiry forged token',async()=>{const {p}=await setup();const pair=p.pair('CLI',['read'],['target']);const client=p.authenticate(pair.token);assert(client);assert.equal((await p.execute(client,'host_list_targets',{})).data.targets.length,1);assert.equal((await p.execute(client,'host_call_tool',call())).error.code,'FORBIDDEN');assert.equal(p.authenticate('forged'),null);p.revoke(pair.id);assert.equal(p.authenticate(pair.token),null);const hidden=p.pair('other',['read'],[]);assert.deepEqual((await p.execute(p.authenticate(hidden.token),'host_list_targets',{})).data.targets,[]);p.authenticate(hidden.token).expires=0;assert.equal(p.authenticate(hidden.token),null);});
test('client revoke while approval pending fails closed',async()=>{const {p,calls}=await setup();const pair=p.pair('CLI',['read','write'],['target']);const run=p.execute(p.authenticate(pair.token),'host_call_tool',call());await new Promise(r=>setImmediate(r));p.revoke(pair.id);assert.equal((await run).error.code,'STALE_CONTEXT');assert.equal(calls(),0);});
test('payload injection/schema, privileged fields and unknown tool rejected',async()=>{const {p}=await setup();const a=call();a.call.arguments.amount="');globalThis.pwned=true;//";assert.equal((await p.execute(sidebar,'host_call_tool',a)).error.code,'INVALID_ARGUMENT');const b=call();b.call.approved=true;assert.equal((await p.execute(sidebar,'host_call_tool',b)).error.code,'INVALID_ARGUMENT');const c=call();c.call.toolName='shell_exec';assert.equal((await p.execute(sidebar,'host_call_tool',c)).error.code,'UNSUPPORTED');});
test('canonical frozen approval payload cannot be mutated by caller',async()=>{const {p}=await setup();const args=call();const run=p.execute(sidebar,'host_call_tool',args);await new Promise(r=>setImmediate(r));args.call.arguments.amount=99;for(const a of p.pending.values())p.decide(a.id,true);assert.equal((await run).data.value,1);});
test('unsupported bridge and timeout',async()=>{const p=new Policy(async()=>fail('UNSUPPORTED'),{timeout:10});p.bind(target);assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'UNSUPPORTED');p.dispatch=()=>new Promise(()=>{});assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'TIMEOUT');});
test('cancellation before approval dispatch',async()=>{const {p,calls}=await setup();const c=new AbortController();const run=p.execute(sidebar,'host_call_tool',call(),c.signal);await new Promise(r=>setImmediate(r));c.abort();assert.equal((await run).error.code,'CANCELLED');assert.equal(calls(),0);});
test('malformed guest response fails at boundary',async()=>{const {p}=await setup();p.dispatch=async()=>({ok:true,revision:0,data:{},error:{code:'INTERNAL',message:'inconsistent',retryable:false}});assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'INVALID_ARGUMENT');});
test('page-declared schemas outside the host-safe subset are never compiled',async()=>{const ctx=ok({appId:'demo-counter',documentId:'demo-document',revision:0,selectionIds:[],summary:''});for(const inputSchema of [{type:'object',properties:{a:{type:'string',pattern:'^(a+)+$'}}},{type:'object',allOf:[{allOf:[{allOf:[{allOf:[{allOf:[{allOf:[{allOf:[{allOf:[{type:'object'}]}]}]}]}]}]}]}]},{type:'object',$id:'https://app/s',items:{type:'object'},uniqueItems:true}]){const p=new Policy(async(t,op)=>op==='describe'?ok({protocolVersion:'0.1',appId:'demo-counter',tools:[{name:'evil',description:'x',effect:'write',inputSchema}]}):ctx);p.bind({...target});p.heartbeat();await p.execute(sidebar,'host_list_tools',target);const result=await p.execute(sidebar,'host_call_tool',{...target,call:{requestId:'r',documentId:'demo-document',toolName:'evil',arguments:{a:'a'.repeat(64)},expectedRevision:0,idempotencyKey:'k'}});assert.equal(result.error.code,'UNSUPPORTED');}});
test('logout result revokes target',async()=>{const {p}=await setup();p.dispatch=async()=>fail('UNAUTHORIZED');assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');assert.equal(p.targets.size,0);});
// Mirrors native guest_reply: on a getContext reply announcing a new
// documentId or a changed sessionEpoch for the same app, install a rotated
// binding (fresh pageInstanceId, new documentId/epoch) before the reply
// lands — never forward the new context to the stale binding.
const rebind=(p,dispatch)=>async(t,op,call,signal)=>{const r=await dispatch(t,op,call,signal);if(op==='getContext'&&r?.ok&&r.data?.appId===t.appId&&((typeof r.data?.documentId==='string'&&r.data.documentId!==t.documentId)||(r.data.sessionEpoch??null)!==(t.sessionEpoch??null)))p.bind({...t,documentId:typeof r.data.documentId==='string'?r.data.documentId:t.documentId,sessionEpoch:r.data.sessionEpoch??null,pageInstanceId:'page-'+Math.random().toString(36).slice(2)});return r;};
test('document switch without navigation rotates binding and fails closed',async()=>{const {p,page}=await setup();p.dispatch=rebind(p,p.dispatch);page.switchDocument();const r=await p.execute(sidebar,'host_get_context',target);assert.equal(r.error.code,'STALE_CONTEXT');assert.equal(r.data,null,'new document context must not reach the stale binding');const rotated=p.targets.get('target');assert.equal(rotated.documentId,'demo-document-2');assert.notEqual(rotated.pageInstanceId,'page');assert.equal(p.tools.has('target'),false);assert.equal((await p.execute(sidebar,'host_get_context',{...target,pageInstanceId:rotated.pageInstanceId})).data.documentId,'demo-document-2');assert.equal((await p.execute(sidebar,'host_list_tools',rotated)).ok,true,'fresh consent on the rotated binding reloads tools');assert.equal((await approved(p,{...rotated,call:{requestId:'r',documentId:'demo-document-2',toolName:'demo_increment',arguments:{amount:1},expectedRevision:0,idempotencyKey:'k'}})).data.value,1);});
test('document switch revokes pairing and kills pending approvals',async()=>{const {p,page,calls}=await setup();const pair=p.pair('CLI',['read','write'],['target']);const cli=p.authenticate(pair.token);const run=p.execute(sidebar,'host_call_tool',call());await new Promise(r=>setImmediate(r));p.dispatch=rebind(p,p.dispatch);page.switchDocument();assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');assert.equal((await run).error.code,'STALE_CONTEXT');assert.equal(calls(),0);const rotated=p.targets.get('target');assert.equal((await p.execute(cli,'host_get_context',rotated)).error.code,'FORBIDDEN');assert.equal((await p.execute(cli,'host_list_tools',rotated)).error.code,'FORBIDDEN');assert.equal((await p.execute(cli,'host_call_tool',{...rotated,call:{requestId:'r',documentId:'demo-document-2',toolName:'demo_increment',arguments:{amount:1},expectedRevision:0,idempotencyKey:'k'}})).error.code,'FORBIDDEN');const pair2=p.pair('CLI2',['read','write'],['target']);const cli2=p.authenticate(pair2.token);assert.equal((await p.execute(cli2,'host_get_context',rotated)).data.documentId,'demo-document-2');});
test('document switch without a native rebind still invalidates',async()=>{const {p,page}=await setup();page.switchDocument();assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');assert.equal(p.targets.size,0);});
test('session epoch appearing, changing or disappearing invalidates authority',async()=>{const {p,page}=await setup();const pair=p.pair('CLI',['read','write'],['target']);const cli=p.authenticate(pair.token);page.setSession('epoch-1');assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');assert.equal(p.targets.size,0,'epoch change without rebind drops the target');const {p:p2,page:page2}=await setup();page2.setSession('epoch-1');p2.dispatch=rebind(p2,p2.dispatch);await p2.execute(sidebar,'host_get_context',target);const bound=p2.targets.get('target');assert.equal(bound.sessionEpoch,'epoch-1');page2.setSession('epoch-2');assert.equal((await p2.execute(sidebar,'host_get_context',bound)).error.code,'STALE_CONTEXT');const rotated=p2.targets.get('target');assert.equal(rotated.sessionEpoch,'epoch-2');assert.notEqual(rotated.pageInstanceId,bound.pageInstanceId);page2.setSession(null);assert.equal((await p2.execute(sidebar,'host_get_context',rotated)).error.code,'STALE_CONTEXT');assert.equal(p2.targets.get('target').sessionEpoch,null);});
test('pending approval cannot execute across a session change',async()=>{const {p,page,calls}=await setup();page.setSession('epoch-1');p.dispatch=rebind(p,p.dispatch);await p.execute(sidebar,'host_get_context',target);const bound=p.targets.get('target');await p.execute(sidebar,'host_list_tools',bound);const run=p.execute(sidebar,'host_call_tool',{...bound,call:{requestId:'r',documentId:'demo-document',toolName:'demo_increment',arguments:{amount:1},expectedRevision:0,idempotencyKey:'k'}});await new Promise(r=>setImmediate(r));page.setSession('epoch-2');assert.equal((await p.execute(sidebar,'host_get_context',bound)).error.code,'STALE_CONTEXT');assert.equal((await run).error.code,'STALE_CONTEXT');assert.equal(calls(),0);});
test('provisional binding fails closed but survives for native promotion',async()=>{const {p,page}=await setup();p.bind({...target,appId:'',documentId:'',sessionEpoch:null,pageInstanceId:'prov'});const prov={...target,appId:'',documentId:'',pageInstanceId:'prov'};assert.equal((await p.execute(sidebar,'host_get_context',prov)).error.code,'STALE_CONTEXT');assert.equal(p.targets.get('target').appId,'','provisional target must persist for discovery');});
// Finding A/D: exercise the real Guava tool catalog (fixtures/canvas.mjs
// loads guava/tool-catalog.json) through host policy. Every descriptor must
// pass safeSchema; reads use null/null envelopes without approval and run
// under a read-only grant; mutations keep CAS + idempotency + approval.
const canvasTarget={targetId:'canvas',pageInstanceId:'cpage',origin:'http://127.0.0.1:4314',appId:'demo-canvas',documentId:'demo-document',title:'Canvas'};
async function canvasSetup(){const page=makeCanvas();let invokes=0;const p=new Policy(async(t,op,c)=>{if(op==='invoke'){invokes++;return page.invoke(c);}return ok(await page[op]());},{timeout:50});p.bind({...canvasTarget});p.heartbeat();await p.execute(sidebar,'host_list_tools',canvasTarget);return {p,page,invokes:()=>invokes};}
const ccall=(toolName,args,rev=null,key=null)=>({...canvasTarget,call:{requestId:'r-'+Math.random(),documentId:'demo-document',toolName,arguments:args,expectedRevision:rev,idempotencyKey:key}});
test('every Guava catalog descriptor passes the host-safe schema gate',async()=>{assert.equal(canvasCatalog.length,7);const {p}=await canvasSetup();const tools=p.tools.get('canvas');assert.equal(tools.length,7);const names=tools.map(t=>t.name);for(const n of['canvas_get_graph','canvas_get_neighbors','evidence_search','evidence_get','canvas_apply_patch','canvas_undo','investigation_propose_conclusion'])assert(names.includes(n),n);});
test('all four Guava read tools execute with null envelopes, no approval',async()=>{const {p,invokes}=await canvasSetup();p.uiUntil=0;assert.equal((await p.execute(sidebar,'host_call_tool',ccall('canvas_get_graph',{}))).data.nodes.length,1);assert.equal((await p.execute(sidebar,'host_call_tool',ccall('canvas_get_neighbors',{nodeIds:['n1'],depth:1}))).data.nodes.length,1);assert.equal((await p.execute(sidebar,'host_call_tool',ccall('evidence_search',{query:'alpha'}))).data.results.length,1);assert.equal((await p.execute(sidebar,'host_call_tool',ccall('evidence_get',{evidenceIds:['ev-1']}))).data.evidence.length,1);assert.equal(invokes(),4);});
test('approved patch, undo and proposal execute through Coconut',async()=>{const {p,invokes}=await canvasSetup();const patch=ccall('canvas_apply_patch',{operations:[{op:'add_node',node:{id:'n2',type:'note',label:'Two',body:'x',position:{x:1,y:2},evidenceIds:['ev-1']}}]},0,'k1');const r1=await approved(p,patch);assert.equal(r1.data.mutationId,'m-1');const undo=ccall('canvas_undo',{mutationId:'m-1'},1,'k2');assert.equal((await approved(p,undo)).data.undone,'m-1');const propose=ccall('investigation_propose_conclusion',{summary:'Lag caused deploy',supportingEvidenceIds:['ev-1'],contradictoryEvidenceIds:[]},2,'k3');assert.equal((await approved(p,propose)).data.nodeId,'c-2');assert.equal(invokes(),3);});
test('valid + invalid arguments for all seven Guava tools',async()=>{const {p,invokes}=await canvasSetup();const bad={'canvas_get_graph':{nodeLimit:500},'canvas_get_neighbors':{nodeIds:[]},'evidence_search':{query:'x'.repeat(201)},'evidence_get':{evidenceIds:['bad id!']},'canvas_apply_patch':{operations:[{op:'nuke'}]},'canvas_undo':{mutationId:'bad id!'},'investigation_propose_conclusion':{summary:''}};for(const [n,a]of Object.entries(bad)){const w=['canvas_apply_patch','canvas_undo','investigation_propose_conclusion'].includes(n);const r=await (w?approved(p,ccall(n,a,w?undefined:null,w?'kbad':null)):p.execute(sidebar,'host_call_tool',ccall(n,a)));assert.equal(r.error?.code,'INVALID_ARGUMENT',n);}assert.equal(invokes(),0,'invalid args must never reach the page');});
test('read envelope rules: CAS on read fails, null envelope on write fails, flipped descriptor cannot smuggle',async()=>{const {p}=await canvasSetup();assert.equal((await p.execute(sidebar,'host_call_tool',ccall('canvas_get_graph',{},0,'k'))).error.code,'INVALID_ARGUMENT');const w=await approved(p,ccall('canvas_apply_patch',{operations:[{op:'auto_layout'}]},null,null));assert.equal(w.error.code,'INVALID_ARGUMENT');p.tools.set('canvas',[{name:'canvas_apply_patch',effect:'read',description:'flipped',inputSchema:canvasCatalog.find(t=>t.name==='canvas_apply_patch').inputSchema}]);const flipped=ccall('canvas_apply_patch',{operations:[{op:'auto_layout'}]});const r=await p.execute(sidebar,'host_call_tool',flipped);assert.equal(r.error.code,'INVALID_ARGUMENT','null-envelope write call is rejected by the app boundary');});
test('read-only MCP grant can read but never mutate',async()=>{const {p}=await canvasSetup();const pair=p.pair('ro',['read'],['canvas']);const c=p.authenticate(pair.token);assert.equal((await p.execute(c,'host_call_tool',ccall('evidence_search',{query:'alpha'}))).data.results.length,1);p.uiUntil=0;assert.equal((await p.execute(c,'host_call_tool',ccall('canvas_apply_patch',{operations:[{op:'auto_layout'}]},0,'k'))).error.code,'FORBIDDEN');assert.equal((await p.execute(c,'host_call_tool',{...canvasTarget,call:ccall('evidence_search',{query:'alpha'}).call})).ok,true,'read path needs no approval heartbeat');});
