import test from 'node:test';import assert from 'node:assert/strict';import {Policy,sidebar,ok,fail} from '../host/policy.mjs';import {makeCounter} from '../fixtures/counter.mjs';
const target={targetId:'target',pageInstanceId:'page',origin:'http://127.0.0.1:4314',appId:'demo-counter',documentId:'demo-document',title:'Fixture'};
async function setup(){const page=makeCounter();let calls=0;const p=new Policy(async(t,op,call)=>{if(op==='invoke'){calls++;return page.invoke(call);}return ok(await page[op]());},{timeout:50});p.bind({...target});p.heartbeat();await p.execute(sidebar,'host_list_tools',target);return {p,page,calls:()=>calls};}
const call=(amount=1,key='key-1',revision=0)=>({...target,call:{requestId:'r',documentId:'demo-document',toolName:'demo_increment',arguments:{amount},expectedRevision:revision,idempotencyKey:key}});
async function approved(p,args,client=sidebar,allow=true){const pending=p.execute(client,'host_call_tool',args);await new Promise(r=>setImmediate(r));for(const a of p.pending.values())p.decide(a.id,allow);return pending;}
test('fixture discovery, context, approved increment, semantic retry, conflict, stale revision',async()=>{const {p}=await setup();assert.equal((await p.execute(sidebar,'host_get_context',target)).data.revision,0);assert.equal((await approved(p,call())).data.value,1);const retry=call();retry.call.requestId='r2';assert.equal((await approved(p,retry)).data.value,1);assert.equal((await approved(p,call(2))).error.code,'IDEMPOTENCY_CONFLICT');assert.equal((await approved(p,call(1,'key-2'))).error.code,'STALE_CONTEXT');});
test('denied approval never dispatches',async()=>{const s=await setup();assert.equal((await approved(s.p,call(),sidebar,false)).error.code,'APPROVAL_DENIED');assert.equal(s.calls(),0);assert.equal((await s.page.getContext()).revision,0);});
test('UI inactive denies writes',async()=>{const {p}=await setup();p.uiUntil=0;assert.equal((await p.execute(sidebar,'host_call_tool',call())).error.code,'APPROVAL_DENIED');});
test('reload / changed origin invalidate approval',async()=>{for(const origin of [target.origin,'https://evil.example']){const {p,calls}=await setup();const run=p.execute(sidebar,'host_call_tool',call());await new Promise(r=>setImmediate(r));p.bind({...target,pageInstanceId:'new',origin});assert.equal((await run).error.code,'STALE_CONTEXT');assert.equal(calls(),0);}});
test('guest close and stale target',async()=>{const {p}=await setup();p.invalidate(target.targetId);assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'TARGET_CLOSED');p.bind({...target,pageInstanceId:'new'});assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');});
test('pair scope visibility revoke expiry forged token',async()=>{const {p}=await setup();const pair=p.pair('CLI',['read'],['target']);const client=p.authenticate(pair.token);assert(client);assert.equal((await p.execute(client,'host_list_targets',{})).data.targets.length,1);assert.equal((await p.execute(client,'host_call_tool',call())).error.code,'FORBIDDEN');assert.equal(p.authenticate('forged'),null);p.revoke(pair.id);assert.equal(p.authenticate(pair.token),null);const hidden=p.pair('other',['read'],[]);assert.deepEqual((await p.execute(p.authenticate(hidden.token),'host_list_targets',{})).data.targets,[]);p.authenticate(hidden.token).expires=0;assert.equal(p.authenticate(hidden.token),null);});
test('client revoke while approval pending fails closed',async()=>{const {p,calls}=await setup();const pair=p.pair('CLI',['read','write'],['target']);const run=p.execute(p.authenticate(pair.token),'host_call_tool',call());await new Promise(r=>setImmediate(r));p.revoke(pair.id);assert.equal((await run).error.code,'STALE_CONTEXT');assert.equal(calls(),0);});
test('payload injection/schema, privileged fields and unknown tool rejected',async()=>{const {p}=await setup();const a=call();a.call.arguments.amount="');globalThis.pwned=true;//";assert.equal((await p.execute(sidebar,'host_call_tool',a)).error.code,'INVALID_ARGUMENT');const b=call();b.call.approved=true;assert.equal((await p.execute(sidebar,'host_call_tool',b)).error.code,'INVALID_ARGUMENT');const c=call();c.call.toolName='shell_exec';assert.equal((await p.execute(sidebar,'host_call_tool',c)).error.code,'UNSUPPORTED');});
test('canonical frozen approval payload cannot be mutated by caller',async()=>{const {p}=await setup();const args=call();const run=p.execute(sidebar,'host_call_tool',args);await new Promise(r=>setImmediate(r));args.call.arguments.amount=99;for(const a of p.pending.values())p.decide(a.id,true);assert.equal((await run).data.value,1);});
test('unsupported bridge and timeout',async()=>{const p=new Policy(async()=>fail('UNSUPPORTED'),{timeout:10});p.bind(target);assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'UNSUPPORTED');p.dispatch=()=>new Promise(()=>{});assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'TIMEOUT');});
test('cancellation before approval dispatch',async()=>{const {p,calls}=await setup();const c=new AbortController();const run=p.execute(sidebar,'host_call_tool',call(),c.signal);await new Promise(r=>setImmediate(r));c.abort();assert.equal((await run).error.code,'CANCELLED');assert.equal(calls(),0);});
test('malformed guest response fails at boundary',async()=>{const {p}=await setup();p.dispatch=async()=>({ok:true,revision:0,data:{},error:{code:'INTERNAL',message:'inconsistent',retryable:false}});assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'INVALID_ARGUMENT');});
test('logout result revokes target',async()=>{const {p}=await setup();p.dispatch=async()=>fail('UNAUTHORIZED');assert.equal((await p.execute(sidebar,'host_get_context',target)).error.code,'STALE_CONTEXT');assert.equal(p.targets.size,0);});
