import React,{useEffect,useState} from "react";
import {translateUI as t} from "./i18n.ts";
import {awardUnitLabel} from "../shared/programs.ts";
type Actions={busy:boolean;op:(name:string,args?:Record<string,unknown>)=>Promise<any>;mutate:(name:string,args:Record<string,unknown>)=>Promise<any>;run:(fn:()=>Promise<void>)=>Promise<boolean>;};
function OriginalDefinition({offer}:{offer:any}){const value=offer.definition;return <div><h5>{value.title}</h5><p>{value.summary}</p>{offer.kind==="award"&&<><p>{t(value.completionMode==="one_item"?"Complete one configured criterion":value.ongoing?"Ongoing program":"Target")}: {value.target} {awardUnitLabel(value,value.target)}</p><p>{t("Source external moderation")}: {String(value.moderatedExternal)} · {t("Source primary assessor requirement")}: {String(!!value.primaryModeration)}</p>{value.requirements.map((r:any)=><div key={r.id}><strong>{r.title}</strong><p>{r.required?t("Required criterion"):t("Elective")} · {r.credits} {awardUnitLabel(value,r.credits)} · {t(r.creditMode==="nested_earned"?"Actual earned child award credits":"Fixed criterion quantity")}</p><ul>{r.alternatives.map((ref:any)=><li key={ref.kind+":"+ref.id}>{ref.kind} · {ref.id} {ref.version?"· v"+ref.version:""}</li>)}</ul></div>)}</>}</div>;}
function IncomingOffer({offer,actions,reload}:{offer:any;actions:Actions;reload:()=>Promise<void>}){
 const [mappings,setMappings]=useState<Record<string,{id:string;version:number}>>({}),[confirmed,setConfirmed]=useState(false);
 return <article className="learning-row"><h4>{t("Incoming original collection offer")} · {offer.id}</h4><p>{offer.sourceTenant} · {offer.destinationCollection} · {offer.state}</p><p>{t("Collection offer expiry")}: {offer.expiresAt}</p>
 {offer.available?<form aria-label={t("Review original collection copy")} onSubmit={event=>{event.preventDefault();if(!confirmed)return;void actions.run(async()=>{await actions.mutate("human_accept_original_collection_offer",{offerId:offer.id,expectedVersion:offer.version,references:offer.references.map((ref:any)=>({kind:ref.kind,sourceId:ref.id,destinationId:mappings[ref.kind+":"+ref.id]?.id??"",version:mappings[ref.kind+":"+ref.id]?.version??1})),confirmed:true});await reload();});}}>
 <p>{t("Review the original definition and map every reference to your authorized published local content. This creates an author-only draft; no media, learner history, assessor grants or publication is copied.")}</p>
 <OriginalDefinition offer={offer}/><fieldset disabled={actions.busy}>
 {offer.references.map((ref:any)=>{const key=ref.kind+":"+ref.id,value=mappings[key]??{id:"",version:1};return <fieldset key={key}><legend>{ref.kind} · {ref.id} · v{ref.version}</legend><label>{t("Authorized local reference ID")}<input required maxLength={64} value={value.id} onChange={event=>{setMappings({...mappings,[key]:{...value,id:event.target.value}});setConfirmed(false);}}/></label><label>{t("Reviewed local reference version")}<input required type="number" min={1} max={1000000} value={value.version} onChange={event=>{setMappings({...mappings,[key]:{...value,version:Number(event.target.value)}});setConfirmed(false);}}/></label></fieldset>;})}
 <label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t("I reviewed this original definition and the local reference rights.")}</label><button disabled={!confirmed}>{t("Create reviewed original collection draft")}</button></fieldset>
 </form>:<p>{t("Offer is no longer reviewable. Original definition is withheld; accepted local drafts and prior official learning remain independent.")}</p>}
 </article>;
}
function OutgoingOffer({offer,actions,reload}:{offer:any;actions:Actions;reload:()=>Promise<void>}){
 const [reason,setReason]=useState("");return <article className="learning-row"><h4>{t("Outgoing original collection offer")} · {offer.id}</h4><p>{offer.destinationTenant} · {offer.destinationCollection} · {offer.state}</p>{offer.state==="pending"&&<form aria-label={t("Cancel own collection offer")} onSubmit={event=>{event.preventDefault();void actions.run(async()=>{await actions.mutate("human_cancel_original_collection_offer",{offerId:offer.id,expectedVersion:offer.version,reason});await reload();});}}><label>{t("Offer cancellation reason")}<input required maxLength={300} value={reason} onChange={event=>setReason(event.target.value)}/></label><button disabled={actions.busy}>{t("Cancel own collection offer")}</button></form>}</article>;
}
export function OriginalCollectionSharing({actions,tick}:{actions:Actions;tick:number}){
 const [direction,setDirection]=useState("incoming"),[offset,setOffset]=useState(0),[page,setPage]=useState<any>({items:[],nextOffset:null}),[error,setError]=useState(""),[confirmed,setConfirmed]=useState(false);
 const reload=async()=>setPage(await actions.op("human_get_original_collection_offers",{direction,offset,limit:10}));
 useEffect(()=>{let current=true;actions.op("human_get_original_collection_offers",{direction,offset,limit:10}).then(value=>{if(current){setPage(value);setError("");}},failure=>{if(current)setError(failure instanceof Error?failure.message:"Collection offers unavailable");});return()=>{current=false;};},[direction,offset,tick]);
 return <section className="panel" style={{overflowWrap:"anywhere"}} aria-label={t("Original collection sharing")}><h3>{t("Original collection sharing")}</h3><p>{t("Explicit administrator review across tenants. Only original configuration is offered; destination content rights are checked independently.")}</p>
 <form aria-label={t("Offer original collection configuration")} onSubmit={event=>{event.preventDefault();if(!confirmed)return;const values=new FormData(event.currentTarget);void actions.run(async()=>{await actions.mutate("human_offer_original_collection",{collectionId:values.get("collection"),sourceVersion:Number(values.get("version")),destinationTenant:values.get("tenant"),destinationAdminId:values.get("admin"),destinationCollectionId:values.get("destination"),confirmed:true});setConfirmed(false);await reload();});}}><fieldset disabled={actions.busy}>
 <label>{t("Own published collection ID")}<input required name="collection" maxLength={64}/></label><label>{t("Reviewed source collection version")}<input required name="version" type="number" min={1} max={1000000} defaultValue={1}/></label>
 <label>{t("Destination tenant ID")}<input required name="tenant" maxLength={64}/></label><label>{t("Explicit destination administrator ID")}<input required name="admin" maxLength={64}/></label><label>{t("New destination collection ID")}<input required name="destination" maxLength={64}/></label>
 <label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t("I authorize offering only this original configuration to this administrator.")}</label><button disabled={!confirmed}>{t("Offer original configuration for review")}</button></fieldset></form>
 <label>{t("Own collection offer direction")}<select disabled={actions.busy} aria-label={t("Own collection offer direction")} value={direction} onChange={event=>{setDirection(event.target.value);setOffset(0);setPage({items:[],nextOffset:null});}}><option value="incoming">{t("Incoming offers")}</option><option value="outgoing">{t("Outgoing offers")}</option></select></label>
 {error&&<p role="alert">{error}</p>}{page.items.map((offer:any)=>direction==="incoming"?<IncomingOffer key={offer.id} offer={offer} actions={actions} reload={reload}/>:<OutgoingOffer key={offer.id} offer={offer} actions={actions} reload={reload}/>)}
 <button disabled={offset===0||actions.busy} onClick={()=>setOffset(Math.max(0,offset-10))}>{t("Previous collection offers")}</button><button disabled={page.nextOffset===null||actions.busy} onClick={()=>setOffset(page.nextOffset)}>{t("Next collection offers")}</button>
 </section>;
}
