import {getUILocale,type UILocale} from "./i18n.ts";
// Exact known diagnostic literals only; authored/unknown values remain literal.
export const vietnameseDiagnostics:Readonly<Record<string,string>>=Object.freeze({"Completed own standalone reading required":"Cần nội dung độc lập của bạn đã được xác nhận học","Standalone retake version changed; review again":"Phiên bản học lại nội dung độc lập đã thay đổi; xem xét lại","A standalone successor already exists; continue that record":"Đã có bản học mới cho nội dung độc lập; tiếp tục bản đó","Active root course cycle delivery required":"Cần bản giao khóa học gốc theo chu kỳ đang hoạt động","Current cycle plan owner required":"Cần chủ kế hoạch chu kỳ hiện tại","Cycle delivery changed; refresh before restarting":"Bản giao theo chu kỳ đã thay đổi; tải lại trước khi học lại","Latest course restart is unavailable or changed; review again":"Không thể học lại bản khóa mới nhất từ đầu hoặc dữ liệu đã thay đổi. Hãy xem xét lại.","Report authority changed":"Quyền truy cập báo cáo đã thay đổi.","Report export role required":"Cần vai trò có quyền xuất báo cáo.","Review exact report export scope before PDF download":"Hãy xem xét đúng phạm vi xuất báo cáo trước khi tải PDF.","Report exceeds server PDF row bounds; use CSV or browser print":"Báo cáo vượt giới hạn số dòng PDF từ máy chủ. Hãy dùng CSV hoặc chức năng in của trình duyệt.","Review current transcript before PDF export":"Hãy xem bảng ghi học tập hiện tại trước khi xuất PDF.","Transcript exceeds server PDF row bounds; use CSV or browser print":"Bảng ghi học tập vượt giới hạn số dòng PDF từ máy chủ. Hãy dùng CSV hoặc chức năng in của trình duyệt.","Original PDF text exceeds document bounds; use CSV or browser print":"Nội dung PDF gốc vượt giới hạn tài liệu. Hãy dùng CSV hoặc chức năng in của trình duyệt.","Original PDF exceeds page bounds; use CSV or browser print":"PDF gốc vượt giới hạn số trang. Hãy dùng CSV hoặc chức năng in của trình duyệt.","Assignment review changed; refresh before offering":"Đề xuất bài được giao đã thay đổi. Hãy làm mới trước khi đề xuất.","A current coordinator review already exists":"Đã có đề xuất của người quản lý còn hiệu lực.","Accepted assignment review is immutable":"Không thể thay đổi đề xuất bài được giao đã được chấp nhận.","Own pending assignment review required":"Cần đề xuất bài được giao đang chờ thuộc quyền của bạn.","Assignment review is no longer pending":"Đề xuất bài được giao không còn ở trạng thái chờ.","Active assignment participant required":"Cần người tham gia bài được giao đang hoạt động.","Active unfinished direct assignment required":"Cần bài được giao trực tiếp đang hoạt động và chưa hoàn thành.","Current assignment coordinator required":"Cần người quản lý hiện có quyền với bài được giao.","Own current assignment review required":"Cần đề xuất bài được giao còn hiệu lực dành cho bạn.","Assigned quiz target changed; request a new coordinator review":"Phiên bản quiz được giao đã thay đổi. Hãy yêu cầu người quản lý xem xét lại.","A coordinator review already exists for this version":"Đã có đề xuất của người quản lý cho phiên bản này.","Assignment review quota reached":"Đã đạt giới hạn đề xuất xem xét bài được giao.",
  "Submitted essay assessment scope denied": "Bạn không có quyền đánh giá bài tự luận đã nộp này.",
  "Attempt is no longer awaiting authorized review": "Lần làm bài không còn chờ người có quyền đánh giá.",
  "Admin reset required": "Cần quản trị viên đặt lại quyền làm bài.",
  "Only active unfinished learning can receive further attempts": "Chỉ bản ghi học tập đang hoạt động và chưa hoàn thành mới được thêm lượt làm bài.",
  "Finish the current assessment before a retry allowance": "Hoàn tất đánh giá hiện tại trước khi cấp thêm lượt làm bài.",
  "Human-only assessment detail": "Chi tiết đánh giá chỉ dành cho người dùng trực tiếp.",
  "Active same-tenant course assessor required": "Cần người đánh giá đang hoạt động và được phân quyền cho khóa học trong cùng tenant.",
  "Reset reason required": "Cần nhập lý do đặt lại.",
  "Retry allowance cap reached": "Đã đạt giới hạn cấp thêm lượt làm bài.",
  "Attempt is already finalized": "Lần làm bài đã có kết quả cuối cùng.",
  "Invalid rubric grade/reason": "Điểm theo tiêu chí hoặc lý do đánh giá không hợp lệ.",
  "Final question review is immutable": "Không thể sửa đánh giá cuối cùng của câu hỏi.",
  "Use a valid UTC ISO timestamp": "Dùng thời điểm UTC theo định dạng ISO hợp lệ.",
  "Assignment plan scope denied": "Bạn không có quyền với kế hoạch giao học này.",
  "Plan owner no longer has assignment authority": "Người sở hữu kế hoạch không còn quyền giao học.",
  "Assignment recipient outside active audience scope": "Người nhận không thuộc đối tượng hiện được phép giao học.",
  "Invalid assignment target": "Nội dung được giao không hợp lệ.",
  "Assignment target unavailable": "Nội dung được giao hiện không khả dụng.",
  "Target version unavailable": "Phiên bản được giao hiện không khả dụng.",
  "Scheduled awards require organization access": "Chương trình giao theo lịch cần có phạm vi truy cập tổ chức.",
  "Invalid assignment plan": "Kế hoạch giao học không hợp lệ.",
  "Monthly recurrence requires a timezone, DST choice and no UTC-day cadence": "Lặp hằng tháng cần múi giờ, lựa chọn DST và không dùng chu kỳ ngày UTC.",
  "Calendar settings require monthly recurrence": "Thiết lập lịch này cần chế độ lặp hằng tháng.",
  "End must not precede start": "Thời điểm kết thúc không được trước thời điểm bắt đầu.",
  "Fixed deadline must follow start and have no rolling offset": "Hạn cố định phải sau thời điểm bắt đầu và không kết hợp hạn tính tương đối.",
  "Invalid due date policy": "Quy tắc hạn hoàn thành không hợp lệ.",
  "Individual audience requires fixed member IDs": "Đối tượng cá nhân cần danh sách mã thành viên cố định.",
  "Group audience requires group ID and no explicit IDs": "Đối tượng nhóm cần mã nhóm và không kèm danh sách mã cá nhân.",
  "Cancelled plan is immutable; create a new plan": "Không thể sửa kế hoạch đã hủy; hãy tạo kế hoạch mới.",
  "Notification access denied": "Bạn không có quyền đọc thông báo này.",
  "Calendar deadline precedes its cycle": "Hạn hoàn thành nằm trước thời điểm của kỳ giao học.",
  "Active own award enrollment required": "Cần bản đăng ký chương trình đang hoạt động của chính bạn.",
  "Award graph invalid": "Cấu trúc liên kết chương trình không hợp lệ.",
  "Course outside enrolled award rules": "Khóa học nằm ngoài quy tắc của chương trình đã đăng ký.",
  "Course unavailable": "Khóa học hiện không khả dụng.",
  "Unknown assignment read": "Không nhận diện được thao tác đọc dữ liệu giao học.",
  "Plan ID and change reason required": "Cần mã kế hoạch và lý do thay đổi.",
  "Reason required; cancelled plans cannot reactivate": "Cần lý do; không thể kích hoạt lại kế hoạch đã hủy.",
  "Unknown assignment write": "Không nhận diện được thao tác thay đổi dữ liệu giao học.",
  "Use an explicit offset or Z for event instants": "Thời điểm sự kiện cần có độ lệch múi giờ hoặc ký hiệu Z.",
  "Invalid event calendar date": "Ngày trong lịch sự kiện không hợp lệ.",
  "Session course unavailable": "Khóa học của buổi học hiện không khả dụng.",
  "Session instructor scope denied": "Bạn không có quyền giảng viên với buổi học này.",
  "Scoped session unavailable": "Buổi học trong phạm vi quyền hiện không khả dụng.",
  "Session booking history unavailable": "Lịch sử đặt chỗ của buổi học hiện không khả dụng.",
  "Explain the session change": "Hãy nhập lý do thay đổi buổi học.",
  "Past or started sessions cannot be changed": "Không thể sửa buổi học đã qua hoặc đã bắt đầu.",
  "Session change history limit reached": "Đã đạt giới hạn lịch sử thay đổi buổi học.",
  "Cancel a scheduled session without a replacement definition": "Hủy buổi học đã lên lịch mà không kèm cấu hình thay thế.",
  "Reschedule requires the same explicit session identity": "Đổi lịch cần giữ đúng mã định danh buổi học đã chọn.",
  "New session and rebooking cutoff must be in the future": "Buổi học mới và hạn đặt lại chỗ phải ở trong tương lai.",
  "Session booking population exceeds capacity bounds": "Số lượt đặt chỗ vượt giới hạn sức chứa của buổi học.",
  "Submission requires rubric, attempt and pass policy": "Bài nộp cần tiêu chí đánh giá, số lượt và quy tắc đạt.",
  "Event requires distinct session definitions": "Sự kiện cần các cấu hình buổi học có định danh riêng.",
  "Session end/cutoff order invalid": "Thứ tự thời điểm kết thúc và hạn đăng ký không hợp lệ.",
  "Unknown IANA timezone": "Không nhận diện được múi giờ IANA.",
  "Invalid event join URL": "Đường dẫn tham gia sự kiện không hợp lệ.",
  "Event join URL must use HTTPS without credentials": "Đường dẫn tham gia phải dùng HTTPS và không chứa thông tin đăng nhập.",
  "Unexpected submission/event settings": "Có thiết lập bài nộp hoặc sự kiện không được hỗ trợ.",
  "Published session identity is immutable; use a new ID to reschedule": "Mã định danh buổi học đã xuất bản không thể thay đổi; dùng mã mới khi đổi lịch.",
  "Course operation scope denied": "Bạn không có quyền thực hiện thao tác này với khóa học.",
  "Blended lesson unavailable": "Bài học kết hợp hiện không khả dụng.",
  "Complete prerequisite lessons first": "Hãy hoàn thành các bài học tiên quyết trước.",
  "Submission unavailable": "Bài nộp hiện không khả dụng.",
  "Booking unavailable": "Lượt đặt chỗ hiện không khả dụng.",
  "Pinned session unavailable": "Phiên bản buổi học đã gắn với bản đăng ký hiện không khả dụng.",
  "Own session notice required": "Chỉ được dùng thông báo buổi học của chính bạn.",
  "Learning obligation is no longer open": "Nhiệm vụ học tập không còn mở.",
  "Reviewer required": "Cần người có quyền đánh giá.",
  "Unknown learning operation": "Không nhận diện được thao tác học tập.",
  "Confirmed submission required": "Cần xác nhận nộp bài trực tiếp.",
  "Submission is pending review or already passed": "Bài nộp đang chờ đánh giá hoặc đã đạt.",
  "Submission attempt limit reached": "Đã đạt giới hạn số lượt nộp bài.",
  "Upload belongs to another assignment": "Tệp tải lên thuộc một bài được giao khác.",
  "Submission already reviewed": "Bài nộp đã được đánh giá.",
  "Assessment reason required": "Cần nhập lý do đánh giá.",
  "Unknown pinned session": "Không nhận diện được phiên bản buổi học đã gắn với bản đăng ký.",
  "Session cancelled; choose an available session explicitly": "Buổi học đã hủy; hãy chủ động chọn buổi học còn khả dụng.",
  "Booking cutoff has passed": "Đã qua hạn đặt chỗ.",
  "Already booked or attended": "Đã đặt chỗ hoặc được ghi nhận tham dự.",
  "Session is full": "Buổi học đã hết chỗ.",
  "Booking history limit reached": "Đã đạt giới hạn lịch sử đặt chỗ.",
  "Only upcoming unassessed booking can be cancelled": "Chỉ được hủy lượt đặt chỗ sắp tới chưa được đánh giá.",
  "Attendance requires an unassessed session that has started": "Ghi nhận tham dự cần buổi học đã bắt đầu và chưa được đánh giá.",
  "Attendance reason required": "Cần nhập lý do ghi nhận tham dự.",
  "Calendar obligation is no longer active": "Nhiệm vụ trong lịch không còn hoạt động.",
  "Active booking required": "Cần lượt đặt chỗ đang hoạt động.",
  "Certificate font lacks a required character; use the original text or browser print export": "Phông chữ PDF thiếu ký tự cần thiết; hãy dùng bản văn bản gốc hoặc chức năng in của trình duyệt.",
  "Certificate exceeds PDF text bounds": "Nội dung chứng chỉ vượt giới hạn văn bản của PDF.",
  "Server certificate supports original Latin/Vietnamese text; use text or browser print for other scripts": "PDF từ máy chủ hỗ trợ chữ Latin và tiếng Việt; dùng bản văn bản hoặc in từ trình duyệt cho hệ chữ khác.",
  "Certificate exceeds single-page layout bounds": "Nội dung chứng chỉ vượt giới hạn bố cục một trang.",
  "Certificate PDF exceeds export bounds": "PDF chứng chỉ vượt giới hạn xuất tệp.",
  "Tenant administrator required": "Cần quyền quản trị viên của tenant.",
  "Review the current published own-tenant collection": "Hãy xem xét phiên bản hiện đang xuất bản của chương trình trong tenant của bạn.",
  "Explicit active other-tenant administrator and valid destination ID required": "Cần chọn quản trị viên đang hoạt động ở tenant khác và mã chương trình đích hợp lệ.",
  "Collection offer supports at most 64 distinct local reference mappings": "Mỗi đề nghị hỗ trợ tối đa 64 ánh xạ tham chiếu nội dung riêng.",
  "Own addressed collection offer required": "Chỉ được dùng đề nghị do bạn tạo hoặc gửi trực tiếp cho bạn.",
  "Collection offer cancelled or expired": "Đề nghị chia sẻ đã hủy hoặc hết hạn.",
  "Current source administrator and published collection authority required": "Cần quyền hiện tại của quản trị viên nguồn và chương trình nguồn còn xuất bản.",
  "Duplicate reference mapping": "Ánh xạ tham chiếu bị trùng.",
  "Every original local reference requires exactly one destination mapping": "Mỗi tham chiếu nguồn cần đúng một ánh xạ nội dung ở bên nhận.",
  "Destination reference is unavailable or version changed": "Nội dung tham chiếu ở bên nhận không khả dụng hoặc phiên bản đã thay đổi.",
  "Source pending offer and cancellation reason required": "Cần đề nghị đang chờ do bạn tạo và lý do hủy.",
  "Offer version changed": "Phiên bản đề nghị đã thay đổi.",
  "Only explicitly addressed receiving administrator may accept": "Chỉ quản trị viên được chọn làm bên nhận mới có thể chấp nhận.",
  "Destination collection ID is occupied": "Mã chương trình đích đã được sử dụng.",
  "Operational quota of 500 original offers per source administrator reached": "Đã đạt giới hạn 500 đề nghị cho quản trị viên nguồn.",
  "Refresh current pending offer before a new operation": "Hãy làm mới đề nghị đang chờ trước khi thực hiện thao tác mới.",
  "Content is outside the current audience": "Nội dung nằm ngoài đối tượng hiện được phép truy cập.",
  "Content author scope denied": "Bạn không có quyền tác giả với nội dung này.",
  "Select one to eight distinct existing own-tenant groups": "Chọn từ một đến tám nhóm khác nhau đang tồn tại trong tenant của bạn.",
  "Group IDs require the groups audience": "Mã nhóm chỉ dùng khi chọn đối tượng theo nhóm.",
  "Pinned content unavailable": "Phiên bản nội dung đã gắn với bản đăng ký hiện không khả dụng.",
  "Only the owner may restrict content to its author": "Chỉ người sở hữu được giới hạn nội dung cho riêng tác giả.",
  "Published content unavailable": "Nội dung đã xuất bản hiện không khả dụng.",
  "Group content cannot be redistributed outside its declared group audience": "Không được chia sẻ lại nội dung nhóm ra ngoài các nhóm đã khai báo.",
  "Author-only content cannot be redistributed to a wider audience": "Không được chia sẻ nội dung riêng của tác giả cho đối tượng rộng hơn.",
  "Invalid content kind": "Loại nội dung không hợp lệ.",
  "Content unavailable": "Nội dung hiện không khả dụng.",
  "Content administrator required": "Cần quyền quản trị nội dung.",
  "Replacement must be different content": "Nội dung thay thế phải khác nội dung nguồn.",
  "Source is not retired": "Nội dung nguồn chưa được ngừng cung cấp.",
  "Retirement impact changed; preview the exact replacement again": "Ảnh hưởng của việc ngừng cung cấp đã thay đổi; hãy xem lại đúng nội dung thay thế.",
  "Own unexpired digest required": "Cần bản tổng hợp của chính bạn còn hiệu lực.",
  "Use a valid named timezone, distinct weekdays and resolvable schedule": "Dùng múi giờ hợp lệ, các ngày trong tuần không trùng và lịch có thể xác định được.",
  "Use a recognized IANA time zone": "Dùng múi giờ IANA được hỗ trợ.",
  "Duration range is reversed": "Thời lượng tối thiểu không được lớn hơn thời lượng tối đa.",
  "Use a valid UTC publication date": "Dùng ngày xuất bản UTC hợp lệ.",
  "Compare distinct course IDs": "Chọn các mã khóa học khác nhau để so sánh.",
  "Comparison source unavailable": "Nội dung cần so sánh hiện không khả dụng.",
  "Own completed enrollment required for feedback": "Chỉ được phản hồi bản đăng ký đã hoàn thành của chính bạn.",
  "Rating scope denied": "Bạn không có quyền đánh giá nội dung này.",
  "Rating version unavailable": "Phiên bản cần đánh giá hiện không khả dụng.",
  "Tenant feedback administrator required": "Cần quyền quản trị phản hồi trong tenant.",
  "Active account required": "Cần tài khoản đang hoạt động.",
  "Identity settings require tenant administrator": "Thiết lập danh tính cần quyền quản trị viên của tenant.",
  "OIDC provider is not configured": "Chưa cấu hình nhà cung cấp OIDC.",
  "Invalid reviewed identity mapping": "Liên kết danh tính đã xem xét không hợp lệ.",
  "Active same-tenant user required": "Cần người dùng đang hoạt động trong cùng tenant.",
  "Identity mapping request changed": "Yêu cầu liên kết danh tính đã thay đổi.",
  "Identity settings changed; refresh": "Thiết lập danh tính đã thay đổi; hãy làm mới.",
  "Subject is linked to another account; unlink explicitly first": "Subject đã liên kết với tài khoản khác; hãy chủ động bỏ liên kết trước.",
  "User already has a subject for this issuer": "Người dùng đã có subject cho issuer này.",
  "Identity transaction capacity reached": "Đã đạt giới hạn giao dịch xác thực danh tính.",
  "Identity response rejected": "Phản hồi xác thực danh tính bị từ chối.",
  "Identity state expired or unavailable": "Trạng thái xác thực danh tính đã hết hạn hoặc không khả dụng.",
  "Identity has no active reviewed account mapping": "Danh tính chưa có liên kết đã xem xét với tài khoản đang hoạt động.",
  "Identity verification failed; restart sign-in": "Xác minh danh tính không thành công; hãy bắt đầu đăng nhập lại.",
  "Own insight ledger changed; refresh the first page": "Dữ liệu học tập của bạn đã thay đổi; hãy làm mới trang đầu.",
  "Active administrator required": "Cần quản trị viên đang hoạt động.",
  "Integration credentials require tenant administrator": "Thông tin xác thực tích hợp cần quyền quản trị viên của tenant.",
  "Invalid reviewed integration credential": "Thông tin xác thực tích hợp đã xem xét không hợp lệ.",
  "Unsupported credential field": "Trường thông tin xác thực không được hỗ trợ.",
  "Use reviewed provisioning scopes and 1–30 day expiration": "Dùng phạm vi cấp phát đã xem xét và thời hạn từ 1 đến 30 ngày.",
  "Credential request changed": "Yêu cầu thông tin xác thực đã thay đổi.",
  "Own credential required": "Chỉ được dùng thông tin xác thực thuộc quyền của bạn.",
  "Integration settings changed; refresh": "Thiết lập tích hợp đã thay đổi; hãy làm mới.",
  "Integration credential quota reached": "Đã đạt giới hạn thông tin xác thực tích hợp.",
  "Provisioning credential required": "Cần thông tin xác thực cấp phát người dùng.",
  "Provisioning credential expired or revoked": "Thông tin xác thực cấp phát đã hết hạn hoặc bị thu hồi.",
  "Provisioning scope required": "Cần phạm vi quyền cấp phát.",
  "Content author required": "Cần quyền tác giả nội dung.",
  "Invalid upload metadata; confirm self-authored content": "Thông tin tệp tải lên không hợp lệ; hãy xác nhận nội dung tự soạn.",
  "Award evidence requires a scoped PDF": "Bằng chứng chương trình cần tệp PDF đúng phạm vi.",
  "Assignment upload requires a scoped PDF": "Bài nộp cần tệp PDF đúng phạm vi được giao.",
  "Open own assignment required": "Cần nhiệm vụ học tập còn mở của chính bạn.",
  "Submission lesson must be unlocked": "Bài học có yêu cầu nộp bài phải được mở khóa.",
  "File must contain 1 byte to 8 MiB": "Tệp phải có dung lượng từ 1 byte đến 8 MiB.",
  "Unsupported file or format signature mismatch": "Tệp không được hỗ trợ hoặc dấu hiệu định dạng không khớp.",
  "Upload operation changed": "Thao tác tải lên đã thay đổi.",
  "Library changed; refresh before uploading": "Thư viện đã thay đổi; hãy làm mới trước khi tải lên.",
  "Tenant upload quota reached": "Đã đạt giới hạn tải lên của tenant.",
  "Asset unavailable in this tenant": "Tệp nội dung không khả dụng trong tenant này.",
  "Asset format does not match content kind": "Định dạng tệp không khớp loại nội dung.",
  "Asset access denied": "Bạn không có quyền truy cập tệp nội dung này.",
  "Award evidence review scope denied": "Bạn không có quyền xét duyệt bằng chứng chương trình này.",
  "Submission file review scope denied": "Bạn không có quyền xét duyệt tệp bài nộp này.",
  "Read an authorized published item or unlocked lesson": "Chọn nội dung đã xuất bản được phép đọc hoặc bài học đã mở khóa.",
  "External record scope denied": "Bạn không có quyền truy cập bản ghi học tập bên ngoài này.",
  "Primary assessor scope denied": "Bạn không có quyền của người đánh giá chính với bản ghi này.",
  "This pending evidence requires its designated primary assessor": "Bằng chứng đang chờ cần đúng người đánh giá chính đã được chỉ định.",
  "Assessor notice scope required": "Cần quyền đọc thông báo đánh giá.",
  "Own notice required": "Chỉ được dùng thông báo của chính bạn.",
  "Tenant administrator assignment required": "Cần quản trị viên của tenant thực hiện phân công.",
  "Only pending evidence may be assigned": "Chỉ được phân công bằng chứng đang chờ đánh giá.",
  "Existing active same-tenant delegated assessor required": "Cần người đánh giá đang hoạt động, cùng tenant và đã được phân quyền.",
  "Assignment reason required": "Cần nhập lý do phân công.",
  "Primary assignment changed; refresh current record": "Phân công người đánh giá chính đã thay đổi; hãy làm mới bản ghi.",
  "Refresh current primary assignment before a new operation": "Hãy làm mới phân công hiện tại trước khi thực hiện thao tác mới.",
  "Operational quota of 100 primary assignments per record reached": "Đã đạt giới hạn 100 lần phân công người đánh giá chính cho bản ghi này.",
  "Invalid offset": "Vị trí phân trang không hợp lệ.",
  "Host mismatch": "Địa chỉ máy chủ không khớp.",
  "Webhook settings require tenant administrator": "Thiết lập webhook cần quyền quản trị viên của tenant.",
  "Invalid reviewed webhook action": "Thao tác webhook đã xem xét không hợp lệ.",
  "Unsupported webhook field": "Trường webhook không được hỗ trợ.",
  "Select reviewed endpoint and explicit event topics": "Chọn endpoint đã xem xét và các chủ đề sự kiện cụ thể.",
  "Own subscription required": "Chỉ được dùng đăng ký thuộc quyền của bạn.",
  "Live subscription and explicit failed event required": "Cần đăng ký đang hoạt động và sự kiện lỗi đã chọn.",
  "Webhook action changed": "Thao tác webhook đã thay đổi.",
  "Webhook review is stale": "Thông tin xem xét webhook đã cũ.",
  "Subscription quota reached": "Đã đạt giới hạn số đăng ký.",
  "Only an explicit failed event may be retried": "Chỉ được thử lại sự kiện lỗi đã chọn cụ thể.",
  "Only after and limit supported": "Chỉ hỗ trợ tham số after và limit.",
  "Invalid event cursor": "Con trỏ sự kiện không hợp lệ.",
  "Invalid identity/profile or duplicate fields": "Danh tính, hồ sơ hoặc các trường bị trùng không hợp lệ.",
  "Identity belongs to another organization": "Danh tính thuộc tổ chức khác.",
  "Organization requires at least one active administrator": "Tổ chức cần ít nhất một quản trị viên đang hoạt động.",
  "Manager must be active, same-tenant and authorized for reports": "Người quản lý phải đang hoạt động, cùng tenant và có quyền xem báo cáo.",
  "Manager relationship cycle": "Quan hệ người quản lý tạo thành vòng lặp.",
  "Invalid group definition": "Cấu hình nhóm không hợp lệ.",
  "Static groups cannot have dynamic rules": "Nhóm cố định không được có quy tắc động.",
  "Group member outside organization": "Thành viên nhóm nằm ngoài tổ chức.",
  "Dynamic group requires rules and no fixed members": "Nhóm động cần quy tắc và không có danh sách thành viên cố định.",
  "Custom field rule requires a field name": "Quy tắc trường tùy chỉnh cần tên trường.",
  "Field selector only allowed for customField rules": "Chỉ quy tắc customField được chọn trường.",
  "Date rules require a valid UTC calendar date on createdAt": "Quy tắc ngày cần ngày UTC hợp lệ trên trường createdAt.",
  "Active rules compare true/false": "Quy tắc trạng thái hoạt động so sánh giá trị true hoặc false.",
  "Group unavailable": "Nhóm hiện không khả dụng.",
  "Group belongs to another organization": "Nhóm thuộc tổ chức khác.",
  "Unknown people read": "Không nhận diện được thao tác đọc dữ liệu người dùng.",
  "Duplicate interests": "Mối quan tâm bị trùng.",
  "CSV invalid; review dry-run row errors": "CSV không hợp lệ; hãy xem lỗi từng dòng trong bản chạy thử.",
  "Import review is stale; rerun dry-run": "Bản xem xét nhập dữ liệu đã cũ; hãy chạy thử lại.",
  "Invalid group ID": "Mã nhóm không hợp lệ.",
  "Unknown people write": "Không nhận diện được thao tác thay đổi dữ liệu người dùng.",
  "Portal settings require tenant administrator": "Thiết lập cổng học tập cần quyền quản trị viên của tenant.",
  "Use nonempty portal name and printable presentation text": "Tên cổng học tập không được để trống; phần trình bày cần dùng văn bản hiển thị được.",
  "Collection unavailable": "Chương trình hoặc danh sách nội dung hiện không khả dụng.",
  "Collection version unavailable": "Phiên bản chương trình hoặc danh sách nội dung hiện không khả dụng.",
  "Collection author scope denied": "Bạn không có quyền tác giả với chương trình hoặc danh sách nội dung này.",
  "Award enrollment access denied": "Bạn không có quyền truy cập bản đăng ký chương trình này.",
  "Current award group membership required": "Cần tư cách thành viên hiện tại của nhóm được phép học chương trình.",
  "Award outside current recipient audience": "Chương trình nằm ngoài đối tượng hiện được phép nhận.",
  "Open own award required": "Cần bản đăng ký chương trình còn mở của chính bạn.",
  "External criterion outside enrolled award": "Tiêu chí học tập bên ngoài nằm ngoài chương trình đã đăng ký.",
  "Award assessor scope denied": "Bạn không có quyền đánh giá chương trình này.",
  "Award audience outside role scope": "Đối tượng của chương trình nằm ngoài phạm vi vai trò của bạn.",
  "Collection not available for current learner": "Chương trình hoặc danh sách nội dung không khả dụng cho người học hiện tại.",
  "Award obligation is no longer active": "Nhiệm vụ học tập của chương trình không còn hoạt động.",
  "Invalid reference ID": "Mã tham chiếu không hợp lệ.",
  "Referenced content unavailable": "Nội dung được tham chiếu hiện không khả dụng.",
  "Publish only available published references": "Chỉ xuất bản với tham chiếu đến nội dung đã xuất bản và còn khả dụng.",
  "Referenced content version unavailable": "Phiên bản nội dung được tham chiếu hiện không khả dụng.",
  "Private nested award cannot be redistributed": "Không được chia sẻ lại chương trình con riêng tư.",
  "Invalid collection structure or size": "Cấu trúc hoặc kích thước chương trình không hợp lệ.",
  "Nested credit capacity exceeds depth bound": "Cách tính tín chỉ con vượt giới hạn độ sâu.",
  "Actual nested credits require only child awards": "Cách cộng tín chỉ thực tế chỉ chấp nhận tham chiếu chương trình con.",
  "Primary assessment requires moderated external learning": "Yêu cầu người đánh giá chính cần bật xét duyệt học tập bên ngoài.",
  "Custom units require original nonblank singular and plural labels; built-in units have fixed labels": "Đơn vị tùy chỉnh cần tên số ít và số nhiều không trống; đơn vị có sẵn dùng tên cố định.",
  "One-item awards use alternative criteria without required flags": "Chương trình hoàn thành một tiêu chí dùng các tiêu chí thay thế không có dấu bắt buộc.",
  "Award graph exceeds cycle/depth/complexity bounds": "Cấu trúc chương trình có vòng lặp hoặc vượt giới hạn độ sâu, độ phức tạp.",
  "Duplicate criterion IDs or unreachable target": "Mã tiêu chí bị trùng hoặc mục tiêu không thể đạt được.",
  "Award progress exceeds envelope bounds": "Dữ liệu tiến độ chương trình vượt giới hạn thông điệp.",
  "Invalid or duplicate criterion alternatives": "Lựa chọn thay thế của tiêu chí không hợp lệ hoặc bị trùng.",
  "Actual nested credit criteria accept only child awards": "Tiêu chí cộng tín chỉ thực tế chỉ chấp nhận chương trình con.",
  "Actual nested credits require identical unit labels; quantity conversion is unsupported": "Tín chỉ thực tế từ chương trình con cần cùng tên đơn vị; không hỗ trợ quy đổi lượng.",
  "Duplicate playlist items": "Mục trong danh sách nội dung bị trùng.",
  "Published collection exceeds size bounds": "Chương trình đã xuất bản vượt giới hạn kích thước.",
  "Stored award graph violates bounds": "Cấu trúc chương trình đã lưu vi phạm giới hạn.",
  "Playlists cannot be enrolled or assigned": "Không thể đăng ký hoặc giao học danh sách nội dung.",
  "Award unavailable to recipient": "Chương trình không khả dụng cho người nhận.",
  "Unknown learning read": "Không nhận diện được thao tác đọc dữ liệu học tập.",
  "Collection kind cannot change": "Không thể đổi loại chương trình hoặc danh sách nội dung.",
  "Only published collections can be unpublished": "Chỉ có thể rút xuất bản chương trình hoặc danh sách nội dung đã xuất bản.",
  "Assessor scope requires an award": "Phân quyền người đánh giá cần chọn một chương trình.",
  "Active same-tenant assessor required": "Cần người đánh giá đang hoạt động trong cùng tenant.",
  "Evidence file must belong to this learner and criterion": "Tệp bằng chứng phải thuộc đúng người học và tiêu chí này.",
  "Evidence is empty or already recorded for this criterion": "Bằng chứng để trống hoặc đã được ghi nhận cho tiêu chí này.",
  "Moderation decisions are final; reconcile original operation key": "Quyết định xét duyệt là cuối cùng; hãy đối soát bằng khóa thao tác ban đầu.",
  "Moderation reason required": "Cần nhập lý do xét duyệt.",
  "Unknown learning write": "Không nhận diện được thao tác thay đổi dữ liệu học tập.",
  "Award certificate access denied": "Bạn không có quyền truy cập chứng chỉ chương trình này.",
  "Current human-reviewed provider connection required": "Cần kết nối nhà cung cấp đã được người dùng xem xét và hiện còn hiệu lực.",
  "Current administrator required": "Cần quyền quản trị viên hiện tại.",
  "Trusted configured provider required": "Cần nhà cung cấp đã được cấu hình đáng tin cậy.",
  "Own configured provider client required": "Cần client nhà cung cấp đã cấu hình thuộc quyền của bạn.",
  "Current own scoped client and license required": "Cần client đúng phạm vi và giấy phép hiện có hiệu lực thuộc quyền của bạn.",
  "Explicit provider rights confirmation and reason required": "Cần xác nhận rõ quyền nhà cung cấp và nhập lý do.",
  "Invalid provider identity": "Danh tính nhà cung cấp không hợp lệ.",
  "Current reviewed provider license and client binding required": "Cần giấy phép nhà cung cấp và liên kết client đã xem xét còn hiệu lực.",
  "Current account required": "Cần tài khoản hiện tại còn hiệu lực.",
  "Current reviewed provider license required": "Cần giấy phép nhà cung cấp đã xem xét còn hiệu lực.",
  "Reviewed provider connection revoked": "Kết nối nhà cung cấp đã xem xét đã bị thu hồi.",
  "Invalid bounded provider event": "Sự kiện nhà cung cấp không hợp lệ hoặc vượt giới hạn.",
  "Metadata only; bodies, answers, URLs and unsupported fields are prohibited": "Chỉ chấp nhận metadata; không nhận nội dung đầy đủ, đáp án, URL hoặc trường không hỗ trợ.",
  "Invalid retirement": "Thông tin ngừng cung cấp nội dung không hợp lệ.",
  "Invalid current grant": "Thông tin cấp quyền hiện tại không hợp lệ.",
  "Invalid revocation": "Thông tin thu hồi quyền không hợp lệ.",
  "Unsupported provider event": "Sự kiện nhà cung cấp không được hỗ trợ.",
  "Provider event identity changed": "Định danh sự kiện nhà cung cấp đã thay đổi.",
  "Source timestamp cannot move backward": "Thời điểm nguồn không được lùi về trước.",
  "Provider sequence requires reconciliation": "Chuỗi sự kiện nhà cung cấp cần được đối soát.",
  "Source version must advance": "Phiên bản nguồn phải tăng.",
  "Provider catalog quota reached": "Đã đạt giới hạn danh mục nhà cung cấp.",
  "Provider metadata item required": "Cần mục metadata của nhà cung cấp.",
  "Current same-tenant learner required": "Cần người học hiện đang hoạt động trong cùng tenant.",
  "Provider entitlement quota reached": "Đã đạt giới hạn quyền sử dụng nhà cung cấp.",
  "Grant cannot outlive active source license": "Thời hạn cấp quyền không được vượt giấy phép nguồn đang hiệu lực.",
  "Invalid provider event page": "Trang sự kiện nhà cung cấp không hợp lệ.",
  "Provider source changed; review again": "Nguồn nhà cung cấp đã thay đổi; hãy xem xét lại.",
  "Explicit human confirmation required": "Cần người dùng xác nhận trực tiếp.",
  "Own provider launch quota reached": "Đã đạt giới hạn lượt mở nội dung nhà cung cấp của bạn.",
  "Own current unexpired launch required": "Cần lượt mở nội dung hiện tại của chính bạn còn hiệu lực.",
  "Provider metadata model rights not reviewed": "Quyền gửi metadata nhà cung cấp cho mô hình chưa được xem xét.",
  "Current own provider entitlement required": "Cần quyền sử dụng nhà cung cấp hiện tại của chính bạn.",
  "Question bank authority changed": "Quyền truy cập ngân hàng câu hỏi đã thay đổi.",
  "Question bank author required": "Cần quyền tác giả ngân hàng câu hỏi.",
  "Group bank cannot be redistributed outside its declared audience": "Không được chia sẻ lại ngân hàng câu hỏi nhóm ngoài đối tượng đã khai báo.",
  "Scoped question bank unavailable": "Ngân hàng câu hỏi trong phạm vi quyền hiện không khả dụng.",
  "Question bank outside author audience": "Ngân hàng câu hỏi nằm ngoài đối tượng được phép dùng của tác giả.",
  "Question bank version unavailable": "Phiên bản ngân hàng câu hỏi hiện không khả dụng.",
  "Private bank version unavailable": "Phiên bản ngân hàng câu hỏi riêng tư hiện không khả dụng.",
  "Question bank original owner required": "Cần người sở hữu ban đầu của ngân hàng câu hỏi.",
  "Question bank is retired for new draft use": "Ngân hàng câu hỏi đã ngừng cung cấp cho bản nháp mới.",
  "Question bank course draft unavailable": "Bản nháp khóa học để dùng ngân hàng câu hỏi hiện không khả dụng.",
  "Private bank cannot be redistributed to a wider course audience": "Không được chia sẻ ngân hàng câu hỏi riêng tư cho đối tượng khóa học rộng hơn.",
  "Distinct bank question IDs required": "Cần các mã câu hỏi trong ngân hàng không trùng nhau.",
  "Question ID missing from selected bank version": "Mã câu hỏi không có trong phiên bản ngân hàng đã chọn.",
  "Create the course draft before applying a question bank": "Hãy tạo bản nháp khóa học trước khi áp dụng ngân hàng câu hỏi.",
  "Private bank requires the same owned author course audience": "Ngân hàng câu hỏi riêng tư cần khóa học riêng của cùng tác giả sở hữu.",
  "Pinned bank questions differ; explicitly detach the bank before manual edits": "Câu hỏi khác phiên bản ngân hàng đã gắn; hãy chủ động tách ngân hàng trước khi sửa thủ công.",
  "Unknown question bank write": "Không nhận diện được thao tác thay đổi ngân hàng câu hỏi.",
  "Question bank source course unavailable": "Khóa học nguồn của ngân hàng câu hỏi hiện không khả dụng.",
  "Group source questions require an equal or narrower bank audience": "Câu hỏi nguồn theo nhóm cần ngân hàng có đối tượng bằng hoặc hẹp hơn.",
  "Private source questions require a private bank": "Câu hỏi nguồn riêng tư cần ngân hàng câu hỏi riêng tư.",
  "Source draft questions changed; review the source again": "Câu hỏi trong bản nháp nguồn đã thay đổi; hãy xem xét nguồn lại.",
  "Distinct bounded bank questions required": "Cần các câu hỏi ngân hàng khác nhau và nằm trong giới hạn.",
  "Bank version history limit reached": "Đã đạt giới hạn lịch sử phiên bản ngân hàng câu hỏi.",
  "Question bank quota reached": "Đã đạt giới hạn số ngân hàng câu hỏi.",
  "Submitted question checks are immutable": "Không thể sửa kiểm tra câu hỏi của lần làm bài đã nộp.",
  "Question checks are not configured": "Chưa cấu hình kiểm tra từng câu hỏi.",
  "Only configured objective questions may be checked": "Chỉ kiểm tra được câu hỏi khách quan đã cấu hình.",
  "Complete earlier questions first": "Hãy hoàn thành các câu hỏi trước.",
  "Save the response before checking": "Hãy lưu câu trả lời trước khi kiểm tra.",
  "Saved response changed; refresh before checking": "Câu trả lời đã lưu đã thay đổi; hãy làm mới trước khi kiểm tra.",
  "Earlier correct responses are retained unchanged in this retry": "Câu trả lời đúng trước đó được giữ nguyên trong lần làm lại này.",
  "Incorrect-only retry requires objective questions": "Làm lại riêng câu sai cần các câu hỏi khách quan.",
  "Invalid UTC report date": "Ngày UTC của báo cáo không hợp lệ.",
  "Invalid report specification/duplicate columns": "Cấu hình báo cáo không hợp lệ hoặc có cột bị trùng.",
  "Report date range reversed": "Ngày bắt đầu báo cáo không được sau ngày kết thúc.",
  "Learner filter outside current audience scope": "Bộ lọc người học nằm ngoài đối tượng hiện được phép xem.",
  "Saved report owner scope denied": "Bạn không có quyền sở hữu báo cáo đã lưu này.",
  "Own insight authority changed": "Quyền xem thông tin học tập của bạn đã thay đổi.",
  "Report data/scope changed; restart the preview/export": "Dữ liệu hoặc phạm vi báo cáo đã thay đổi; hãy bắt đầu xem trước hoặc xuất lại.",
  "Unsupported report status": "Trạng thái báo cáo không được hỗ trợ.",
  "Unknown report read": "Không nhận diện được thao tác đọc báo cáo.",
  "Invalid saved report ID": "Mã báo cáo đã lưu không hợp lệ.",
  "Unknown report write": "Không nhận diện được thao tác thay đổi báo cáo.",
  "Own enrollment required": "Chỉ được dùng bản đăng ký của chính bạn.",
  "Only completed learning may be retaken": "Chỉ có thể học lại nội dung đã hoàn thành.",
  "Course version unavailable": "Phiên bản khóa học hiện không khả dụng.",
  "Latest quiz upgrade is unavailable or changed; review again": "Không thể nâng cấp bài kiểm tra mới nhất hoặc phiên bản đã thay đổi; hãy xem xét lại.",
  "Course is not accepting new learning": "Khóa học hiện không nhận bản đăng ký mới.",
  "Chosen course version changed; review options again": "Phiên bản khóa học đã chọn đã thay đổi; hãy xem lại lựa chọn.",
  "A retake already exists; continue that record": "Đã có bản ghi học lại; hãy tiếp tục bản ghi đó.",
  "Own unfinished self-directed learning required": "Cần bản học tự đăng ký chưa hoàn thành của chính bạn.",
  "Active unfinished learning required": "Cần bản ghi học tập đang hoạt động và chưa hoàn thành.",
  "A successor already exists": "Đã có bản ghi học tiếp theo.",
  "Unsupported/invalid SCORM package: ": "Gói SCORM không được hỗ trợ hoặc không hợp lệ: ",
  "Invalid package page": "Trang của gói nội dung không hợp lệ.",
  "Bound launch ticket required": "Cần vé mở nội dung đã gắn đúng phiên.",
  "Reviewed binary ZIP upload required": "Cần tệp ZIP đã tải lên và được xem xét.",
  "Authorized package unavailable": "Gói nội dung trong phạm vi được phép hiện không khả dụng.",
  "Explicit reviewed package action required": "Cần thao tác với gói nội dung đã được xem xét rõ ràng.",
  "Package operation changed": "Thao tác với gói nội dung đã thay đổi.",
  "Package context changed; review again": "Ngữ cảnh gói nội dung đã thay đổi; hãy xem xét lại.",
  "Confirm self-authored ZIP and supported language": "Hãy xác nhận tệp ZIP tự soạn và ngôn ngữ được hỗ trợ.",
  "Shared tenant upload quota reached": "Đã đạt giới hạn tải lên dùng chung của tenant.",
  "Explicit package code/provenance review required": "Cần xem xét rõ mã thực thi và nguồn gốc gói nội dung.",
  "Exact imported package hash required": "Cần đúng mã băm của gói đã nhập.",
  "Publish only an explicitly reviewed quarantined immutable package": "Chỉ xuất bản gói bất biến đang cách ly đã được xem xét rõ ràng.",
  "Retire only a published package": "Chỉ ngừng cung cấp gói đã xuất bản.",
  "Own package record required": "Chỉ được dùng bản ghi gói nội dung của chính bạn.",
  "Human package tracking consent required": "Cần người dùng đồng ý trực tiếp với việc theo dõi gói nội dung.",
  "Package is not accepting new launches": "Gói nội dung hiện không nhận lượt mở mới.",
  "Quarantined package cannot execute": "Gói nội dung đang cách ly không được thực thi.",
  "Live own package launch required": "Cần lượt mở gói nội dung đang hiệu lực của chính bạn.",
  "Bound package launch ticket required": "Cần vé mở gói nội dung đã gắn đúng phiên.",
  "Bounded package runtime state required": "Trạng thái thực thi gói nội dung phải nằm trong giới hạn.",
  "Package message binding changed": "Liên kết thông điệp của gói nội dung đã thay đổi.",
  "Package state changed; reopen and resume": "Trạng thái gói nội dung đã thay đổi; hãy mở lại và tiếp tục.",
  "Reported session time cannot go backwards": "Thời gian phiên được báo cáo không được giảm.",
  "Invalid assistant workspace": "Workspace dành cho trợ lý không hợp lệ.",
  "Workspace access denied": "Bạn không có quyền truy cập workspace này.",
  "Content item unavailable": "Mục nội dung hiện không khả dụng.",
  "Published content version unavailable": "Phiên bản nội dung đã xuất bản hiện không khả dụng.",
  "Enrollment access denied": "Bạn không có quyền truy cập bản đăng ký này.",
  "Attempt access denied": "Bạn không có quyền truy cập lần làm bài này.",
  "Assignment audience outside role scope": "Đối tượng giao học nằm ngoài phạm vi vai trò của bạn.",
  "Assignment obligation is no longer active": "Nhiệm vụ học tập được giao không còn hoạt động.",
  "Invalid call envelope": "Cấu trúc thông điệp gọi không hợp lệ.",
  "Tool unavailable for current role and channel": "Thao tác không khả dụng cho vai trò và kênh hiện tại.",
  "Arguments fail tool schema": "Tham số không đúng cấu trúc của thao tác.",
  "Invalid revision or idempotency fields": "Phiên bản hoặc trường chống lặp thao tác không hợp lệ.",
  "Mutation targets the wrong aggregate": "Thao tác thay đổi nhắm sai vùng dữ liệu.",
  "Result exceeds envelope limit": "Kết quả vượt giới hạn thông điệp.",
  "Account authority changed before transaction": "Quyền tài khoản đã thay đổi trước giao dịch.",
  "Operation key reused with another payload": "Khóa thao tác đã được dùng cho nội dung khác.",
  "Workspace changed; refresh before proposing another mutation": "Workspace đã thay đổi; hãy làm mới trước khi đề xuất thay đổi tiếp.",
  "Content item is not available for discovery": "Mục nội dung hiện không được cung cấp trong tìm kiếm.",
  "Course is not available for discovery": "Khóa học hiện không được cung cấp trong tìm kiếm.",
  "Lesson unavailable": "Bài học hiện không khả dụng.",
  "Captions require uploaded audio/video": "Phụ đề cần tệp âm thanh hoặc video đã tải lên.",
  "Use distinct caption languages": "Chọn các ngôn ngữ phụ đề không trùng nhau.",
  "Caption label required": "Cần nhập tên phụ đề.",
  "Choose one immutable asset or HTTPS URL": "Chọn một tệp bất biến hoặc một URL HTTPS.",
  "Uploaded asset required": "Cần tệp nội dung đã tải lên.",
  "External media URL required": "Cần URL nội dung đa phương tiện bên ngoài.",
  "Invalid media URL": "URL nội dung đa phương tiện không hợp lệ.",
  "Media must use HTTPS without credentials": "Nội dung đa phương tiện phải dùng HTTPS và không chứa thông tin đăng nhập.",
  "Media transcript required": "Cần bản chép lời cho nội dung đa phương tiện.",
  "Invalid standalone content structure": "Cấu trúc nội dung độc lập không hợp lệ.",
  "Discovery metadata must have distinct nonblank entries": "Metadata tìm kiếm cần các mục không trùng và không để trống.",
  "Invalid course structure": "Cấu trúc khóa học không hợp lệ.",
  "Reusable item must be published and available": "Nội dung dùng lại phải đã xuất bản và còn khả dụng.",
  "Duplicate lesson/question IDs": "Mã bài học hoặc câu hỏi bị trùng.",
  "Prerequisites must reference distinct earlier lessons": "Điều kiện tiên quyết phải tham chiếu các bài học trước và không trùng.",
  "Duplicate module IDs": "Mã học phần bị trùng.",
  "Modules must partition every lesson exactly once in course sequence": "Mỗi bài học phải thuộc đúng một học phần theo thứ tự khóa học.",
  "Module prerequisites must reference distinct earlier modules": "Điều kiện tiên quyết của học phần phải tham chiếu các học phần trước và không trùng.",
  "Incorrect-only retries require objective questions without correct-before-continuing": "Làm lại riêng câu sai cần câu hỏi khách quan và không bật yêu cầu trả lời đúng để tiếp tục.",
  "Correct-before-continuing requires objective questions; essays need human final assessment": "Yêu cầu trả lời đúng để tiếp tục chỉ dùng cho câu khách quan; tự luận cần người đánh giá kết quả cuối cùng.",
  "Assessment content exceeds 16 KiB budget": "Nội dung đánh giá vượt giới hạn 16 KiB.",
  "Resolved course exceeds schema or byte bounds": "Khóa học sau khi gắn nội dung vượt giới hạn cấu trúc hoặc dung lượng.",
  "Course is not accepting enrollments": "Khóa học hiện không nhận đăng ký.",
  "Content item ID already exists": "Mã mục nội dung đã tồn tại.",
  "Only published content can be unpublished": "Chỉ rút xuất bản được nội dung đã xuất bản.",
  "Only available courses can be saved": "Chỉ lưu được khóa học còn khả dụng.",
  "Submission or attendance requires an authorized human review": "Bài nộp hoặc tham dự cần người có quyền đánh giá trực tiếp.",
  "Complete prerequisites first": "Hãy hoàn thành các điều kiện tiên quyết trước.",
  "Enrollment already completed": "Bản đăng ký đã hoàn thành.",
  "Complete all lessons before assessment": "Hãy hoàn thành tất cả bài học trước khi làm bài đánh giá.",
  "Wait for human assessment review before retrying": "Hãy chờ người đánh giá xem xét trước khi làm lại.",
  "Operational quota of 2500 attempts per enrollment reached": "Đã đạt giới hạn 2500 lần làm bài cho bản đăng ký này.",
  "Assessment attempt limit reached": "Đã đạt giới hạn số lượt làm bài đánh giá.",
  "Submitted answers are immutable": "Không thể sửa câu trả lời đã nộp.",
  "Invalid question": "Câu hỏi không hợp lệ.",
  "Combined responses exceed 32 KiB budget": "Tổng các câu trả lời vượt giới hạn 32 KiB.",
  "Attempt already submitted; reconcile the original key": "Lần làm bài đã được nộp; hãy đối soát bằng khóa thao tác ban đầu.",
  "Check every current response as correct before submitting": "Hãy kiểm tra tất cả câu trả lời hiện tại đều đúng trước khi nộp.",
  "Answer every question before submitting": "Hãy trả lời tất cả câu hỏi trước khi nộp.",
  "Course ID already exists": "Mã khóa học đã tồn tại.",
  "Due date must be an exact UTC ISO timestamp": "Hạn hoàn thành cần đúng định dạng thời điểm UTC ISO.",
  "Certificate access denied": "Bạn không có quyền truy cập chứng chỉ này.",
  "Own standalone enrollment required": "Chỉ được dùng bản đăng ký nội dung độc lập của chính bạn.",
  "Published standalone item required": "Cần mục nội dung độc lập đã xuất bản.",
  "Standalone version unavailable": "Phiên bản nội dung độc lập hiện không khả dụng.",
  "Invalid study timer target": "Nội dung được chọn để tính thời gian học không hợp lệ.",
  "Study timer account authority changed": "Quyền tài khoản đối với bộ tính thời gian học đã thay đổi.",
  "Own active learning record required": "Cần bản ghi học tập đang hoạt động của chính bạn.",
  "Invalid timer action": "Thao tác với bộ tính thời gian không hợp lệ.",
  "Study timer lease changed; explicitly start again": "Quyền phiên tính thời gian đã thay đổi; hãy chủ động bắt đầu lại.",
  "Translation review requires content administrator": "Xem xét bản dịch cần quyền quản trị nội dung.",
  "Explicit content kind and ID required": "Cần chọn rõ loại và mã nội dung.",
  "Published authorized content required": "Cần nội dung đã xuất bản mà bạn có quyền sử dụng.",
  "Supported preferredLanguage values: en, vi; other provider languages remain unsupported": "Ngôn ngữ ưu tiên được hỗ trợ: en và vi; chưa hỗ trợ các ngôn ngữ khác của nhà cung cấp.",
  "Invalid reviewed translation": "Bản dịch đã xem xét không hợp lệ.",
  "Unsupported translation field": "Trường bản dịch không được hỗ trợ.",
  "Link distinct self-authored sources with different supported languages": "Liên kết các nguồn tự soạn khác nhau có ngôn ngữ khác nhau được hỗ trợ.",
  "Explicit derivative provenance and human quality review required": "Cần nguồn gốc bản phái sinh rõ ràng và người dùng xem xét chất lượng.",
  "Translation chains are not allowed; select the canonical original": "Không chấp nhận chuỗi bản dịch; hãy chọn bản gốc chuẩn.",
  "A canonical original cannot become a derivative": "Bản gốc chuẩn không thể trở thành bản phái sinh.",
  "Authorized translation required": "Cần bản dịch được phép sử dụng.",
  "Authorized translation source required": "Cần nguồn bản dịch được phép sử dụng.",
  "Translation request changed": "Yêu cầu bản dịch đã thay đổi.",
  "Translation review changed; refresh": "Thông tin xem xét bản dịch đã thay đổi; hãy làm mới.",
  "Published source version changed; review again": "Phiên bản nguồn đã xuất bản đã thay đổi; hãy xem xét lại.",
  "Translation identity quota reached": "Đã đạt giới hạn số định danh bản dịch.",
  "Source/language already has an active reviewed translation": "Nguồn và ngôn ngữ này đã có bản dịch đã xem xét đang hoạt động.",
  "Translation review history quota reached": "Đã đạt giới hạn lịch sử xem xét bản dịch.",
  "Unsupported/missing xAPI profile attribute": "Thuộc tính hồ sơ xAPI không được hỗ trợ hoặc bị thiếu.",
  "Explicit UUID and ≤8 KiB statement required": "Cần UUID cụ thể và statement không quá 8 KiB.",
  "Only account Agent actors supported": "Chỉ hỗ trợ actor Agent xác định bằng tài khoản.",
  "Reviewed managed opaque actor required": "Cần actor được quản lý có định danh không tiết lộ danh tính và đã xem xét.",
  "Active same-client managed learner required": "Cần người học đang hoạt động được quản lý bởi cùng client.",
  "Unsupported xAPI verb": "Verb xAPI không được hỗ trợ.",
  "Only course Activity objects supported": "Chỉ hỗ trợ đối tượng Activity của khóa học.",
  "Authorized Pear course activity required": "Cần hoạt động khóa học Pear được phép sử dụng.",
  "Use exact versioned course Activity IRI": "Dùng đúng Activity IRI có phiên bản của khóa học.",
  "Authorized published or enrolled pinned course required": "Cần khóa học đã xuất bản được phép dùng hoặc phiên bản đã gắn với bản đăng ký.",
  "Explicit registration UUID required": "Cần UUID bản đăng ký cụ thể.",
  "Use valid UTC profile timestamp, at most five minutes ahead": "Dùng thời điểm UTC hợp lệ, không quá năm phút trong tương lai.",
  "Invalid UTC calendar timestamp": "Thời điểm lịch UTC không hợp lệ.",
  "Boolean result field required": "Trường kết quả cần giá trị true hoặc false.",
  "Nonempty score required": "Điểm không được để trống.",
  "Finite score required": "Điểm phải là số hữu hạn.",
  "Score bounds invalid": "Giới hạn điểm không hợp lệ.",
  "Only bounded PT hours/minutes/seconds durations supported": "Chỉ hỗ trợ thời lượng PT giờ, phút, giây trong giới hạn.",
  "Verb and reported result must agree": "Verb và kết quả được báo cáo phải khớp nhau.",
  "Supply 1–5 bounded statements": "Cung cấp từ 1 đến 5 statement trong giới hạn.",
  "Statement ID unavailable": "Mã statement hiện không khả dụng.",
  "Statement ID reused with changed payload": "Mã statement đã được dùng cho nội dung khác.",
  "Statement history quota reached": "Đã đạt giới hạn lịch sử statement.",
  "Unsupported xAPI profile query": "Truy vấn hồ sơ xAPI không được hỗ trợ.",
  "Use a single statementId UUID query": "Dùng truy vấn với một UUID statementId.",
  "Authorized statement unavailable": "Statement trong phạm vi được phép hiện không khả dụng.",
  "Invalid profile cursor/registration": "Con trỏ hoặc bản đăng ký của hồ sơ không hợp lệ.",
  "Active learner required": "Cần người học đang hoạt động.",
  "Same-origin request required": "Yêu cầu phải đến từ cùng origin.",
  "Sign in required": "Cần đăng nhập.",
  "CSRF check failed": "Kiểm tra CSRF không thành công.",
  "Session changed; refresh and consent again": "Phiên đã thay đổi; hãy làm mới và xác nhận quyền lại.",
  "Development login disabled; production identity adapter is not configured": "Đăng nhập thử nghiệm đã tắt; chưa cấu hình bộ kết nối danh tính production.",
  "Login rate limit": "Đã đạt giới hạn tốc độ đăng nhập.",
  "Invalid synthetic account credentials": "Thông tin đăng nhập tài khoản thử nghiệm không hợp lệ.",
  "Identity login rate limit": "Đã đạt giới hạn tốc độ đăng nhập danh tính tổ chức.",
  "Organization sign-in unavailable": "Đăng nhập tổ chức hiện không khả dụng.",
  "Organization sign-in failed; restart sign-in": "Đăng nhập tổ chức không thành công; hãy bắt đầu lại.",
  "Invalid identity page": "Trang danh tính không hợp lệ.",
  "Audience access denied": "Bạn không có quyền xem đối tượng này.",
  "Production upload scanning/storage gate is not configured": "Chưa cấu hình kiểm tra và lưu trữ tệp tải lên cho production.",
  "Binary upload required": "Cần tệp tải lên ở dạng nhị phân.",
  "Interactive HTML required": "Cần nội dung HTML tương tác.",
  "Interactive launch denied": "Không được phép mở nội dung tương tác.",
  "Endpoint not found": "Không tìm thấy endpoint.",
  "Request failed": "Yêu cầu không thành công.",
  "Certificate PDF unavailable": "PDF chứng chỉ hiện không khả dụng.",
  "Server PDF font is not configured; original text and browser print remain available": "Chưa cấu hình phông chữ PDF trên máy chủ; vẫn có thể dùng bản văn bản gốc và chức năng in của trình duyệt.",
  "Award references conflicting course versions; author review is required": "Chương trình yêu cầu các phiên bản khóa học khác nhau; tác giả cần xem xét lại.",
  "Existing course version differs from the award; reviewed learning changes are required": "Phiên bản khóa học hiện có khác với yêu cầu của chương trình; cần xem xét và xác nhận thay đổi học tập.",
  "Current award course obligation is not active": "Nhiệm vụ khóa học hiện tại của chương trình không đang hoạt động.",
  "An active unfinished award is required for a binding change": "Cần chương trình đang hoạt động và chưa hoàn thành để thay đổi khóa học gắn với tiêu chí.",
  "Exact course criterion outside enrolled award": "Khóa học không thuộc đúng tiêu chí của chương trình đã đăng ký.",
  "Bound course ledger scope mismatch": "Bản ghi khóa học không khớp người học, tổ chức hoặc chu kỳ của chương trình.",
  "Resolve pending assessment and cancel bookings before changing award learning": "Hoàn tất đánh giá đang chờ và hủy đặt chỗ trước khi thay đổi khóa học trong chương trình.",
  "Award course binding changed; review again": "Khóa học gắn với tiêu chí đã thay đổi; hãy xem xét lại.",
  "Current award course review required": "Cần đề xuất khóa học trong chương trình còn hiệu lực.",
  "Addressed exact award course review required": "Cần đúng người học xác nhận đúng đề xuất khóa học trong chương trình.",
  "Assigned award learning requires separate coordinator review": "Khóa học thuộc chương trình được giao cần người quản lý xem xét riêng.",
  "A current award course offer already exists": "Đã có đề xuất khóa học trong chương trình còn hiệu lực.",
  "Only the current bound course may change official learning": "Chỉ bản ghi khóa học hiện gắn với tiêu chí mới được thay đổi kết quả học chính thức.",
  "Use the exact award course binding review": "Hãy dùng luồng xem xét đúng khóa học gắn với tiêu chí của chương trình.",
  "Active award cycle delivery required": "Cần bản giao chương trình theo chu kỳ đang hoạt động.",
  "Active award cycle membership required": "Cần tư cách thành viên hiện tại của chu kỳ giao chương trình.",
  "Current award audience required": "Cần quyền truy cập hiện tại vào chương trình.",
  "Select an exact course criterion path": "Hãy chọn đúng đường dẫn tiêu chí khóa học.",
  "Award references conflicting course versions; select an exact criterion path": "Chương trình tham chiếu nhiều phiên bản khóa học; hãy chọn đúng đường dẫn tiêu chí.",
  "Operation failed": "Thao tác không thành công.",
  "Failed to fetch": "Không thể kết nối để gửi yêu cầu.",
  "NetworkError when attempting to fetch resource.": "Không thể kết nối để tải dữ liệu.",
  "Request outcome unknown; refresh current data before confirming another action.": "Chưa biết thao tác đã được ghi nhận chưa. Hãy làm mới dữ liệu trước khi xác nhận thao tác tiếp."
});
export function diagnosticText(message:string,locale:UILocale=getUILocale()){return locale==="vi"&&Object.hasOwn(vietnameseDiagnostics,message)?vietnameseDiagnostics[message]!:message;}
export function humanError(code:unknown,message:unknown,locale:UILocale=getUILocale()){return String(code)+": "+diagnosticText(String(message),locale);}
