import React,{useEffect,useState} from "react";
import {translateUI as t} from "./i18n.ts";
export function ProviderConnections(p:{busy:boolean;tick:number;op:(name:string,args?:Record<string,unknown>)=>Promise<any>;mutate:(name:string,args:Record<string,unknown>)=>Promise<any>;run:(fn:()=>Promise<void>)=>Promise<boolean>;isCurrent:()=>boolean}){
 const [data,setData]=useState<any>(null),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false),[refresh,setRefresh]=useState(0),[error,setError]=useState("");
 useEffect(()=>{let live=true;void p.op("human_get_provider_connections").then(value=>{if(live&&p.isCurrent()){setData(value);setError("");}}).catch(e=>{if(live&&p.isCurrent())setError(e.message);});return()=>{live=false;};},[refresh,p.tick]);
 async function review(providerId:string,enabled:boolean){await p.run(async()=>{await p.mutate("human_review_provider_connection",{providerId,enabled,rightsConfirmed:true,reason});if(p.isCurrent()){setConfirmed(false);setRefresh(n=>n+1);}});}
 return <section className="panel" aria-label={t("Reviewed provider connections")}><h2>{t("Reviewed provider connections")}</h2><p>{t("Confirm the configured provider license, client, metadata processing permission and external destination. Your review cannot expand the server allowlist or change a provider contract.")}</p>
 {error&&<p role="alert">{error}</p>}{data?.configurationRequired&&<p>{t("No reviewed provider configuration is available. Ask your operator to configure the contracted provider and scoped client.")}</p>}
 <label>{t("Provider review reason")}<input required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t("I confirm reviewing provider content and metadata rights")}</label>
 {data?.items.map((row:any)=><article key={row.providerId}><h3>{row.providerId}</h3><dl><dt>{t("Provider destination")}</dt><dd style={{overflowWrap:"anywhere"}}>{row.launchOrigin}</dd><dt>{t("Provider license expiration")}</dt><dd>{row.licenseUntil}</dd><dt>{t("Configured provider client")}</dt><dd>{row.clientName??t("Own active scoped client unavailable")}</dd><dt>{t("Model metadata permission")}</dt><dd>{row.metadataForModels?t("Allowed by configured contract"):t("Human metadata only")}</dd><dt>{t("Connection state")}</dt><dd>{row.enabled?t("Approved"):t("Disabled or awaiting review")}</dd></dl>
 <button disabled={p.busy||!confirmed||!reason.trim()||!row.canEnable||row.enabled} onClick={()=>{void review(row.providerId,true);}}>{t("Approve configured provider connection")}</button><button disabled={p.busy||!confirmed||!reason.trim()||!row.clientId} onClick={()=>{void review(row.providerId,false);}}>{t("Disable provider connection")}</button></article>)}
 </section>;
}
