import React,{useEffect,useState} from "react";
import {translateUI as t} from "./i18n.ts";
export function ProviderContent(p:{busy:boolean;tick:number;op:(name:string,args?:Record<string,unknown>)=>Promise<any>;mutate:(name:string,args:Record<string,unknown>)=>Promise<any>;run:(fn:()=>Promise<void>)=>Promise<boolean>;isCurrent:()=>boolean}){
 const [query,setQuery]=useState(""),[offset,setOffset]=useState(0),[historyOffset,setHistoryOffset]=useState(0),[refresh,setRefresh]=useState(0),[page,setPage]=useState<any>(null),[history,setHistory]=useState<any>(null),[selected,setSelected]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[launch,setLaunch]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{let live=true;void Promise.all([p.op("learning_search_provider_content",{query,offset}),p.op("learning_get_my_provider_launches",{offset:historyOffset})]).then(([page,history])=>{if(live&&p.isCurrent()){setPage(page);setHistory(history);setError("");}}).catch(e=>{if(live&&p.isCurrent())setError(e.message);});return()=>{live=false;};},[refresh,offset,historyOffset,p.tick]);
 return <section className="panel" aria-label={t("Provider content")}><h2>{t("Provider content")}</h2>
 <p>{t("Access depends on your current provider entitlement. Opening external content records a launch only; it does not create course progress, a grade or a certificate.")}</p>
 {error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();setOffset(0);setSelected(null);setLaunch(null);setRefresh(n=>n+1);}}><label>{t("Search provider metadata")}<input maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={p.busy}>{t("Search provider content")}</button></form>
 {page&&page.items.length===0&&<p>{t("No currently entitled provider content is available.")}</p>}
 {page?.items.map((item:any)=><article key={item.providerId+":"+item.sourceId}><h3>{item.title}</h3><p>{item.summary}</p><p>{item.providerId+" · "+item.language+" · "+item.intendedMinutes+" min · v"+item.version}</p><button disabled={p.busy} onClick={()=>{void p.run(async()=>{const value=await p.op("learning_get_provider_item",{providerId:item.providerId,sourceId:item.sourceId});if(p.isCurrent()){setSelected(value);setConfirmed(false);setLaunch(null);}});}}>{t("Review provider item")}</button></article>)}
 {page&&<div className="actions"><button disabled={p.busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-10))}>{t("Previous provider page")}</button><button disabled={p.busy||page.nextOffset===null} onClick={()=>setOffset(page.nextOffset)}>{t("Next provider page")}</button></div>}
 {selected&&<section aria-label={t("Provider launch review")}><h3>{selected.title}</h3><p>{selected.summary}</p><p>{t("Your provider handles its own sign-in and content rights.")}</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t("I confirm creating my provider launch record")}</label><button disabled={p.busy||!confirmed} onClick={()=>{void p.run(async()=>{const result=await p.mutate("human_open_provider_content",{providerId:selected.providerId,sourceId:selected.sourceId,version:selected.version,confirmed:true});if(p.isCurrent()){setLaunch(result);setConfirmed(false);void p.op("learning_get_my_provider_launches",{offset:historyOffset}).then(value=>{if(p.isCurrent())setHistory(value);}).catch(()=>{});}});}}>{t("Create provider launch")}</button>
 {launch&&<div role="status"><p>{t("This link expires after 60 seconds. Current rights are checked again when you open it.")}</p><a href={launch.href} target="_blank" rel="noopener noreferrer">{t("Open provider content in a new tab")}</a></div>}</section>}
 <h3>{t("My provider launch history")}</h3><p>{t("Launch records are separate from official learning outcomes.")}</p>
 <ul>{history?.items.map((record:any)=><li key={record.id}>{record.title??t("Provider metadata unavailable")}{" · "+record.providerId+" · v"+record.sourceVersion+" · "+record.createdAt}</li>)}</ul>
 {history&&<div className="actions"><button disabled={p.busy||historyOffset===0} onClick={()=>setHistoryOffset(Math.max(0,historyOffset-20))}>{t("Previous launch history")}</button><button disabled={p.busy||history.nextOffset===null} onClick={()=>setHistoryOffset(history.nextOffset)}>{t("Next launch history")}</button></div>}
 </section>;
}
