import React,{useEffect,useState} from "react";
import {translateUI as t} from "./i18n.ts";
type Props={principalId:string;admin:boolean;busy:boolean;tick:number;op:(name:string,args:Record<string,unknown>)=>Promise<any>;mutate:(name:string,args:Record<string,unknown>)=>Promise<any>;run:(f:()=>Promise<void>)=>Promise<boolean>;isCurrent:()=>boolean};
export function QuestionBanks(p:Props){
 const [rows,setRows]=useState<any[]>([]),[offset,setOffset]=useState(0),[next,setNext]=useState<number|null>(null),[bankId,setBankId]=useState(""),[title,setTitle]=useState(""),[access,setAccess]=useState("author"),[groupIds,setGroupIds]=useState(""),[ai,setAI]=useState(true),[sourceCourse,setSourceCourse]=useState(""),[selected,setSelected]=useState<any>(null),[questions,setQuestions]=useState<string[]>([]),[target,setTarget]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;void (async()=>{try{const r=await p.op("learning_get_question_banks",{offset,limit:10});if(live&&p.isCurrent()){setRows(r.items);setNext(r.nextOffset);}}catch(error){if(live&&p.isCurrent())setMessage(error instanceof Error?error.message:String(error));}})();return()=>{live=false;};},[p.tick,offset]);
 return <section className="panel" aria-label={t("Reusable question banks")}><h2>{t("Reusable question banks")}</h2><p>{t("Publish bank questions from a saved original course draft. Applying a version changes only the target draft; existing learners keep their published quiz.")}</p>
 <form aria-label={t("Publish question bank")} onSubmit={e=>{e.preventDefault();void p.run(async()=>{const course=await p.op("learning_get_course_draft",{courseId:sourceCourse});if(course.draft.access==="author"&&access!=="author")throw new Error(t("Private source questions require a private bank"));const r=await p.mutate("learning_save_question_bank",{bankId,sourceCourseId:sourceCourse,bank:{title,access,...(access==="groups"?{groupIds:groupIds.split(",").map(id=>id.trim()).filter(Boolean)}:{}),aiProcessingAllowed:ai&&course.draft.aiProcessingAllowed,questions:course.draft.quiz.questions}});if(p.isCurrent())setMessage(t("Bank version published")+" · v"+r.version);});}}><fieldset disabled={p.busy}>
 <legend>{t("Publish question bank")}</legend><label>{t("Question bank ID")}<input required maxLength={64} value={bankId} onChange={e=>setBankId(e.target.value)}/></label><label>{t("Question bank title")}<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label>{t("Bank source course ID")}<input required maxLength={64} value={sourceCourse} onChange={e=>setSourceCourse(e.target.value)}/></label><label>{t("Question bank audience")}<select aria-label={t("Question bank audience")} value={access} onChange={e=>setAccess(e.target.value)}><option value="author">{t("Author only")}</option><option value="tenant">{t("Organization")}</option><option value="groups">{t("Selected groups")}</option></select></label>
 {access==="groups"&&<label>{t("Audience group IDs")}<input aria-label={t("Audience group IDs")} required maxLength={520} value={groupIds} onChange={e=>setGroupIds(e.target.value)}/></label>}
 <label><input type="checkbox" checked={ai} onChange={e=>setAI(e.target.checked)}/>{t("Permit model processing of bank questions")}</label><button>{t("Publish bank version")}</button></fieldset></form>
 {message&&<p role="status">{message}</p>}
 {rows.map(r=><article key={r.id}><h3>{r.title}</h3><p>{r.id} · v{r.version} · {r.questionCount} {t("questions")} · {r.state}</p><button disabled={p.busy||r.state!=="published"} onClick={()=>void p.run(async()=>{const bank=await p.op("learning_get_question_bank",{bankId:r.id,version:r.version});if(p.isCurrent()){setSelected(bank);setQuestions(bank.questions.slice(0,50).map((q:any)=>q.id));setTarget("");}})}>{t("Choose bank questions")}</button>
 {r.state==="published"&&(p.admin||r.owner===p.principalId)&&<button disabled={p.busy} onClick={()=>void p.run(async()=>{await p.mutate("learning_retire_question_bank",{bankId:r.id});if(p.isCurrent())setSelected(null);})}>{t("Retire question bank")}</button>}</article>)}
 <button disabled={p.busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-10))}>{t("Previous banks")}</button><button disabled={p.busy||next===null} onClick={()=>setOffset(next!)}>{t("Next banks")}</button>
 {selected&&<form aria-label={t("Apply question bank")} onSubmit={e=>{e.preventDefault();void p.run(async()=>{if(!questions.length)throw new Error(t("Choose one to fifty bank questions"));await p.mutate("learning_apply_question_bank",{courseId:target,source:{bankId:selected.id,version:selected.version,questionIds:questions}});if(p.isCurrent())setMessage(t("Bank applied. Reopen the target course draft to review and publish."));});}}><fieldset disabled={p.busy}><legend>{t("Apply question bank")} · {selected.id} · v{selected.version}</legend>
 {selected.questions.map((q:any)=><label key={q.id}><input type="checkbox" checked={questions.includes(q.id)} disabled={!questions.includes(q.id)&&questions.length>=50} onChange={e=>setQuestions(e.target.checked?[...questions,q.id]:questions.filter(id=>id!==q.id))}/>{q.id} · {q.prompt}</label>)}
 <label>{t("Bank target course ID")}<input required maxLength={64} value={target} onChange={e=>setTarget(e.target.value)}/></label><button>{t("Apply selected bank version")}</button></fieldset></form>}</section>;
}
