import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fixture,data} from './helpers.ts';
import {bindingFixture,publishBindingAward,awardDefinition,publishNext,finishCourse,assignedBindingFixture,courseChange,groupDefinition,ownAward} from './award-binding-fixture.ts';
const open=(f:ReturnType<typeof fixture>,address:any)=>data(f.call('learner-a','learning_enroll_award_course',address));
test('nested original versions are selected by exact criterion path, never by highest version; each bound official proof stays distinct',()=>{
 const f=fixture();try{publishBindingAward(f,'child-old',awardDefinition('Original old child',{target:1,requirements:[awardDefinition().requirements[0]]}));publishNext(f);publishBindingAward(f,'child-new',awardDefinition('Original new child',{target:1,requirements:[awardDefinition().requirements[0]]}));publishBindingAward(f,'two-pins',awardDefinition('Original two pins',{requirements:[{id:'old',title:'Old required pin',required:true,credits:1,alternatives:[{kind:'award',id:'child-old'}]},{id:'new',title:'New required pin',required:true,credits:1,alternatives:[{kind:'award',id:'child-new'}]}]}));const e=data(f.call('learner-a','learning_enroll_award',{collectionId:'two-pins'}));
 const common={awardEnrollmentId:e.awardEnrollmentId,courseId:'learning-vi'};assert.equal(f.call('learner-a','learning_enroll_award_course',common).ok,false);
 const a=open(f,{...common,criterionPath:'old/child-old@1/course'}),b=open(f,{...common,criterionPath:'new/child-new@1/course'});assert.equal(a.version,1);assert.equal(b.version,2);assert.notEqual(a.enrollmentId,b.enrollmentId);assert.equal(f.call('learner-a','learning_enroll_award_course',{...common,criterionPath:'invented'}).ok,false);finishCourse(f,b.enrollmentId);let root=ownAward(f,e.awardEnrollmentId);assert.equal(root.requirements[0].alternatives[0].earned,0);assert.equal(root.requirements[1].alternatives[0].earned,1);finishCourse(f,a.enrollmentId);root=ownAward(f,e.awardEnrollmentId);assert.equal(root.requirements[0].alternatives[0].earned,1);assert.equal(root.requirements[1].alternatives[0].earned,1);assert.equal(root.earned,2);assert.equal(root.completed,true);
 }finally{f.db.close();}
});
test('completed-course requalification binds a separately reviewed fresh record and preserves original attempts, certificates and ledger byte-for-byte',()=>{
 const f=bindingFixture();try{const e=open(f,f.address);finishCourse(f,e.enrollmentId);const old=f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(e.enrollmentId),attempts=f.db.prepare('SELECT * FROM attempts').all(),certs=f.db.prepare('SELECT * FROM certificates').all();publishNext(f);const args=courseChange(f,f.address,2),opts={idempotencyKey:'bound-requalify',expectedRevision:f.service.context('learner-a').revision};assert.equal(f.call('learner-a','human_requalify_award_course',args).ok,false);assert.equal(f.call('learner-b','human_requalify_award_course',args,'human').ok,false);const first=f.call('learner-a','human_requalify_award_course',args,'human',opts),newId=data(first).enrollmentId;assert.deepEqual(f.call('learner-a','human_requalify_award_course',args,'human',opts),first);assert.equal(f.call('learner-a','human_requalify_award_course',args,'human').ok,false);const fresh=f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(newId)!;assert.equal(fresh.version,2);assert.equal(fresh.completed_lessons,'[]');assert.equal(fresh.completed_at,null);assert.equal(ownAward(f,f.e.awardEnrollmentId).earned,0);assert.deepEqual(f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(e.enrollmentId),old);assert.deepEqual(f.db.prepare('SELECT * FROM attempts').all(),attempts);assert.deepEqual(f.db.prepare('SELECT * FROM certificates').all(),certs);finishCourse(f,newId);assert.equal(ownAward(f,f.e.awardEnrollmentId).earned,1);assert.equal(ownAward(f,f.e.awardEnrollmentId).requirements[0].alternatives[0].originalVersion,1);
 }finally{f.db.close();}
});
test('award-cycle child migration requires two humans and keeps original cycle, future pins, due date and assigner',()=>{
 const f=assignedBindingFixture();try{const e=open(f,f.address);publishNext(f);const originalCycle=f.db.prepare('SELECT * FROM assignment_cycles').all(),originalPlan=f.db.prepare('SELECT * FROM assignment_plans').all(),args=courseChange(f,f.address,2,'manager');assert.equal(f.call('learner-a','human_requalify_award_course',args,'human').ok,false);assert.equal(f.call('learner-a','human_offer_award_course_change',args,'human').ok,false);const offer=data(f.call('manager','human_offer_award_course_change',args,'human'));assert.equal(f.db.prepare('SELECT count(*) n FROM enrollments').get()!.n,1);const accept={reviewId:offer.reviewId,targetVersion:2,expectedBindingRevision:0,confirmed:true};assert.equal(f.call('learner-b','human_accept_award_course_change',accept,'human').ok,false);assert.equal(f.call('learner-a','human_accept_award_course_change',{...accept,targetVersion:1},'human').ok,false);const first=f.call('learner-a','human_accept_award_course_change',accept,'human',{idempotencyKey:'cycle-binding',expectedRevision:f.service.context('learner-a').revision}),fresh=data(first);assert.equal(fresh.version,2);const row=f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(fresh.enrollmentId)!;assert.equal(row.assignment_cycle_id,f.e.assignment_cycle_id);assert.equal(row.assigned_by,f.e.assigned_by);assert.equal(row.due_date,f.e.due_date);assert.equal(row.completed_lessons,'[]');assert.deepEqual(f.db.prepare('SELECT * FROM assignment_cycles').all(),originalCycle);assert.deepEqual(f.db.prepare('SELECT * FROM assignment_plans').all(),originalPlan);assert.equal(ownAward(f,f.e.id).earned,0);finishCourse(f,fresh.enrollmentId);assert.equal(ownAward(f,f.e.id).earned,1);const next=new Date(Date.parse(f.plan.startsAt)+30*86400000).toISOString();f.service.assignments.runBackground(next);const cycles=f.db.prepare('SELECT * FROM assignment_cycles ORDER BY run_at').all();assert.equal(cycles.length,2);assert.equal(cycles[1]!.target_version,1);assert.equal(JSON.parse(String(f.db.prepare('SELECT content FROM collection_versions WHERE collection_id=? AND version=1').get('binding-award')!.content)).requirements[0].alternatives[0].version,1);
 }finally{f.db.close();}
});
test('live manager and group revocation deny original accepted receipt; scheduler rejoin restores current child only and cancellation stays final',()=>{
 const f=assignedBindingFixture(true);try{const old=open(f,f.address);publishNext(f);const args=courseChange(f,f.address,2,'manager'),offer=data(f.call('manager','human_offer_award_course_change',args,'human')),accept={reviewId:offer.reviewId,targetVersion:2,expectedBindingRevision:0,confirmed:true},opts={idempotencyKey:'live-bound-change',expectedRevision:f.service.context('learner-a').revision},first=f.call('learner-a','human_accept_award_course_change',accept,'human',opts);const newId=data(first).enrollmentId;
 f.db.prepare("UPDATE accounts SET manager_id=NULL WHERE id='learner-a'").run();assert.equal(f.call('learner-a','human_accept_award_course_change',accept,'human',opts).ok,false);f.db.prepare("UPDATE accounts SET manager_id='manager' WHERE id='learner-a'").run();
 data(f.call('admin','learning_save_group',{groupId:'binding-group',group:groupDefinition([])}));assert.equal(f.call('learner-a','human_accept_award_course_change',accept,'human',opts).ok,false);f.service.assignments.runBackground();assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(newId)!.assignment_state,'withdrawn');data(f.call('admin','learning_save_group',{groupId:'binding-group',group:groupDefinition()}));f.service.assignments.runBackground();assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(newId)!.assignment_state,'active');assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(old.enrollmentId)!.assignment_state,'withdrawn');assert.deepEqual(f.call('learner-a','human_accept_award_course_change',accept,'human',opts),first);
 data(f.call('manager','learning_set_assignment_plan_state',{planId:'binding-plan',state:'cancelled',reason:'Original cancellation'}));assert.equal(f.call('learner-a','human_accept_award_course_change',accept,'human',opts).ok,false);assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(newId)!.assignment_state,'cancelled');
 }finally{f.db.close();}
});
test('pending manual grade blocks offer until real assessor resolution; no grade is carried into the reviewed child',()=>{
 const f=assignedBindingFixture(false,'essay');try{
  const e=open(f,f.address);data(f.call('learner-a','human_complete_lesson',{enrollmentId:e.enrollmentId,lessonId:'practice'},'human'));const at=data(f.call('learner-a','learning_start_attempt',{enrollmentId:e.enrollmentId}));data(f.call('learner-a','human_save_answer',{attemptId:at.attemptId,questionId:'essay',answer:'Original pending reasoning'},'human'));data(f.call('learner-a','human_submit_attempt',{attemptId:at.attemptId,confirmed:true},'human'));publishNext(f);const args=courseChange(f,f.address,3,'manager');assert.equal(f.call('manager','human_offer_award_course_change',args,'human').ok,false);data(f.call('assessor','human_assess_answer',{attemptId:at.attemptId,questionId:'essay',points:0,reason:'Resolved original failed reasoning'},'human'));const offer=data(f.call('manager','human_offer_award_course_change',args,'human')),fresh=data(f.call('learner-a','human_accept_award_course_change',{reviewId:offer.reviewId,targetVersion:3,expectedBindingRevision:0,confirmed:true},'human'));assert.equal(f.db.prepare('SELECT count(*) n FROM attempts WHERE enrollment_id=?').get(fresh.enrollmentId)!.n,0);assert.equal(f.db.prepare('SELECT grading_state FROM attempts WHERE id=?').get(at.attemptId)!.grading_state,'graded');
 }finally{f.db.close();}
});
test('a booking added after coordinator offer blocks acceptance until explicit learner cancellation, without carrying attendance',()=>{
 const f=assignedBindingFixture(false,'event');try{const e=open(f,f.address);publishNext(f);const args=courseChange(f,f.address,3,'manager'),offer=data(f.call('manager','human_offer_award_course_change',args,'human')),booking=data(f.call('learner-a','learning_book_session',{enrollmentId:e.enrollmentId,lessonId:'event',sessionId:'original'})),accept={reviewId:offer.reviewId,targetVersion:3,expectedBindingRevision:0,confirmed:true};assert.equal(f.call('learner-a','human_accept_award_course_change',accept,'human').ok,false);assert.equal(f.db.prepare('SELECT state FROM bookings WHERE id=?').get(booking.bookingId)!.state,'booked');data(f.call('learner-a','learning_cancel_booking',{bookingId:booking.bookingId},'human'));const before=f.db.prepare('SELECT * FROM bookings WHERE id=?').get(booking.bookingId),fresh=data(f.call('learner-a','human_accept_award_course_change',accept,'human'));assert.deepEqual(f.db.prepare('SELECT * FROM bookings WHERE id=?').get(booking.bookingId),before);assert.equal(f.db.prepare('SELECT count(*) n FROM bookings WHERE enrollment_id=?').get(fresh.enrollmentId)!.n,0);
 }finally{f.db.close();}
});
test('binding review, enrollment, receipts and counterpart revisions roll back atomically on audit failure',()=>{
 const f=assignedBindingFixture();try{open(f,f.address);publishNext(f);const args=courseChange(f,f.address,2,'manager'),before=JSON.stringify(f.db.prepare('SELECT * FROM workspaces ORDER BY id').all());f.db.exec("CREATE TRIGGER fail_binding_offer BEFORE INSERT ON audit WHEN NEW.tool='human_offer_award_course_change' BEGIN SELECT RAISE(ABORT,'binding audit'); END;");assert.equal(f.call('manager','human_offer_award_course_change',args,'human').ok,false);assert.equal(f.db.prepare('SELECT count(*) n FROM award_course_reviews').get()!.n,0);assert.equal(JSON.stringify(f.db.prepare('SELECT * FROM workspaces ORDER BY id').all()),before);f.db.exec('DROP TRIGGER fail_binding_offer');const offer=data(f.call('manager','human_offer_award_course_change',args,'human')),accept={reviewId:offer.reviewId,targetVersion:2,expectedBindingRevision:0,confirmed:true},rows=f.db.prepare('SELECT * FROM enrollments').all();f.db.exec("CREATE TRIGGER fail_binding_accept BEFORE INSERT ON audit WHEN NEW.tool='human_accept_award_course_change' BEGIN SELECT RAISE(ABORT,'binding audit'); END;");assert.equal(f.call('learner-a','human_accept_award_course_change',accept,'human').ok,false);assert.deepEqual(f.db.prepare('SELECT * FROM enrollments').all(),rows);assert.equal(f.db.prepare('SELECT state FROM award_course_reviews WHERE id=?').get(offer.reviewId)!.state,'pending');assert.equal(f.db.prepare('SELECT revision FROM award_course_bindings').get()!.revision,0);
 }finally{f.db.close();}
});
test('nonempty 041→042 preserves original ledger, certificate, events and FKs; binding history survives actual SQLite reopen',()=>{
 const dir=mkdtempSync(join(tmpdir(),'pear-binding-migrate-')),path=join(dir,'db.sqlite');let f=bindingFixture(path);try{const e=data(f.call('learner-a','learning_enroll',{courseId:'learning-vi'}));finishCourse(f,e.enrollmentId);const old=f.db.prepare('SELECT * FROM enrollments').all().map(({award_binding_id,...r}:any)=>r),events=f.db.prepare('SELECT * FROM integration_events').all(),certs=f.db.prepare('SELECT * FROM certificates').all();f.db.exec('DROP INDEX enrollment_award_binding; DROP INDEX enrollment_direct; DROP INDEX enrollment_cycle; ALTER TABLE enrollments DROP COLUMN award_binding_id; DROP TABLE award_course_reviews; DROP TABLE award_course_bindings; DROP TRIGGER IF EXISTS integration_enrollment_assignment_created; DROP TRIGGER IF EXISTS integration_award_assignment_created; DROP TABLE award_completion_snapshots; DROP TABLE webhook_claim_cursor; CREATE UNIQUE INDEX enrollment_direct ON enrollments(learner,course_id) WHERE assignment_cycle_id IS NULL AND retake_of IS NULL; CREATE UNIQUE INDEX enrollment_cycle ON enrollments(learner,assignment_cycle_id,course_id) WHERE assignment_cycle_id IS NOT NULL AND retake_of IS NULL; DELETE FROM schema_version WHERE version=42;');f.db.close();f={...fixture(path),e:f.e,address:f.address};assert.deepEqual(f.db.prepare('SELECT * FROM enrollments').all().map(({award_binding_id,...r}:any)=>r),old);assert.deepEqual(f.db.prepare('SELECT * FROM integration_events').all(),events);assert.deepEqual(f.db.prepare('SELECT * FROM certificates').all(),certs);const args=courseChange(f,f.address,1),newId=data(f.call('learner-a','human_requalify_award_course',args,'human')).enrollmentId;const binding=f.db.prepare('SELECT * FROM award_course_bindings').get();f.db.close();f={...fixture(path),e:f.e,address:f.address};assert.deepEqual(f.db.prepare('SELECT * FROM award_course_bindings').get(),binding);assert.equal(f.db.prepare('SELECT completed_at FROM enrollments WHERE id=?').get(newId)!.completed_at,null);assert.deepEqual(f.db.prepare('PRAGMA foreign_key_check').all(),[]);
 }finally{try{f.db.close();}catch{}rmSync(dir,{recursive:true,force:true});}
});
test('reviewed pinned group rights stay live before receipts, proof and scheduler rejoin even after tenant-visible latest publication',()=>{
 const f=assignedBindingFixture(true);try{const old=open(f,f.address);data(f.call('admin','learning_save_group',{groupId:'reviewed-group',group:groupDefinition(['manager','learner-a'])}));publishNext(f,{access:'groups',groupIds:['reviewed-group']});const offer=data(f.call('manager','human_offer_award_course_change',courseChange(f,f.address,2,'manager'),'human')),args={reviewId:offer.reviewId,targetVersion:2,expectedBindingRevision:0,confirmed:true},opts={idempotencyKey:'group-replay',expectedRevision:f.service.context('learner-a').revision},first=f.call('learner-a','human_accept_award_course_change',args,'human',opts),fresh=data(first);publishNext(f);
 data(f.call('admin','learning_save_group',{groupId:'reviewed-group',group:groupDefinition(['manager'])}));assert.equal(f.call('learner-a','human_accept_award_course_change',args,'human',opts).ok,false);assert.equal(f.call('learner-a','human_complete_lesson',{enrollmentId:fresh.enrollmentId,lessonId:'practice'},'human').ok,false);f.service.assignments.runBackground();assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(fresh.enrollmentId)!.assignment_state,'withdrawn');
 data(f.call('admin','learning_save_group',{groupId:'binding-group',group:groupDefinition([])}));f.service.assignments.runBackground();data(f.call('admin','learning_save_group',{groupId:'binding-group',group:groupDefinition()}));f.service.assignments.runBackground();assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(fresh.enrollmentId)!.assignment_state,'withdrawn');assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(old.enrollmentId)!.assignment_state,'withdrawn');
 data(f.call('admin','learning_save_group',{groupId:'reviewed-group',group:groupDefinition(['manager','learner-a'])}));f.service.assignments.runBackground();assert.deepEqual(f.call('learner-a','human_accept_award_course_change',args,'human',opts),first);finishCourse(f,fresh.enrollmentId);assert.equal(ownAward(f,f.e.id).earned,1);data(f.call('admin','learning_save_group',{groupId:'reviewed-group',group:groupDefinition(['manager'])}));assert.equal(ownAward(f,f.e.id).earned,0);
 }finally{f.db.close();}
});
test('bound proof cannot borrow a different learner, tenant, version, cycle or stale completion even at the current binding pointer',()=>{
 const f=assignedBindingFixture();try{const e=open(f,f.address);finishCourse(f,e.enrollmentId);assert.equal(ownAward(f,f.e.id).earned,1);publishNext(f);const original=f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(e.enrollmentId)!;
 for(const [column,value] of [['learner','learner-b'],['tenant','other'],['version',2],['assignment_cycle_id',null],['completed_at','2000-01-01T00:00:00.000Z']] as const){f.db.prepare(`UPDATE enrollments SET ${column}=? WHERE id=?`).run(value,e.enrollmentId);assert.equal(ownAward(f,f.e.id).earned,0,column);f.db.prepare(`UPDATE enrollments SET ${column}=? WHERE id=?`).run(original[column],e.enrollmentId);}assert.equal(ownAward(f,f.e.id).earned,1);
 }finally{f.db.close();}
});
test('review CAS, payload identity, expiry and explicit coordinator cancellation cannot create a second successor or revive an offer',()=>{
 const f=assignedBindingFixture();try{open(f,f.address);publishNext(f);const args=courseChange(f,f.address,2,'manager'),rows=f.db.prepare('SELECT * FROM enrollments').all();assert.equal(f.call('manager','human_offer_award_course_change',args,'human',{expectedRevision:0}).ok,false);const offer=data(f.call('manager','human_offer_award_course_change',args,'human'));assert.equal(f.call('manager','human_offer_award_course_change',args,'human').ok,false);assert.equal(f.call('learner-a','human_accept_award_course_change',{reviewId:offer.reviewId,targetVersion:2,expectedBindingRevision:1,confirmed:true},'human').ok,false);assert.deepEqual(f.db.prepare('SELECT * FROM enrollments').all(),rows);
 const cancelled=f.call('manager','human_cancel_award_course_change',{reviewId:offer.reviewId,confirmed:true},'human',{idempotencyKey:'cancel-review',expectedRevision:f.service.context('manager',f.service.library(f.service.principal('manager'))).revision});data(cancelled);assert.equal(f.call('learner-a','human_accept_award_course_change',{reviewId:offer.reviewId,targetVersion:2,expectedBindingRevision:0,confirmed:true},'human').ok,false);const next=data(f.call('manager','human_offer_award_course_change',args,'human'));f.db.prepare("UPDATE award_course_reviews SET expires_at='2000-01-01T00:00:00Z' WHERE id=?").run(next.reviewId);assert.equal(f.call('learner-a','human_accept_award_course_change',{reviewId:next.reviewId,targetVersion:2,expectedBindingRevision:0,confirmed:true},'human').ok,false);assert.deepEqual(f.db.prepare('SELECT * FROM enrollments').all(),rows);assert.equal(f.call('outsider','human_get_award_course_review',f.address,'human').ok,false);
 }finally{f.db.close();}
});
test('ordinary enrollment stays separate from criterion roots; original opening receipt cannot return a superseded course after a reviewed binding change',()=>{
 const f=bindingFixture();try{const opts={idempotencyKey:'bound-original-opening',expectedRevision:f.service.context('learner-a').revision},first=f.call('learner-a','learning_enroll_award_course',f.address,'bridge',opts),old=data(first),ordinary=data(f.call('learner-a','learning_enroll',{courseId:'learning-vi'}));assert.notEqual(old.enrollmentId,ordinary.enrollmentId);assert.equal(f.db.prepare('SELECT award_binding_id FROM enrollments WHERE id=?').get(ordinary.enrollmentId)!.award_binding_id,null);publishNext(f);const fresh=data(f.call('learner-a','human_requalify_award_course',courseChange(f,f.address,2),'human'));assert.equal(f.call('learner-a','learning_enroll_award_course',f.address,'bridge',opts).error?.code,'STALE_CONTEXT');assert.equal(open(f,f.address).enrollmentId,fresh.enrollmentId);assert.equal(data(f.call('learner-a','learning_enroll_award_course',{awardEnrollmentId:f.e.awardEnrollmentId,courseId:'learning-vi'})).enrollmentId,fresh.enrollmentId);assert.equal(f.call('learner-a','human_complete_lesson',{enrollmentId:old.enrollmentId,lessonId:'practice'},'human').ok,false);
 }finally{f.db.close();}
});

test('unfinished nested proof respects live child audience; issued certificate freezes the accepted graph and rejects snapshot mutation',()=>{
 const f=fixture();try{publishBindingAward(f,'snapshot-child',awardDefinition('Original nested proof',{target:1,requirements:[awardDefinition().requirements[0]]}));publishBindingAward(f,'snapshot-root',awardDefinition('Original frozen graph',{target:1,requirements:[{id:'nested',title:'Nested',required:true,credits:1,alternatives:[{kind:'award',id:'snapshot-child'}]}]}));
 const root=data(f.call('learner-a','learning_enroll_award',{collectionId:'snapshot-root'})),address={awardEnrollmentId:root.awardEnrollmentId,criterionPath:'nested/snapshot-child@1/course',courseId:'learning-vi'},child=data(f.call('learner-a','learning_enroll',{courseId:'learning-vi'}));
 data(f.call('admin','learning_save_group',{groupId:'snapshot-audience',group:groupDefinition(['learner-b'])}));publishBindingAward(f,'snapshot-child',awardDefinition('Restricted nested proof',{target:1,access:'groups',groupIds:['snapshot-audience'],requirements:[awardDefinition().requirements[0]]}));
 finishCourse(f,child.enrollmentId);let progress=ownAward(f,root.awardEnrollmentId);assert.equal(progress.earned,0);assert.equal(progress.completed_at,null);assert.equal(progress.requirements[0].alternatives[0].unavailable,true);
 data(f.call('admin','learning_save_group',{groupId:'snapshot-audience',group:groupDefinition()}));f.service.programs.refreshLearner('demo','learner-a');progress=ownAward(f,root.awardEnrollmentId);assert.equal(progress.earned,1);assert.ok(progress.certificate_id);const saved=f.db.prepare('SELECT * FROM award_completion_snapshots WHERE certificate_id=?').get(progress.certificate_id)!;assert.equal(saved.provenance,'issuance');
 data(f.call('admin','learning_save_group',{groupId:'snapshot-audience',group:groupDefinition(['learner-b'])}));publishNext(f);const after=ownAward(f,root.awardEnrollmentId);assert.equal(after.earned,1);assert.equal(after.certificate_id,progress.certificate_id);assert.deepEqual(after.requirements,progress.requirements);assert.throws(()=>f.db.prepare("UPDATE award_completion_snapshots SET progress='{}' WHERE certificate_id=?").run(progress.certificate_id),/Immutable/);
 }finally{f.db.close();}
});

test('legacy unbound completion from a different assignment cycle cannot satisfy original award cycle',()=>{
 const f=assignedBindingFixture();try{const original=f.e.assignment_cycle_id;f.service.assignments.runBackground(new Date(Date.parse(f.plan.startsAt)+30*86400000).toISOString());const next=f.db.prepare('SELECT id FROM assignment_cycles WHERE id!=?').get(original)!.id;f.db.prepare("INSERT INTO enrollments(id,tenant,learner,course_id,version,assignment_cycle_id,status,completed_at) VALUES('legacy-wrong-cycle','demo','learner-a','learning-vi',1,?,'completed',?)").run(next,new Date().toISOString());assert.equal(ownAward(f,f.e.id).earned,0);
 }finally{f.db.close();}
});

test('event joining is disclosed only to an active booked learner, with the booked session visible to the scoped assessor',()=>{
 const f=assignedBindingFixture(false,'event');try{const e=open(f,f.address),scope={enrollmentId:e.enrollmentId,lessonId:'event'};assert.equal(data(f.call('learner-a','learning_get_lesson',scope,'human')).sessions[0].joinUrl,undefined);assert.equal(data(f.call('learner-a','learning_get_blended_lesson',scope,'human')).sessions[0].joinUrl,undefined);const b=data(f.call('learner-a','learning_book_session',{...scope,sessionId:'original'},'human'));assert.ok(data(f.call('learner-a','learning_get_lesson',scope,'human')).sessions[0].joinUrl);const row=data(f.call('assessor','learning_get_blended_queue',{},'human')).items.find((r:any)=>r.id===b.bookingId);assert.equal(row.sessionId,'original');assert.equal(row.location,'Original room');data(f.call('learner-a','learning_cancel_booking',{bookingId:b.bookingId},'human'));assert.equal(data(f.call('learner-a','learning_get_blended_lesson',scope,'human')).sessions[0].joinUrl,undefined);
 }finally{f.db.close();}
});


test('nested ancestor revocation gates opening receipts, review and official writes; assigned rejoin keeps the same bound child',()=>{
 const f=fixture();try{data(f.call('admin','learning_save_group',{groupId:'nested-members',group:groupDefinition()}));publishBindingAward(f,'live-child',awardDefinition('Original nested audience'));publishBindingAward(f,'live-root',awardDefinition('Original root',{requirements:[{id:'nested',title:'Nested original obligation',required:true,credits:2,alternatives:[{kind:'award',id:'live-child'}]}]}));
 const plan={title:'Original nested cycle',targetKind:'award',targetId:'live-root',audienceKind:'individuals',learnerIds:['learner-a'],groupId:'',membership:'fixed',startsAt:new Date(Date.now()-1000).toISOString(),repeatDays:30,endAt:null,dueKind:'rolling',fixedDueAt:null,rollingDays:7};data(f.call('manager','learning_save_assignment_plan',{planId:'nested-cycle',plan,reason:'Original reviewed nested cycle'}));f.service.assignments.runBackground();const root=data(f.call('learner-a','learning_get_my_awards')).items.find((r:any)=>r.award_id==='live-root');const address={awardEnrollmentId:root.id,criterionPath:'nested/live-child@1/course',courseId:'learning-vi'},opts={idempotencyKey:'original-nested-open',expectedRevision:f.service.context('learner-a').revision},enrollment=data(f.call('learner-a','learning_enroll_award_course',address,'bridge',opts));
 publishBindingAward(f,'live-child',awardDefinition('Restricted current child',{access:'groups',groupIds:['nested-members']}));data(f.call('admin','learning_save_group',{groupId:'nested-members',group:groupDefinition(['learner-b'])}));const before=f.db.prepare('SELECT * FROM enrollments').all();assert.equal(f.call('learner-a','learning_enroll_award_course',address,'bridge',opts).error?.code,'FORBIDDEN');assert.equal(f.call('manager','human_get_award_course_review',address,'human').error?.code,'FORBIDDEN');assert.equal(f.call('learner-a','human_complete_lesson',{enrollmentId:enrollment.enrollmentId,lessonId:'practice'},'human').error?.code,'FORBIDDEN');assert.deepEqual(f.db.prepare('SELECT * FROM enrollments').all(),before);
 f.service.assignments.runBackground();assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(enrollment.enrollmentId)!.assignment_state,'withdrawn');data(f.call('admin','learning_save_group',{groupId:'nested-members',group:groupDefinition()}));f.service.assignments.runBackground();assert.equal(f.db.prepare('SELECT assignment_state FROM enrollments WHERE id=?').get(enrollment.enrollmentId)!.assignment_state,'active');assert.equal(open(f,address).enrollmentId,enrollment.enrollmentId);assert.equal(f.db.prepare('SELECT count(*) n FROM enrollments').get()!.n,1);finishCourse(f,enrollment.enrollmentId);f.db.prepare("UPDATE accounts SET active=0 WHERE id='manager'").run();assert.equal(data(f.call('learner-a','learning_get_progress',{enrollmentId:enrollment.enrollmentId})).status,'completed');assert.equal(f.call('learner-a','learning_enroll_award_course',address,'bridge',opts).ok,false);
 }finally{f.db.close();}
});

test('populated v41 upgrade preserves a legacy issued award and marks its available-ledger snapshot provenance through reopen',()=>{
 const dir=mkdtempSync(join(tmpdir(),'pear-legacy-credential-')),path=join(dir,'db.sqlite');let f=bindingFixture(path);try{const c=data(f.call('learner-a','learning_enroll',{courseId:'learning-vi'}));finishCourse(f,c.enrollmentId);data(f.call('learner-a','human_submit_external_record',{awardEnrollmentId:f.e.awardEnrollmentId,criterionPath:'evidence',amount:1,evidence:'Original independently confirmed legacy practice',confirmed:true},'human'));const original=f.db.prepare('SELECT * FROM award_enrollments WHERE id=?').get(f.e.awardEnrollmentId)!,attempts=f.db.prepare('SELECT * FROM attempts').all(),records=f.db.prepare('SELECT * FROM external_records').all();assert.ok(original.certificate_id);
 f.db.exec('DROP TRIGGER integration_enrollment_assignment_created; DROP TRIGGER integration_award_assignment_created; DROP INDEX enrollment_award_binding; DROP INDEX enrollment_direct; DROP INDEX enrollment_cycle; ALTER TABLE enrollments DROP COLUMN award_binding_id; DROP TABLE award_course_reviews; DROP TABLE award_course_bindings; DROP TABLE award_completion_snapshots; DROP TABLE webhook_claim_cursor; CREATE UNIQUE INDEX enrollment_direct ON enrollments(learner,course_id) WHERE assignment_cycle_id IS NULL AND retake_of IS NULL; CREATE UNIQUE INDEX enrollment_cycle ON enrollments(learner,assignment_cycle_id,course_id) WHERE assignment_cycle_id IS NOT NULL AND retake_of IS NULL; DELETE FROM schema_version WHERE version=42;');f.db.close();f={...fixture(path),e:f.e,address:f.address};assert.deepEqual(f.db.prepare('SELECT * FROM award_enrollments WHERE id=?').get(original.id),original);assert.deepEqual(f.db.prepare('SELECT * FROM attempts').all(),attempts);assert.deepEqual(f.db.prepare('SELECT * FROM external_records').all(),records);const snapshot=f.db.prepare('SELECT * FROM award_completion_snapshots WHERE certificate_id=?').get(original.certificate_id)!;assert.equal(snapshot.provenance,'legacy_ledger_at_upgrade');assert.equal(JSON.parse(String(snapshot.progress)).earned,2);f.db.close();f={...fixture(path),e:f.e,address:f.address};assert.deepEqual(f.db.prepare('SELECT * FROM award_completion_snapshots WHERE certificate_id=?').get(original.certificate_id),snapshot);assert.deepEqual(f.db.prepare('PRAGMA foreign_key_check').all(),[]);
 }finally{f.db.close();rmSync(dir,{recursive:true,force:true});}
});
