import {test,expect} from "@playwright/test";
import {assignedQuizFixture,offerAssigned} from "../assigned-quiz-fixture.ts";
import {data} from "../helpers.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("coordinator explicitly renews an expired same-version review then cancels it in a real browser without changing learning",async({page})=>{
 test.setTimeout(90000);const f=assignedQuizFixture(),old=data(offerAssigned(f)),origin="http://127.0.0.1:4376";f.db.prepare("UPDATE assigned_quiz_reviews SET expires_at='2000-01-01T00:00:00.000Z' WHERE id=?").run(old.reviewId);const before=JSON.stringify(f.db.prepare("SELECT * FROM enrollments WHERE id=?").get(f.e.enrollmentId)),{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function write(tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName===tool);await click();const result=await(await response).json();expect(result.ok,JSON.stringify(result.error)).toBe(true);}
 try{
  await app.listen({port:4376,host:"127.0.0.1"});await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill("manager");await page.getByLabel("Password",{exact:true}).fill("manager-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();await page.getByRole("button",{name:"Administration",exact:true}).click();
  const region=page.getByRole("region",{name:"Coordinate assigned quiz restart",exact:true}),reviewButton=region.getByRole("button",{name:"Review direct assignment quiz",exact:true});await region.getByLabel("Direct assignment enrollment ID",{exact:true}).fill(f.e.enrollmentId);await reviewButton.click();const form=region.getByRole("form",{name:"Coordinator quiz restart confirmation",exact:true});await expect(form).toBeVisible();await form.getByLabel("I authorize offering this assigned objective quiz restart.",{exact:true}).check();await write("human_offer_assigned_quiz_restart",()=>form.getByRole("button",{name:"Offer assigned quiz restart",exact:true}).click());await expect(region).toContainText("Assigned quiz review action recorded");
  const next=f.db.prepare("SELECT * FROM assigned_quiz_reviews WHERE previous_review=?").get(old.reviewId)!;expect(next.state).toBe("pending");await reviewButton.click();const cancel=region.getByRole("button",{name:"Cancel assigned quiz restart review",exact:true});await expect(cancel).toBeVisible();await write("human_cancel_assigned_quiz_review",()=>cancel.click());await expect(region).toContainText("Assigned quiz review action recorded");expect(f.db.prepare("SELECT state FROM assigned_quiz_reviews WHERE id=?").get(next.id)!.state).toBe("cancelled");expect(JSON.stringify(f.db.prepare("SELECT * FROM enrollments WHERE id=?").get(f.e.enrollmentId))).toBe(before);expect(f.db.prepare("SELECT count(*) n FROM enrollments WHERE retake_of=?").get(f.e.enrollmentId)!.n).toBe(0);
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
