import {test,expect} from "@playwright/test";
import {assignedQuizFixture} from "../assigned-quiz-fixture.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("manager offers and addressed learner confirms direct assignment quiz restart in real EN/VI browser",async({page})=>{
 test.setTimeout(90000);const f=assignedQuizFixture(),origin="http://127.0.0.1:4375",{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 async function write(tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName===tool);await click();const result=await(await response).json();expect(result.ok,JSON.stringify(result.error)).toBe(true);}
 try{
  await app.listen({port:4375,host:"127.0.0.1"});await login("manager");await page.getByRole("button",{name:"Administration",exact:true}).click();const region=page.getByRole("region",{name:"Coordinate assigned quiz restart",exact:true});
  await region.getByLabel("Direct assignment enrollment ID",{exact:true}).fill(f.e.enrollmentId);await region.getByRole("button",{name:"Review direct assignment quiz",exact:true}).click();const form=region.getByRole("form",{name:"Coordinator quiz restart confirmation",exact:true});await expect(form).toBeVisible();await expect(form.getByRole("button",{name:"Offer assigned quiz restart",exact:true})).toBeDisabled();await form.getByLabel("I authorize offering this assigned objective quiz restart.",{exact:true}).check();await write("human_offer_assigned_quiz_restart",()=>form.getByRole("button",{name:"Offer assigned quiz restart",exact:true}).click());await expect(region).toContainText("Assigned quiz review action recorded");expect(f.db.prepare("SELECT count(*) n FROM enrollments WHERE retake_of=?").get(f.e.enrollmentId)!.n).toBe(0);
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();await page.getByLabel("Interface language",{exact:true}).selectOption("vi");const learner=page.getByRole("region",{name:"Xem xét quiz được giao",exact:true});await expect(learner).toContainText("Original assigned quiz restart");await expect(learner).toContainText("2026-12-01");const accept=learner.getByRole("button",{name:"Đồng ý làm lại quiz được giao",exact:true});await expect(accept).toBeDisabled();await learner.getByLabel("Tôi đã xem xét và đồng ý làm lại quiz trắc nghiệm được giao này.",{exact:true}).check();await write("human_accept_assigned_quiz_restart",()=>accept.click());await expect(learner.getByRole("button",{name:"Đồng ý làm lại quiz được giao",exact:true})).toHaveCount(0);
  const successor=f.db.prepare("SELECT * FROM enrollments WHERE retake_of=?").get(f.e.enrollmentId)!;expect(successor.assigned_by).toBe("manager");expect(successor.due_date).toBe("2026-12-01T00:00:00.000Z");expect(successor.status).toBe("in_progress");expect(successor.version).toBe(2);expect(f.db.prepare("SELECT count(*) n FROM attempts WHERE enrollment_id=?").get(successor.id)!.n).toBe(0);expect(f.db.prepare("SELECT count(*) n FROM certificates").get()!.n).toBe(0);
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
