import {test,expect} from "@playwright/test";
import {courseRestartFixture} from "../course-restart-fixture.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("manager reviews full-change zero-progress policy and learner separately accepts that exact mode in real EN/VI browser",async({page})=>{
 test.setTimeout(90000);const f=courseRestartFixture("objective",":memory:",true),origin="http://127.0.0.1:4382",prior=f.db.prepare("SELECT * FROM attempts WHERE id=?").get(f.at.attemptId),{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 async function write(tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName===tool);await click();const result=await(await response).json();expect(result.ok,JSON.stringify(result.error)).toBe(true);}
 try{
  await app.listen({port:4382,host:"127.0.0.1"});await login("manager");await page.getByRole("button",{name:"Administration",exact:true}).click();await page.getByRole("region",{name:"Coordinate assigned quiz restart",exact:true}).getByLabel("Assigned restart policy",{exact:true}).selectOption("fresh_course");const region=page.getByRole("region",{name:"Coordinate full assigned course restart",exact:true});await region.getByLabel("Direct assignment enrollment ID",{exact:true}).fill(f.e.enrollmentId);await region.getByRole("button",{name:"Review direct assignment quiz",exact:true}).click();const form=region.getByRole("form",{name:"Coordinator full-course restart confirmation",exact:true});await expect(region).toContainText("Original latest full course");await expect(region).toContainText("Prior learning stays in history");const offer=form.getByRole("button",{name:"Offer full assigned course fresh start",exact:true});await expect(offer).toBeDisabled();await form.getByLabel("I authorize offering this assigned full-course fresh start.",{exact:true}).check();await write("human_offer_assigned_quiz_restart",()=>offer.click());await expect(region).toContainText("Assigned quiz review action recorded");expect(f.db.prepare("SELECT count(*) n FROM enrollments WHERE retake_of=?").get(f.e.enrollmentId)!.n).toBe(0);
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();await page.getByLabel("Interface language",{exact:true}).selectOption("vi");const learner=page.getByRole("region",{name:"Xem xét học khóa được giao từ đầu",exact:true});await expect(learner).toContainText("Original latest full course");const accept=learner.getByRole("button",{name:"Đồng ý học khóa được giao từ đầu",exact:true});await expect(accept).toBeDisabled();await learner.getByLabel("Tôi đã xem xét và đồng ý học khóa được giao này từ đầu.",{exact:true}).check();await write("human_accept_assigned_quiz_restart",()=>accept.click());await expect(learner).toHaveCount(0);
  const next=f.db.prepare("SELECT * FROM enrollments WHERE retake_of=?").get(f.e.enrollmentId)!;expect(next.completed_lessons).toBe("[]");expect(next.assigned_by).toBe("manager");expect(next.due_date).toBe("2026-12-01T00:00:00.000Z");expect(next.version).toBe(2);expect(next.status).toBe("in_progress");expect(f.db.prepare("SELECT * FROM attempts WHERE id=?").get(f.at.attemptId)).toEqual(prior);expect(f.db.prepare("SELECT count(*) n FROM certificates").get()!.n).toBe(0);
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
