import {test,expect,type Page} from '@playwright/test';
import {bindingFixture,assignedBindingFixture,publishNext,finishCourse} from '../award-binding-fixture.ts';
import {data} from '../helpers.ts';
import {createApp} from '../../src/server/app.ts';
import {resolve} from 'node:path';
async function login(page:Page,origin:string,user:string){await page.goto(origin);await page.getByLabel('Account',{exact:true}).fill(user);await page.getByLabel('Password',{exact:true}).fill(user+'-dev');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Sign out',exact:true})).toBeVisible();}
async function write(page:Page,tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith('/api/human/invoke')&&r.request().postDataJSON()?.toolName===tool);await click();const result=await(await response).json();expect(result.ok,JSON.stringify(result.error)).toBe(true);}
test('completed-course requalification selects an explicit version in EN and confirms fresh bound learning in VI without altering original proof',async({page})=>{
 test.setTimeout(90000);const f=bindingFixture(),origin='http://127.0.0.1:4387',old=data(f.call('learner-a','learning_enroll_award_course',f.address));finishCourse(f,old.enrollmentId);publishNext(f);const prior=f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(old.enrollmentId),certs=f.db.prepare('SELECT * FROM certificates').all(),{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve('dist')});
 try{await app.listen({port:4387,host:'127.0.0.1'});await login(page,origin,'learner-a');await page.getByRole('button',{name:'Programs',exact:true}).click();await page.getByRole('button',{name:'Review award course learning',exact:true}).click();const review=page.getByRole('region',{name:'Award course binding review',exact:true});await expect(review).toContainText('Original pinned version: 1');const version=review.getByLabel('Reviewed award course version',{exact:true});await expect(version).toHaveValue('');await expect(review.getByRole('button',{name:'Start reviewed award course learning',exact:true})).toBeDisabled();await version.selectOption('2');await page.getByLabel('Interface language',{exact:true}).selectOption('vi');const vi=page.getByRole('region',{name:'Xem xét liên kết khóa học trong chương trình',exact:true}),start=vi.getByRole('button',{name:'Bắt đầu lượt học chương trình đã xem xét',exact:true});await expect(vi).toContainText('không sao chép hoàn thành');await expect(start).toBeDisabled();await vi.getByLabel('Tôi đã xem xét đúng phiên bản khóa học này và đồng ý bắt đầu lượt học mới.',{exact:true}).check();await write(page,'human_requalify_award_course',()=>start.click());await expect(page.getByRole('heading',{name:'Các bước tiếp theo',exact:true})).toBeVisible();const fresh=f.db.prepare('SELECT e.* FROM award_course_bindings b JOIN enrollments e ON e.id=b.course_enrollment_id').get()!;expect(fresh.version).toBe(2);expect(fresh.completed_lessons).toBe('[]');expect(fresh.completed_at).toBeNull();expect(f.db.prepare('SELECT * FROM enrollments WHERE id=?').get(old.enrollmentId)).toEqual(prior);expect(f.db.prepare('SELECT * FROM certificates').all()).toEqual(certs);await page.screenshot({path:'artifacts/award-binding-learner.png',fullPage:true});
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
test('award-cycle change uses separate manager offer and learner VI confirmation while preserving original cycle and future pins',async({page,browser})=>{
 test.setTimeout(90000);const f=assignedBindingFixture(),origin='http://127.0.0.1:4388',old=data(f.call('learner-a','learning_enroll_award_course',f.address));publishNext(f);const originalCycle=f.db.prepare('SELECT * FROM assignment_cycles').all(),originalPlan=f.db.prepare('SELECT * FROM assignment_plans').all(),{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve('dist')}),learnerContext=await browser.newContext(),learner=await learnerContext.newPage();
 try{await app.listen({port:4388,host:'127.0.0.1'});await login(page,origin,'manager');await page.getByRole('button',{name:'Administration',exact:true}).click();const coordinator=page.getByRole('region',{name:'Coordinate award course learning',exact:true});await coordinator.getByLabel('Award enrollment ID',{exact:true}).fill(f.e.id);await coordinator.getByLabel('Criterion path',{exact:true}).fill('course');await coordinator.getByLabel('Award course ID',{exact:true}).fill('learning-vi');await coordinator.getByRole('button',{name:'Review exact award course',exact:true}).click();const offer=coordinator.getByRole('button',{name:'Offer award course change',exact:true});await expect(offer).toBeDisabled();await coordinator.getByLabel('Reviewed award course version',{exact:true}).selectOption('2');await expect(offer).toBeDisabled();await coordinator.getByLabel('I authorize this exact award course offer.',{exact:true}).check();await write(page,'human_offer_award_course_change',()=>offer.click());await expect(coordinator).toContainText('Award course review recorded');expect(f.db.prepare('SELECT count(*) n FROM enrollments').get()!.n).toBe(1);await page.screenshot({path:'artifacts/award-binding-coordinator.png',fullPage:true});
 await login(learner,origin,'learner-a');await learner.getByRole('button',{name:'Programs',exact:true}).click();await learner.getByRole('button',{name:'Review award course learning',exact:true}).click();await learner.getByLabel('Interface language',{exact:true}).selectOption('vi');const review=learner.getByRole('region',{name:'Xem xét liên kết khóa học trong chương trình',exact:true}),accept=review.getByRole('button',{name:'Chấp nhận thay đổi khóa học của chương trình',exact:true});await expect(review).toContainText('Phiên bản người điều phối đề nghị: 2');await expect(accept).toBeDisabled();await review.getByLabel('Tôi đã xem xét đúng phiên bản khóa học này và đồng ý bắt đầu lượt học mới.',{exact:true}).check();await write(learner,'human_accept_award_course_change',()=>accept.click());await expect(learner.getByRole('heading',{name:'Các bước tiếp theo',exact:true})).toBeVisible();const fresh=f.db.prepare('SELECT * FROM enrollments WHERE retake_of=?').get(old.enrollmentId)!;expect(fresh.version).toBe(2);expect(fresh.assignment_cycle_id).toBe(f.e.assignment_cycle_id);expect(fresh.due_date).toBe(f.e.due_date);expect(fresh.completed_lessons).toBe('[]');expect(fresh.completed_at).toBeNull();expect(f.db.prepare('SELECT * FROM assignment_cycles').all()).toEqual(originalCycle);expect(f.db.prepare('SELECT * FROM assignment_plans').all()).toEqual(originalPlan);await learner.screenshot({path:'artifacts/award-binding-cycle-learner.png',fullPage:true});
 }finally{await learnerContext.close();await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
