
import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("human author configures one-criterion award and custom unit names; learner moderation/completion/certificate use pinned literal labels in EN/VI",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4366",title="Original UI one-criterion award",plural="original points <img src=x>";
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 const write=(tool:string)=>page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().postDataJSON()?.toolName===tool);
 async function action(tool:string,click:()=>Promise<void>){const response=write(tool);await click();expect((await(await response).json()).ok).toBe(true);}
 try{
  await app.listen({port:4366,host:"127.0.0.1"});await login("admin");await page.getByRole("button",{name:"Administration",exact:true}).click();const editor=page.getByRole("form",{name:"Program editor",exact:true});await editor.getByLabel("Collection ID",{exact:true}).fill("ui-award-rules");await editor.getByLabel("Program title",{exact:true}).fill(title);await editor.getByLabel("Target",{exact:true}).fill("999");await editor.getByLabel("Credit unit",{exact:true}).selectOption("custom");await editor.getByLabel("Custom unit singular",{exact:true}).fill("original point");await editor.getByLabel("Custom unit plural",{exact:true}).fill(plural);await editor.getByLabel("Award completion rule",{exact:true}).selectOption("one_item");await expect(editor.getByLabel("Target",{exact:true})).toBeDisabled();await expect(editor.getByLabel("Required criterion",{exact:true})).not.toBeChecked();
  await editor.getByLabel("Reference type",{exact:true}).selectOption("external");await editor.getByLabel("Published reference ID · external learning key",{exact:true}).fill("original-practice");await editor.getByLabel("Criterion credits or hours",{exact:true}).fill("2");await editor.getByRole("button",{name:"Add criterion",exact:true}).click();const second=editor.getByRole("group",{name:"Requirement 2",exact:true});await expect(second.getByLabel("Required criterion",{exact:true})).not.toBeChecked();await second.getByLabel("Reference type",{exact:true}).selectOption("external");await second.getByLabel("Published reference ID · external learning key",{exact:true}).fill("alternative-practice");
  await action("learning_save_award",()=>editor.getByRole("button",{name:"Save program draft",exact:true}).click());const row=page.getByRole("region",{name:"Programs",exact:true}).locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await expect(row.getByRole("button",{name:"Publish program",exact:true})).toBeEnabled();await action("learning_publish_collection",()=>row.getByRole("button",{name:"Publish program",exact:true}).click());await expect(row).toContainText("Version 1");
  data(f.call("admin","learning_set_award_assessor",{collectionId:"ui-award-rules",assessorId:"assessor",enabled:true}));await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"Programs",exact:true}).click();const card=page.locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await action("learning_enroll_award",()=>card.getByRole("button",{name:"Enroll in award",exact:true}).click());await expect(page.getByRole("region",{name:"Programs",exact:true})).toContainText("Complete one configured criterion");await expect(page.locator('img[src="x"]')).toHaveCount(0);
  const e=f.db.prepare("SELECT * FROM award_enrollments WHERE award_id='ui-award-rules' AND learner='learner-a'").get()!,record=data(f.call("learner-a","human_submit_external_record",{awardEnrollmentId:e.id,criterionPath:"criterion-1",amount:2,evidence:"Original confirmed two-point practice",confirmed:true},"human"));expect(f.db.prepare("SELECT certificate_id FROM award_enrollments WHERE id=?").get(e.id)!.certificate_id).toBe(null);
  data(f.call("assessor","learning_assess_external_record",{recordId:record.recordId,accepted:true,reason:"Original scoped review"}));await page.reload();await page.getByRole("button",{name:"Programs",exact:true}).click();await expect(page.getByRole("button",{name:"Award certificate",exact:true})).toBeVisible();await page.getByRole("button",{name:"Award certificate",exact:true}).click();const certificate=page.getByRole("region",{name:"Award completion certificate",exact:true});await expect(certificate).toContainText("2 "+plural+" earned");await expect(certificate.locator("img")).toHaveCount(0);expect(f.db.prepare("SELECT completed_at FROM award_enrollments WHERE id=?").get(e.id)!.completed_at).toBeTruthy();
  const download=certificate.getByRole("link",{name:"Download award certificate",exact:true});const href=await download.getAttribute("href");expect(decodeURIComponent(href!.split(",")[1])).toContain("Earned 2 "+plural);await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(certificate).toContainText(plural);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/original-one-criterion-award.png",fullPage:true});console.log("AWARD RULE ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
