import {test,expect} from "@playwright/test";
import {mismatchedCourseOpening} from "../award-course-opening-fixture.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("actual EN/VI award shows pinned course version and rejects mismatched old completion without changing history",async({page})=>{
 test.setTimeout(90000);const f=mismatchedCourseOpening(),origin="http://127.0.0.1:4386",{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")}),before=JSON.stringify(f.db.prepare("SELECT * FROM enrollments ORDER BY id").all());
 try{await app.listen({port:4386,host:"127.0.0.1"});await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill("learner-a");await page.getByLabel("Password",{exact:true}).fill("learner-a-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();await page.getByRole("button",{name:"Programs",exact:true}).click();await expect(page.getByRole("region",{name:"Programs",exact:true})).toContainText("learning-vi · Version 2");
 await page.getByLabel("Interface language",{exact:true}).selectOption("vi");const programs=page.getByRole("region",{name:"Chương trình",exact:true});await expect(programs).toContainText("learning-vi · Phiên bản 2");const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName==="learning_enroll_award_course");await programs.getByRole("button",{name:"Học khóa học cho chương trình chứng chỉ này",exact:true}).click();const result=await(await response).json();expect(result.ok).toBe(false);expect(result.error.code).toBe("FORBIDDEN");await expect(page.getByRole("alert")).toContainText("Phiên bản khóa học hiện có khác");await expect(programs).toBeVisible();expect(JSON.stringify(f.db.prepare("SELECT * FROM enrollments ORDER BY id").all())).toBe(before);expect(f.db.prepare("SELECT certificate_id FROM award_enrollments WHERE id=?").get(f.e.awardEnrollmentId)!.certificate_id).toBeNull();
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
