import {test,expect} from "@playwright/test";
import {shareFixture} from "../collection-sharing-fixture.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("source admin offers literal original rules, addressed other-tenant admin reviews local references and creates only a private draft in real EN/VI browser",async({page})=>{
 test.setTimeout(90000);const f=shareFixture(),origin="http://127.0.0.1:4373",{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();await page.getByRole("button",{name:"Administration",exact:true}).click();}
 async function action(tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName===tool);await click();const result=await(await response).json();expect(result.ok,tool+" "+JSON.stringify(result.error)).toBe(true);}
 try{
  await app.listen({port:4373,host:"127.0.0.1"});await login("admin");const region=page.getByRole("region",{name:"Original collection sharing",exact:true}),form=region.getByRole("form",{name:"Offer original collection configuration",exact:true});
  await form.getByLabel("Own published collection ID",{exact:true}).fill("share-source-award");await form.getByLabel("Reviewed source collection version",{exact:true}).fill("1");await form.getByLabel("Destination tenant ID",{exact:true}).fill("other");await form.getByLabel("Explicit destination administrator ID",{exact:true}).fill("receiver");await form.getByLabel("New destination collection ID",{exact:true}).fill("share-receiver-award");const send=form.getByRole("button",{name:"Offer original configuration for review",exact:true});await expect(send).toBeDisabled();await form.getByLabel("I authorize offering only this original configuration to this administrator.",{exact:true}).check();await action("human_offer_original_collection",()=>send.click());await region.getByLabel("Own collection offer direction",{exact:true}).selectOption("outgoing");await expect(region).toContainText("share-receiver-award");expect(f.db.prepare("SELECT 1 FROM collections WHERE id='share-receiver-award'").get()).toBe(undefined);
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("receiver");const review=page.getByRole("form",{name:"Review original collection copy",exact:true});await expect(review).toContainText(f.award.title);await expect(page.locator('img[src="x"]')).toHaveCount(0);await review.getByLabel("Authorized local reference ID",{exact:true}).fill("share-local-course");await review.getByLabel("Reviewed local reference version",{exact:true}).fill("1");const copy=review.getByRole("button",{name:"Create reviewed original collection draft",exact:true});await expect(copy).toBeDisabled();await review.getByLabel("I reviewed this original definition and the local reference rights.",{exact:true}).check();await action("human_accept_original_collection_offer",()=>copy.click());await expect(review).toHaveCount(0);
  const row=f.db.prepare("SELECT * FROM collections WHERE id='share-receiver-award'").get()!;expect(row.tenant).toBe("other");expect(row.state).toBe("draft");expect(row.latest_version).toBe(0);expect(JSON.parse(row.draft as string).access).toBe("author");expect(JSON.parse(row.draft as string).requirements[0].alternatives[0].id).toBe("share-local-course");expect(f.db.prepare("SELECT count(*) n FROM award_assessors").get()!.n).toBe(0);expect(f.db.prepare("SELECT count(*) n FROM enrollments").get()!.n).toBe(0);
  await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByRole("region",{name:"Chia sẻ cấu hình chương trình gốc",exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/original-two-tenant-collection-review.png",fullPage:true});
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
