import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author publishes a group playlist and bank, pins quiz reuse without rewriting enrolled history, and current learners lose discovery when removed from the group",async({page})=>{
 test.setTimeout(120000);const f=fixture(),origin="http://127.0.0.1:4358",group={name:"Original UI collection audience",kind:"static",mode:"ALL",memberIds:["learner-a","admin"],rules:[]};
 data(f.call("admin","learning_save_group",{groupId:"ui-collection-group",group}));data(f.call("editor","learning_create_course",{courseId:"ui-collection-source",course:{...structuredClone(courses["systems-basics"]),title:"Original group quiz source",access:"groups",groupIds:["ui-collection-group"]}}));data(f.call("editor","learning_publish_course",{courseId:"ui-collection-source"}));data(f.call("learner-a","learning_enroll",{courseId:"ui-collection-source"}));const before=f.db.prepare("SELECT * FROM enrollments").all();
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 try{
  await app.listen({port:4358,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();
  const form=page.getByRole("form",{name:"Program editor",exact:true});await form.getByLabel("Collection ID",{exact:true}).fill("ui-group-playlist");await form.getByLabel("Collection type",{exact:true}).selectOption("playlist");await form.getByLabel("Program title",{exact:true}).fill("Original UI group playlist");await form.getByLabel("Access",{exact:true}).selectOption("groups");await form.getByLabel("Audience group IDs",{exact:true}).fill("ui-collection-group");await form.getByLabel("Published reference ID · external learning key",{exact:true}).fill("ui-collection-source");await form.getByRole("button",{name:"Save program draft",exact:true}).click();
  const row=page.getByRole("region",{name:"Programs",exact:true}).locator(".learning-row").filter({has:page.getByRole("heading",{name:"Original UI group playlist",exact:true})});await expect(row).toBeVisible();await row.getByRole("button",{name:"Publish program",exact:true}).click();await expect(row).toContainText("Version 1");
  const banks=page.getByRole("region",{name:"Reusable question banks",exact:true}),publish=banks.getByRole("form",{name:"Publish question bank",exact:true});await publish.getByLabel("Question bank ID",{exact:true}).fill("ui-group-bank");await publish.getByLabel("Question bank title",{exact:true}).fill("Original UI group bank");await publish.getByLabel("Bank source course ID",{exact:true}).fill("ui-collection-source");await publish.getByLabel("Question bank audience",{exact:true}).selectOption("groups");await publish.getByLabel("Audience group IDs",{exact:true}).fill("ui-collection-group");await publish.getByRole("button",{name:"Publish bank version",exact:true}).click();await expect(banks.getByRole("status")).toContainText("Bank version published");
  const bankRow=banks.locator("article").filter({has:page.getByRole("heading",{name:"Original UI group bank",exact:true})});await bankRow.getByRole("button",{name:"Choose bank questions",exact:true}).click();const apply=banks.getByRole("form",{name:"Apply question bank",exact:true});await apply.getByLabel("Bank target course ID",{exact:true}).fill("ui-collection-source");await apply.getByRole("button",{name:"Apply selected bank version",exact:true}).click();await expect(banks.getByRole("status")).toContainText("Reopen the target course draft");
  const courseRow=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:"Original group quiz source",exact:true})});await courseRow.getByRole("button",{name:"Publish",exact:true}).click();await expect(courseRow).toContainText("Published version 2");expect(f.db.prepare("SELECT * FROM enrollments").all()).toEqual(before);const pinned=JSON.parse(f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-collection-source' AND version=2").get()!.content as string);expect(pinned.quiz.questionBankRef.bankId).toBe("ui-group-bank");expect(pinned.groupIds).toEqual(["ui-collection-group"]);
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByLabel("ID nhóm được xem nội dung",{exact:true})).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/collection-bank-group-audience.png",fullPage:true});await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"Programs",exact:true}).click();await expect(page.getByRole("heading",{name:"Original UI group playlist",exact:true})).toBeVisible();data(f.call("admin","learning_save_group",{groupId:"ui-collection-group",group:{...group,memberIds:["admin"]}}));await page.reload();await page.getByRole("button",{name:"Programs",exact:true}).click();await expect(page.getByRole("heading",{name:"Original UI group playlist",exact:true})).toHaveCount(0);expect(f.db.prepare("SELECT * FROM enrollments").all()).toEqual(before);
  console.log("COLLECTION BANK GROUP ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
