import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author selects exact group audience in a published version, current learner discovery changes with membership and historical records remain pinned in mobile EN/VI",async({page})=>{
 test.setTimeout(120000);const f=fixture(),origin="http://127.0.0.1:4357",title="Original UI group course",group={name:"Original UI audience",kind:"static",mode:"ALL",memberIds:["learner-a"],rules:[]};
 data(f.call("admin","learning_save_group",{groupId:"ui-group",group}));data(f.call("editor","learning_create_course",{courseId:"ui-group-course",course:{...structuredClone(courses["systems-basics"]),title}}));data(f.call("editor","learning_publish_course",{courseId:"ui-group-course"}));
 const oldVersion=f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-group-course' AND version=1").get()!.content,{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 async function search(){await page.getByLabel("Search courses",{exact:true}).fill(title);await page.locator("form.filters").getByRole("button",{name:"Search",exact:true}).click();}
 try{
  await app.listen({port:4357,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();const author=page.getByRole("region",{name:"Course authoring",exact:true});await author.getByLabel("Content audience",{exact:true}).selectOption("groups");await author.getByLabel("Audience group IDs",{exact:true}).fill("ui-group");await author.getByRole("button",{name:"Save draft",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"Draft saved"})).toBeVisible();await row.getByRole("button",{name:"Publish",exact:true}).click();await expect(row).toContainText("Published version 2");
  expect(f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-group-course' AND version=1").get()!.content).toBe(oldVersion);const pinned=JSON.parse(f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-group-course' AND version=2").get()!.content as string);expect(pinned.access).toBe("groups");expect(pinned.groupIds).toEqual(["ui-group"]);
  await row.getByRole("button",{name:"Edit draft",exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByLabel("ID nhóm được xem nội dung",{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/group-content-audience.png",fullPage:true});await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-b");await search();await expect(page.locator(".cards article").filter({has:page.getByRole("heading",{name:title,exact:true})})).toHaveCount(0);
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await search();const card=page.locator(".cards article").filter({has:page.getByRole("heading",{name:title,exact:true})});await expect(card).toBeVisible();const [enrolled]=await Promise.all([page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().method()==="POST"&&response.request().postDataJSON()?.toolName==="learning_enroll"),card.getByRole("button",{name:"Enroll",exact:true}).click()]);expect(enrolled.status()).toBe(200);expect((await enrolled.json()).ok).toBe(true);await expect(page.getByRole("button",{name:"My learning",exact:true})).toHaveAttribute("aria-current","page");
  const records=f.db.prepare("SELECT * FROM enrollments WHERE course_id='ui-group-course'").all();expect(records.length).toBe(1);expect(records[0].version).toBe(2);data(f.call("admin","learning_save_group",{groupId:"ui-group",group:{...group,memberIds:[]}}));await page.getByRole("button",{name:"Explore",exact:true}).click();await search();await expect(card).toHaveCount(0);expect(f.db.prepare("SELECT * FROM enrollments WHERE course_id='ui-group-course'").all()).toEqual(records);
  console.log("GROUP AUDIENCE ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
