import {test, expect} from '@playwright/test';
import {createServer} from 'node:http';
import {resolve} from 'node:path';
import {createApp} from '../../src/server/app.ts';
import {openDatabase} from '../../src/server/database.ts';
import {startIdentityFixture} from '../identity-fixture.ts';

test('admin reviews and sends an invitation; wrong identity fails, exact SSO redeems once and revoked links stay closed', async ({page}) => {
  test.setTimeout(60000);
  const origin = 'http://127.0.0.1:4317', db = openDatabase(':memory:', true), provider = await startIdentityFixture(origin + '/api/auth/callback');
  db.prepare('INSERT INTO identity_links VALUES(?,?,?,?,?)').run('demo', provider.config.issuer, 'admin-subject', 'admin', new Date().toISOString());
  provider.controls.subject = 'admin-subject';
  const messages: any[] = [], mail = createServer(async (req, res) => {let body = ''; for await (const part of req) body += part; messages.push(JSON.parse(body)); res.writeHead(202); res.end();});
  await new Promise<void>(resolve => mail.listen(0, '127.0.0.1', resolve));
  const {app} = await createApp({db, origin, oidc: provider.config, identityFixture: true, staticRoot: resolve('dist'), invitationMail: {url: 'http://127.0.0.1:' + (mail.address() as any).port, token: 'browser-fixture-mail-token'}});
  try {
    await app.listen({port: 4317, host: '127.0.0.1'});
    await page.setViewportSize({width: 768, height: 1024});
    await page.goto(origin); await page.getByRole('button', {name: 'Continue with organization SSO', exact: true}).click();
    await expect(page.getByRole('button', {name: 'Sign out', exact: true})).toBeVisible();
    await page.getByRole('button', {name: 'Administration', exact: true}).click();
    const invitations = page.getByRole('region', {name: 'User invitations', exact: true});
    await invitations.getByLabel('Invited account ID', {exact: true}).fill('learner-a');
    await invitations.getByLabel('Invited issuer subject', {exact: true}).fill('invited-subject');
    await invitations.getByLabel('Invitation email', {exact: true}).fill('original@example.test');
    await invitations.getByLabel('Invitation review reason', {exact: true}).fill('Original fixture reviewed in browser');
    await invitations.getByRole('button', {name: 'Create reviewed invitation', exact: true}).click();
    await expect(invitations.getByRole('status')).toHaveText('Invitation saved.');
    const url = await invitations.getByRole('link', {name: 'Invitation link', exact: true}).getAttribute('href');
    expect(db.prepare('SELECT COUNT(*) n FROM identity_links WHERE user_id=\'learner-a\'').get()!.n).toBe(0);
    page.once('dialog', d => d.accept());
    await invitations.getByRole('button', {name: 'Send welcome email', exact: true}).click();
    await expect(invitations.getByRole('status')).toHaveText('Email accepted by transport; recipient delivery is not verified.');
    expect(messages).toHaveLength(1); expect(messages[0].url).toBe(url);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    const description = await page.evaluate(() => window.agentBridgeV1!.describe()); expect(description.tools.some(t => /invitation/.test(t.name))).toBe(false);
    await page.getByRole('button', {name: 'Sign out', exact: true}).click();
    provider.controls.subject = 'wrong-subject'; await page.goto(url!);
    await page.getByRole('button', {name: 'Continue with organization SSO', exact: true}).click();
    await expect(page.locator('body')).toContainText('Organization sign-in failed');
    expect(db.prepare('SELECT COUNT(*) n FROM identity_links WHERE user_id=\'learner-a\'').get()!.n).toBe(0);
    provider.controls.subject = 'invited-subject'; await page.goto(url!);
    await page.getByRole('button', {name: 'Continue with organization SSO', exact: true}).click();
    await expect(page.getByRole('button', {name: 'Sign out', exact: true})).toBeVisible();
    await expect(page.getByRole('button', {name: 'Administration', exact: true})).toHaveCount(0);
    expect(await page.evaluate(async () => (await (await fetch('/api/session')).json()).principal.id)).toBe('learner-a');
    expect(db.prepare('SELECT state FROM user_invitations').get()!.state).toBe('accepted');
    await page.goto(url!);
    await page.getByRole('button', {name: 'Accept invitation with organization SSO', exact: true}).click();
    await expect(page.getByRole('alert')).toContainText('Organization sign-in unavailable');
    await page.getByRole('button', {name: 'Sign out', exact: true}).click();
    provider.controls.subject = 'admin-subject'; await page.goto(origin);
    await page.getByRole('button', {name: 'Continue with organization SSO', exact: true}).click();
    await page.getByRole('button', {name: 'Administration', exact: true}).click();
    await invitations.getByLabel('Invited account ID', {exact: true}).fill('learner-b');
    await invitations.getByLabel('Invited issuer subject', {exact: true}).fill('revoked-subject');
    await invitations.getByLabel('Invitation email', {exact: true}).fill('revoked@example.test');
    await invitations.getByLabel('Invitation review reason', {exact: true}).fill('Revoke original fixture');
    await invitations.getByRole('button', {name: 'Create reviewed invitation', exact: true}).click();
    const revokedURL = await invitations.getByRole('link', {name: 'Invitation link', exact: true}).getAttribute('href');
    await page.getByLabel('Interface language',{exact:true}).selectOption('vi');
    const vi=page.getByRole('region',{name:'Lời mời người dùng',exact:true});
    await vi.getByRole('checkbox',{name:'Chọn lời mời revoked@example.test',exact:true}).check();
    page.once('dialog',d=>{expect(d.message()).toContain('revoked@example.test');return d.dismiss();});
    await vi.getByRole('button',{name:'Gửi email chào mừng đã chọn (1)',exact:true}).click();
    expect(messages).toHaveLength(1);
    page.once('dialog',d=>d.accept());
    await vi.getByRole('button',{name:'Gửi email chào mừng đã chọn (1)',exact:true}).click();
    await expect(vi.getByRole('status')).toContainText('1 đã được dịch vụ gửi tiếp nhận, 0 gửi thất bại');
    expect(messages).toHaveLength(2);expect(messages[1].url).toBe(revokedURL);
    await page.getByLabel('Ngôn ngữ giao diện',{exact:true}).selectOption('en');

    await invitations.getByRole('button', {name: 'Revoke invitation', exact: true}).click();
    await expect(invitations.getByRole('link', {name: 'Invitation link', exact: true})).toHaveCount(0);
    await page.getByRole('button', {name: 'Sign out', exact: true}).click(); provider.controls.subject = 'revoked-subject'; await page.goto(revokedURL!);
    await page.getByRole('button', {name: 'Continue with organization SSO', exact: true}).click();
    await expect(page.getByRole('alert')).toContainText('Organization sign-in unavailable');
    expect(db.prepare('SELECT COUNT(*) n FROM identity_links WHERE user_id=\'learner-b\'').get()!.n).toBe(0);
  } finally {await page.close(); app.server.closeAllConnections(); await app.close(); await provider.close(); await new Promise<void>(resolve => {mail.close(() => resolve()); mail.closeAllConnections();}); db.close();}
});
