import {test,expect} from "@playwright/test";
import {itemRetakeFixture} from "../item-retake-fixture.ts";
import {data} from "../helpers.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("actual EN human chooses fresh same-version reading; VI separate confirmation supplies new later-cycle proof while original reading stays immutable",async({page})=>{
 test.setTimeout(90000);const f=itemRetakeFixture(),now=Date.now(),start=new Date(now-1000).toISOString();f.db.prepare("UPDATE item_enrollments SET completed_at=? WHERE id=?").run(new Date(now-2000).toISOString(),f.item.itemEnrollmentId);const old=f.db.prepare("SELECT * FROM item_enrollments WHERE id=?").get(f.item.itemEnrollmentId);
 const plan={title:"Original later browser reading",targetKind:"award",targetId:"item-award",audienceKind:"individuals",learnerIds:["learner-a"],groupId:"",membership:"fixed",startsAt:start,repeatDays:0,endAt:null,dueKind:"none",fixedDueAt:null,rollingDays:0};data(f.call("manager","learning_save_assignment_plan",{planId:"browser-retake",plan,reason:"Original browser cycle"}));f.service.assignments.runBackground(start);const cycle=f.db.prepare("SELECT e.* FROM award_enrollments e JOIN assignment_cycles c ON c.id=e.assignment_cycle_id WHERE c.plan_id='browser-retake'").get()!;
 const origin="http://127.0.0.1:4385",{app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function write(tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName===tool);await click();const result=await(await response).json();expect(result.ok,JSON.stringify(result.error)).toBe(true);}
 try{
  await app.listen({port:4385,host:"127.0.0.1"});await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill("learner-a");await page.getByLabel("Password",{exact:true}).fill("learner-a-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();await page.getByRole("button",{name:"My learning",exact:true}).click();
  const form=page.getByRole("form",{name:"Fresh standalone reading",exact:true}),fresh=form.getByRole("button",{name:"Start fresh standalone reading",exact:true});await expect(form).toContainText("Prior confirmed reading remains in history");await expect(fresh).toBeDisabled();await form.getByLabel("I choose to study this same standalone version again in a fresh record.",{exact:true}).check();await write("human_retake_completed_item",()=>fresh.click());
  const reader=page.getByRole("region",{name:"Standalone item reader",exact:true});await expect(reader).toContainText("Original learner-confirmed standalone reading.");const next=f.db.prepare("SELECT * FROM item_enrollments WHERE retake_of=?").get(f.item.itemEnrollmentId)!;expect(next.completed_at).toBeNull();expect(next.version).toBe(1);expect(f.db.prepare("SELECT completed_at FROM award_enrollments WHERE id=?").get(cycle.id)!.completed_at).toBeNull();expect(f.db.prepare("SELECT * FROM item_enrollments WHERE id=?").get(f.item.itemEnrollmentId)).toEqual(old);
  await page.getByLabel("Interface language",{exact:true}).selectOption("vi");const vi=page.getByRole("region",{name:"Trình đọc nội dung độc lập",exact:true}),confirm=vi.getByRole("button",{name:"Xác nhận đã đọc nội dung độc lập",exact:true});await expect(confirm).toBeDisabled();await vi.getByLabel("Tôi xác nhận đã học phiên bản nội dung độc lập này.",{exact:true}).check();await write("human_complete_item",()=>confirm.click());await expect(confirm).toHaveCount(0);await expect(vi).toContainText("Đã xác nhận học");expect(f.db.prepare("SELECT certificate_id FROM award_enrollments WHERE id=?").get(cycle.id)!.certificate_id).toBeTruthy();expect(f.db.prepare("SELECT * FROM item_enrollments WHERE id=?").get(f.item.itemEnrollmentId)).toEqual(old);expect(f.db.prepare("SELECT count(*) n FROM attempts").get()!.n).toBe(0);expect(f.db.prepare("SELECT count(*) n FROM learning_notifications WHERE cycle_id=? AND kind='completed'").get(cycle.assignment_cycle_id)!.n).toBe(1);
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
