import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("human author chooses actual child quantity; player shows real partial credit with EN/VI original labels",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4368";
 const child={title:"Original UI child",summary:"Original",access:"tenant",unit:"credits",target:4,ongoing:false,moderatedExternal:true,requirements:[{id:"practice",title:"Practice",required:true,credits:4,alternatives:[{kind:"external",id:"practice-proof"}]}]};
 data(f.call("editor","learning_save_award",{collectionId:"ui-credit-child",award:child}));data(f.call("editor","learning_publish_collection",{collectionId:"ui-credit-child"}));
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 async function action(tool:string,click:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName===tool);await click();expect((await(await response).json()).ok).toBe(true);}
 try{
  await app.listen({port:4368,host:"127.0.0.1"});await login("admin");await page.getByRole("button",{name:"Administration",exact:true}).click();const form=page.getByRole("form",{name:"Program editor",exact:true});
  await form.getByLabel("Collection ID",{exact:true}).fill("ui-credit-root");await form.getByLabel("Program title",{exact:true}).fill("Original UI root");await form.getByLabel("Credit unit",{exact:true}).selectOption("credits");await form.getByLabel("Target",{exact:true}).fill("3");await form.getByLabel("Criterion credit calculation",{exact:true}).selectOption("nested_earned");await expect(form.getByLabel("Criterion credits or hours",{exact:true})).toBeDisabled();await form.getByLabel("Reference type",{exact:true}).selectOption("award");await form.getByLabel("Published reference ID · external learning key",{exact:true}).fill("ui-credit-child");
  await action("learning_save_award",()=>form.getByRole("button",{name:"Save program draft",exact:true}).click());const row=page.locator(".learning-row").filter({has:page.getByRole("heading",{name:"Original UI root",exact:true})});await action("learning_publish_collection",()=>row.getByRole("button",{name:"Publish program",exact:true}).click());await expect(row).toContainText("Version 1");
  data(f.call("admin","learning_set_award_assessor",{collectionId:"ui-credit-root",assessorId:"assessor",enabled:true}));await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"Programs",exact:true}).click();const card=page.locator(".learning-row").filter({has:page.getByRole("heading",{name:"Original UI root",exact:true})});await action("learning_enroll_award",()=>card.getByRole("button",{name:"Enroll in award",exact:true}).click());
  const e=f.db.prepare("SELECT id FROM award_enrollments WHERE award_id='ui-credit-root' AND learner='learner-a'").get()!,record=data(f.call("learner-a","human_submit_external_record",{awardEnrollmentId:e.id,criterionPath:"criterion-1/ui-credit-child@1/practice",amount:2,evidence:"Original partial child practice",confirmed:true},"human"));data(f.call("assessor","learning_assess_external_record",{recordId:record.recordId,accepted:true,reason:"Human verification"}));
  await page.reload();await page.getByRole("button",{name:"Programs",exact:true}).click();const region=page.getByRole("region",{name:"Programs",exact:true});await expect(region).toContainText("Actual earned child award credits");await expect(region).toContainText("2 / 4");expect(f.db.prepare("SELECT certificate_id FROM award_enrollments WHERE id=?").get(e.id)!.certificate_id).toBe(null);
  await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByRole("region",{name:"Chương trình",exact:true})).toContainText("Tín chỉ thực tế đạt được từ chương trình con");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/actual-child-award-credits.png",fullPage:true});
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
