import {test,expect} from "@playwright/test";
import {fixture} from "../helpers.ts";
import {createApp} from "../../src/server/app.ts";
import {IntegrationCredentials} from "../../src/server/integration-credentials.ts";
import {ProviderCatalogService,type ProviderAdapter} from "../../src/server/provider-catalog.ts";
import {randomUUID} from "node:crypto";
import {resolve} from "node:path";
test("admin explicitly reviews configured provider rights, issues only selected catalog scopes and disables current learner access without losing history",async({page})=>{
 test.setTimeout(120000);const f=fixture(),origin="http://127.0.0.1:4356",issued=new IntegrationCredentials(f.db).mutate(f.service.principal("admin"),{action:"issue",name:"Configured synthetic provider",reason:"Fixture only",scopes:["catalog.read","catalog.write"],ttlDays:1,key:randomUUID(),revision:0}),policy:ProviderAdapter={id:"fixture-provider",tenant:"demo",clientId:issued.id,licenseUntil:new Date(Date.now()+86400000).toISOString(),metadataForModels:false,launchOrigin:"https://provider-fixture.invalid"},feed=new ProviderCatalogService(f.db,[policy]);
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,catalogFixture:true,catalogAdapters:[policy],staticRoot:resolve("dist")});
 let sequence=0;const event=(action:string,data:any)=>feed.write("Bearer "+issued.token,policy.id,{profile:"pear-provider-metadata/1",id:randomUUID(),sequence:++sequence,sourceTime:new Date().toISOString(),action,data});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 try{
  await app.listen({port:4356,host:"127.0.0.1"});await login("admin");await page.getByRole("button",{name:"Administration",exact:true}).click();const review=page.getByRole("region",{name:"Reviewed provider connections",exact:true});await expect(review).toContainText("Disabled or awaiting review");await expect(review).toContainText("Human metadata only");const approve=review.getByRole("button",{name:"Approve configured provider connection",exact:true});await expect(approve).toBeDisabled();
  await review.getByLabel("Provider review reason",{exact:true}).fill("Synthetic provider contract review");await review.getByLabel("I confirm reviewing provider content and metadata rights",{exact:true}).check();await approve.click();await expect(review.getByText("Approved",{exact:true})).toBeVisible();
  event("upsert",{sourceId:"synthetic-source",version:1,title:"Reviewed synthetic metadata",summary:"No licensed body",language:"en",topic:"Reliability",intendedMinutes:15});event("grant",{sourceId:"synthetic-source",learnerId:"learner-a",validUntil:new Date(Date.now()+3600000).toISOString()});
  const clients=page.getByRole("region",{name:"Provisioning credentials",exact:true});await expect(clients.getByLabel("Allow provisioning writes",{exact:true})).toBeDisabled();await clients.getByLabel("Provisioning client name",{exact:true}).fill("Only catalog scopes");await clients.getByLabel("Provisioning review reason",{exact:true}).fill("Synthetic catalog credential review");await clients.getByLabel("Allow provider metadata and entitlement feed writes",{exact:true}).check();await clients.getByRole("button",{name:"Issue reviewed credential",exact:true}).click();await expect(clients.getByTestId("provisioning-secret")).toBeVisible();const row=f.db.prepare("SELECT scopes FROM integration_clients WHERE name='Only catalog scopes'").get()!;expect(JSON.parse(row.scopes as string)).toEqual(["catalog.read","catalog.write"]);await clients.getByRole("button",{name:"Hide provisioning secret",exact:true}).click();
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");const content=page.getByRole("region",{name:"Provider content",exact:true});await expect(content).toContainText("Reviewed synthetic metadata");await content.getByRole("button",{name:"Review provider item",exact:true}).click();await content.getByLabel("I confirm creating my provider launch record",{exact:true}).check();await content.getByRole("button",{name:"Create provider launch",exact:true}).click();await expect(content.getByRole("link",{name:"Open provider content in a new tab",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("admin");await page.getByRole("button",{name:"Administration",exact:true}).click();await review.getByLabel("Provider review reason",{exact:true}).fill("Disable synthetic connection");await review.getByLabel("I confirm reviewing provider content and metadata rights",{exact:true}).check();await review.getByRole("button",{name:"Disable provider connection",exact:true}).click();await expect(review).toContainText("Disabled or awaiting review");
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByRole("heading",{name:"Kết nối nhà cung cấp đã duyệt",exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/provider-review-settings.png",fullPage:true});await page.getByLabel("Interface language",{exact:true}).selectOption("en");await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await expect(content).toContainText("No currently entitled provider content is available.");await expect(content.getByRole("list")).toContainText("Provider metadata unavailable");expect(f.db.prepare("SELECT COUNT(*) AS n FROM provider_launches").get()!.n).toBe(1);expect(f.db.prepare("SELECT COUNT(*) AS n FROM enrollments").get()!.n).toBe(0);
  console.log("PROVIDER REVIEW ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
