
import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author title/format toolbar publishes safe original bold/italic/underline/lists; learner and unsaved preview render same text in EN/VI without HTML execution",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4365",title="Original titled formatting",questionTitle="Original question <b>literal title</b>",prompt="**Original bold** and *original italic* and __original underline__\n\n- Original bullet\n- Second bullet\n\n1. Original numbered\n2. Second numbered\n\n<img src=x onerror=alert(1)>";
 const course={...structuredClone(courses["learning-vi"]),title,language:"en",quiz:{passScore:100,maxAttempts:2,questions:[{id:"formatted",prompt:"Original bold",options:["Original right","Original wrong"],correct:0}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-formatted-question",course}));data(f.call("editor","learning_publish_course",{courseId:"ui-formatted-question"}));const pin=f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-formatted-question' AND version=1").get()!.content;
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 const write=(tool:string)=>page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().postDataJSON()?.toolName===tool);
 async function action(tool:string,click:()=>Promise<void>){const response=write(tool);await click();expect((await(await response).json()).ok).toBe(true);}
 try{
  await app.listen({port:4365,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();const editor=page.getByRole("region",{name:"Course authoring",exact:true}),q=editor.getByRole("group",{name:"Question 1",exact:true});
  await expect(q.getByLabel("Optional question title",{exact:true})).toHaveAttribute("maxlength","255");await q.getByLabel("Optional question title",{exact:true}).fill(questionTitle);await q.getByLabel("Question prompt formatting",{exact:true}).selectOption("original_markup");const field=q.getByLabel("First quiz question",{exact:true});await field.evaluate((input:HTMLTextAreaElement)=>{input.focus();input.setSelectionRange(0,input.value.length);});await q.getByRole("button",{name:"Bold",exact:true}).click();await expect(field).toHaveValue("**Original bold**");await field.fill(prompt);
  await editor.getByRole("button",{name:"Preview draft",exact:true}).click();const preview=editor.getByRole("region",{name:"Interactive quiz preview",exact:true});await expect(preview.locator("strong")).toHaveText("Original bold");await expect(preview.locator("em")).toHaveText("original italic");await expect(preview.locator("u")).toHaveText("original underline");await expect(preview.locator("img")).toHaveCount(0);
  await action("learning_update_course",()=>editor.getByRole("button",{name:"Save draft",exact:true}).click());await expect(row.getByRole("button",{name:"Publish",exact:true})).toBeEnabled();await action("learning_publish_course",()=>row.getByRole("button",{name:"Publish",exact:true}).click());await expect(row).toContainText("Published version 2");expect(f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-formatted-question' AND version=1").get()!.content).toBe(pin);
  const e=data(f.call("learner-a","learning_enroll",{courseId:"ui-formatted-question"}));for(const lesson of course.lessons)data(f.call("learner-a","human_complete_lesson",{enrollmentId:e.enrollmentId,lessonId:lesson.id},"human"));
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();await page.locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})}).getByRole("button",{name:"Continue learning",exact:true}).click();await page.getByRole("button",{name:"Start assessment",exact:true}).click();
  const player=page.getByRole("group",{name:questionTitle+" · 1 points",exact:true});await expect(player.locator("strong")).toHaveText("Original bold");await expect(player.locator("em")).toHaveText("original italic");await expect(player.locator("u")).toHaveText("original underline");await expect(player.locator("ul li")).toHaveText(["Original bullet","Second bullet"]);await expect(player.locator("ol li")).toHaveText(["Original numbered","Second numbered"]);await expect(player.locator("img,b,script,a")).toHaveCount(0);await expect(player).toContainText("<img src=x onerror=alert(1)>");
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(player).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/original-titled-formatted-question.png",fullPage:true});await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");
  await action("human_save_answer",()=>player.getByRole("radio",{name:"Original right",exact:true}).check());await expect(page.getByRole("button",{name:"Confirm and submit my answers",exact:true})).toBeEnabled();await action("human_submit_attempt",()=>page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click());await expect(player.getByRole("radio",{name:"Original right",exact:true})).toBeDisabled();const at=f.db.prepare("SELECT * FROM attempts WHERE enrollment_id=?").get(e.enrollmentId)!;expect(at.score).toBe(100);const agent=data(f.call("learner-a","learning_get_attempt",{attemptId:at.id}));expect(agent.questions[0].title).toBe(questionTitle);expect(agent.questions[0].correct).toBe(undefined);expect(agent.feedback).toEqual([]);console.log("QUESTION TEXT ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
