
import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author enables objective progression; human saved checks unlock next question in EN/VI mobile without official grade until explicit submission",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4362",title="Original question progression";
 const course={...structuredClone(courses["learning-vi"]),title,language:"en",quiz:{passScore:100,maxAttempts:3,questions:[{id:"one",prompt:"Original first gated question",options:["Original correct one","Original wrong one"],correct:0},{id:"two",prompt:"Original second gated question",options:["Original correct two","Original wrong two"],correct:0}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-question-progress",course}));data(f.call("editor","learning_publish_course",{courseId:"ui-question-progress"}));
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 const write=(tool:string)=>page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().postDataJSON()?.toolName===tool);
 async function action(tool:string,click:()=>Promise<void>){const response=write(tool);await click();expect((await(await response).json()).ok).toBe(true);}
 try{
  await app.listen({port:4362,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();const editor=page.getByRole("region",{name:"Course authoring",exact:true});
  await editor.getByLabel("Require correct objective response before continuing",{exact:true}).check();await editor.getByLabel("Answer release",{exact:true}).selectOption("after_question");
  await action("learning_update_course",()=>editor.getByRole("button",{name:"Save draft",exact:true}).click());await expect(row.getByRole("button",{name:"Publish",exact:true})).toBeEnabled();await action("learning_publish_course",()=>row.getByRole("button",{name:"Publish",exact:true}).click());await expect(row).toContainText("Published version 2");
  const e=data(f.call("learner-a","learning_enroll",{courseId:"ui-question-progress"}));for(const lesson of course.lessons)data(f.call("learner-a","human_complete_lesson",{enrollmentId:e.enrollmentId,lessonId:lesson.id},"human"));
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();await page.locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})}).getByRole("button",{name:"Continue learning",exact:true}).click();await page.getByRole("button",{name:"Start assessment",exact:true}).click();
  await expect(page.getByRole("radio",{name:"Original correct one",exact:true})).toBeVisible();await expect(page.getByRole("radio",{name:"Original correct two",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"Confirm and submit my answers",exact:true})).toBeDisabled();
  await action("human_save_answer",()=>page.getByRole("radio",{name:"Original wrong one",exact:true}).check());await expect(page.getByRole("button",{name:"Check saved response",exact:true})).toBeEnabled();await action("human_check_question",()=>page.getByRole("button",{name:"Check saved response",exact:true}).click());await expect(page.getByText("Try another response",{exact:true})).toBeVisible();await expect(page.getByRole("radio",{name:"Original correct two",exact:true})).toHaveCount(0);
  await action("human_save_answer",()=>page.getByRole("radio",{name:"Original correct one",exact:true}).check());await expect(page.getByRole("button",{name:"Check saved response",exact:true})).toBeEnabled();await action("human_check_question",()=>page.getByRole("button",{name:"Check saved response",exact:true}).click());await expect(page.getByRole("radio",{name:"Original correct two",exact:true})).toBeVisible();
  const at=f.db.prepare("SELECT * FROM attempts WHERE enrollment_id=?").get(e.enrollmentId)!;expect(at.score).toBe(null);expect(at.submitted).toBe(0);expect(f.db.prepare("SELECT COUNT(*) AS n FROM certificates WHERE enrollment_id=?").get(e.enrollmentId)!.n).toBe(0);
  const second=page.getByRole("group",{name:"Original second gated question · 1 points",exact:true});await action("human_save_answer",()=>second.getByRole("radio",{name:"Original correct two",exact:true}).check());await expect(page.getByRole("button",{name:"Check saved response",exact:true}).nth(1)).toBeEnabled();
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByRole("button",{name:"Kiểm tra câu trả lời đã lưu",exact:true}).nth(1)).toBeEnabled();await action("human_check_question",()=>page.getByRole("button",{name:"Kiểm tra câu trả lời đã lưu",exact:true}).nth(1).click());await expect(page.getByText("Đã kiểm tra đúng",{exact:true})).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/question-check-original.png",fullPage:true});
  await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");await expect(page.getByRole("button",{name:"Confirm and submit my answers",exact:true})).toBeEnabled();await action("human_submit_attempt",()=>page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click());await expect(page.getByLabel("Released question results",{exact:true})).toContainText("100%");
  expect(f.db.prepare("SELECT score FROM attempts WHERE id=?").get(at.id)!.score).toBe(100);const agent=data(f.call("learner-a","learning_get_attempt",{attemptId:at.id}));expect(agent.feedback).toEqual([]);expect(agent.questionChecks).toBe(undefined);expect(agent.answers).toEqual({});console.log("QUESTION PROGRESSION ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
