import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author configures multiple-correct feedback and dropdown/free blanks; learner answers shuffled forms through human UI in EN/VI with private graded feedback",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4361",title="Original UI question forms";
 const value={...structuredClone(courses["learning-vi"]),title,language:"en",quiz:{passScore:100,maxAttempts:3,shuffleOptions:true,answerRelease:"after_submission",questions:[{id:"multi",prompt:"Select original correct choices",options:["Alpha","Beta","Gamma","Delta"],correct:0},{id:"blanks",kind:"blanks",prompt:"Choose a city and write a word",options:[],correct:0,prompts:["Original city","Original word"],correctAnswers:["Paris","Áp dụng"]}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-question-forms",course:value}));data(f.call("editor","learning_publish_course",{courseId:"ui-question-forms"}));const before=f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-question-forms' AND version=1").get()!.content;
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 const write=(tool:string)=>page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().postDataJSON()?.toolName===tool);
 try{
  await app.listen({port:4361,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();const editor=page.getByRole("region",{name:"Course authoring",exact:true}),one=editor.getByRole("group",{name:"Question 1",exact:true}),two=editor.getByRole("group",{name:"Question 2",exact:true});
  await one.getByLabel("Multiple correct choices",{exact:true}).check();await one.getByLabel("Correct choice C",{exact:true}).check();await one.getByLabel("Allow partial choice credit",{exact:true}).check();await one.getByLabel("Add option feedback",{exact:true}).check();await one.getByRole("group",{name:"Option feedback A",exact:true}).getByLabel("Feedback when selected",{exact:true}).fill("Original Alpha chosen feedback");await one.getByRole("group",{name:"Option feedback C",exact:true}).getByLabel("Feedback when not selected",{exact:true}).fill("Original Gamma missing feedback");
  await two.getByLabel("Use dropdown blank 1",{exact:true}).check();await two.getByLabel("Dropdown choices, one per line 1",{exact:true}).fill("Paris\nLondon\nBerlin");
  let response=write("learning_update_course");await editor.getByRole("button",{name:"Save draft",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(row.getByRole("button",{name:"Publish",exact:true})).toBeEnabled();response=write("learning_publish_course");await row.getByRole("button",{name:"Publish",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(row).toContainText("Published version 2");expect(f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-question-forms' AND version=1").get()!.content).toBe(before);
  const published=JSON.parse(f.db.prepare("SELECT content FROM course_versions WHERE course_id=\'ui-question-forms\' AND version=2").get()!.content as string);expect(published.quiz.questions[0].feedbackSelected[0]).toBe("Original Alpha chosen feedback");expect(published.quiz.questions[0].feedbackNotSelected[2]).toBe("Original Gamma missing feedback");
  const e=data(f.call("learner-a","learning_enroll",{courseId:"ui-question-forms"}));for(const lesson of value.lessons)data(f.call("learner-a","human_complete_lesson",{enrollmentId:e.enrollmentId,lessonId:lesson.id},"human"));
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();await page.locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})}).getByRole("button",{name:"Continue learning",exact:true}).click();await page.getByRole("button",{name:"Start assessment",exact:true}).click();await expect(page.getByRole("checkbox",{name:"Alpha",exact:true})).toBeVisible();
  response=write("human_save_answer");await page.getByRole("checkbox",{name:"Alpha",exact:true}).check();expect((await(await response).json()).ok).toBe(true);
  await page.getByLabel("Original city",{exact:true}).selectOption({label:"Paris"});await page.getByLabel("Original word",{exact:true}).fill("Áp dụng");response=write("human_save_answer");await page.getByRole("group",{name:"Choose a city and write a word · 1 points",exact:true}).getByRole("button",{name:"Save response",exact:true}).click();expect((await(await response).json()).ok).toBe(true);
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByRole("button",{name:"Lưu câu trả lời",exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/multi-dropdown-original-questions.png",fullPage:true});await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");
  response=write("human_submit_attempt");await page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(page.getByLabel("Released question results",{exact:true})).toContainText("50%");await expect(page.getByLabel("Released question results",{exact:true})).toContainText("100%");
  await page.getByText("Released answer feedback",{exact:true}).click();await expect(page.getByText(/Original Alpha chosen feedback/)).toBeVisible();await expect(page.getByText(/Original Gamma missing feedback/)).toBeVisible();
  const at=f.db.prepare("SELECT * FROM attempts WHERE enrollment_id=?").get(e.enrollmentId)!;expect(at.score).toBe(75);expect(at.passed).toBe(0);const agent=data(f.call("learner-a","learning_get_attempt",{attemptId:at.id}));expect(agent.feedback).toEqual([]);expect(agent.questionResults).toEqual([]);expect(JSON.stringify(agent)).not.toContain("Original Alpha chosen feedback");expect(f.db.prepare("SELECT COUNT(*) AS n FROM certificates WHERE enrollment_id=?").get(e.enrollmentId)!.n).toBe(0);console.log("QUESTION FORMS ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
