import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("human keeps pinned quiz or explicitly confirms latest objective version, preserving prior responses and identical lessons through reload EN/VI",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4369",value={...structuredClone(courses["learning-vi"]),title:"Original UI quiz upgrade",language:"en",quiz:{passScore:100,maxAttempts:2,questions:[{id:"old-question",prompt:"Original old prompt",options:["Correct","Incorrect"],correct:0}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-quiz-upgrade",course:value}));data(f.call("editor","learning_publish_course",{courseId:"ui-quiz-upgrade"}));const e=data(f.call("learner-a","learning_enroll",{courseId:"ui-quiz-upgrade"}));for(const l of value.lessons)data(f.call("learner-a","human_complete_lesson",{enrollmentId:e.enrollmentId,lessonId:l.id},"human"));const at=data(f.call("learner-a","learning_start_attempt",{enrollmentId:e.enrollmentId}));data(f.call("learner-a","human_save_answer",{attemptId:at.attemptId,questionId:"old-question",answer:1},"human"));data(f.call("learner-a","human_submit_attempt",{attemptId:at.attemptId,confirmed:true},"human"));const old=f.db.prepare("SELECT * FROM attempts WHERE id=?").get(at.attemptId),lessons=f.db.prepare("SELECT completed_lessons FROM enrollments WHERE id=?").get(e.enrollmentId)!.completed_lessons;
 data(f.call("editor","learning_update_course",{courseId:"ui-quiz-upgrade",course:{...value,quiz:{...value.quiz,questions:[{id:"latest-question",prompt:"Original latest prompt",options:["Latest correct","Latest incorrect"],correct:0}]}}}));data(f.call("editor","learning_publish_course",{courseId:"ui-quiz-upgrade"}));
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 try{
  await app.listen({port:4369,host:"127.0.0.1"});await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill("learner-a");await page.getByLabel("Password",{exact:true}).fill("learner-a-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();await page.getByRole("button",{name:"My learning",exact:true}).click();
  const region=page.getByRole("region",{name:"Latest objective quiz review",exact:true});await region.getByRole("button",{name:"Review latest objective quiz",exact:true}).click();await expect(region).toContainText("v1 → v2");const create=region.getByRole("button",{name:"Restart with latest objective quiz",exact:true});await expect(create).toBeDisabled();await region.getByRole("button",{name:"Keep enrolled quiz version",exact:true}).click();expect(f.db.prepare("SELECT count(*) n FROM enrollments WHERE retake_of=?").get(e.enrollmentId)!.n).toBe(0);
  await region.getByRole("button",{name:"Review latest objective quiz",exact:true}).click();await region.getByLabel("I choose the latest objective quiz and reset my answers.",{exact:true}).check();const response=page.waitForResponse(r=>r.url().endsWith("/api/human/invoke")&&r.request().postDataJSON()?.toolName==="human_restart_latest_quiz");await create.click();const result=await(await response).json();expect(result.ok,JSON.stringify(result.error)).toBe(true);
  await page.reload();await page.getByRole("button",{name:"My learning",exact:true}).click();await expect(page.getByRole("region",{name:"Latest objective quiz review",exact:true})).toBeVisible();const fresh=f.db.prepare("SELECT * FROM enrollments WHERE retake_of=?").get(e.enrollmentId)!;expect(fresh.version).toBe(2);expect(fresh.completed_lessons).toBe(lessons);expect(fresh.status).toBe("in_progress");expect(f.db.prepare("SELECT * FROM attempts WHERE id=?").get(at.attemptId)).toEqual(old);expect(f.db.prepare("SELECT count(*) n FROM certificates").get()!.n).toBe(0);
  await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByRole("region",{name:"Xem xét bài kiểm tra khách quan mới nhất",exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/latest-objective-quiz-review.png",fullPage:true});
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
