
import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author enables previous hints and incorrect-only objective retry; learner keeps first correct response, compares prior wrong answer and explicitly submits in EN/VI",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4364",title="Original UI incorrect retry";
 const course={...structuredClone(courses["learning-vi"]),title,language:"en",quiz:{passScore:100,maxAttempts:4,shuffleOptions:true,questions:[{id:"first",prompt:"Original retained first question",options:["Correct first","Wrong first"],correct:0},{id:"second",prompt:"Original remaining second question",options:["Correct second","Wrong second"],correct:0}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-incorrect-retry",course}));data(f.call("editor","learning_publish_course",{courseId:"ui-incorrect-retry"}));
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 const write=(tool:string)=>page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().postDataJSON()?.toolName===tool);
 async function action(tool:string,click:()=>Promise<void>){const response=write(tool);await click();expect((await(await response).json()).ok).toBe(true);}
 try{
  await app.listen({port:4364,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();const editor=page.getByRole("region",{name:"Course authoring",exact:true});
  await editor.getByLabel("Show previous responses in human player",{exact:true}).check();await editor.getByLabel("Retry only incorrect objective questions",{exact:true}).check();await action("learning_update_course",()=>editor.getByRole("button",{name:"Save draft",exact:true}).click());await expect(row.getByRole("button",{name:"Publish",exact:true})).toBeEnabled();await action("learning_publish_course",()=>row.getByRole("button",{name:"Publish",exact:true}).click());await expect(row).toContainText("Published version 2");
  const e=data(f.call("learner-a","learning_enroll",{courseId:"ui-incorrect-retry"}));for(const lesson of course.lessons)data(f.call("learner-a","human_complete_lesson",{enrollmentId:e.enrollmentId,lessonId:lesson.id},"human"));
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();await page.locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})}).getByRole("button",{name:"Continue learning",exact:true}).click();await page.getByRole("button",{name:"Start assessment",exact:true}).click();await expect(page.getByRole("heading",{name:"Assessment · Attempt 1",exact:true})).toBeVisible();
  await action("human_save_answer",()=>page.getByRole("radio",{name:"Correct first",exact:true}).check());await expect(page.getByRole("radio",{name:"Wrong second",exact:true})).toBeEnabled();await action("human_save_answer",()=>page.getByRole("radio",{name:"Wrong second",exact:true}).check());await expect(page.getByRole("button",{name:"Confirm and submit my answers",exact:true})).toBeEnabled();await action("human_submit_attempt",()=>page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click());await expect(page.getByRole("radio",{name:"Wrong second",exact:true})).toBeDisabled();
  const prior=f.db.prepare("SELECT * FROM attempts WHERE enrollment_id=? AND number=1").get(e.enrollmentId)!;expect(prior.score).toBe(50);await page.getByRole("button",{name:"Start assessment",exact:true}).click();await expect(page.getByRole("heading",{name:"Assessment · Attempt 2",exact:true})).toBeVisible();await expect(page.getByRole("radio",{name:"Correct first",exact:true})).toHaveCount(0);await expect(page.getByText("1 · Earlier correct responses are retained unchanged; complete the remaining questions and explicitly submit this new attempt.",{exact:true})).toBeVisible();
  const hint=page.getByText("Previous response · Attempt 1",{exact:true});await hint.click();await expect(hint.locator("..").getByText("Wrong second",{exact:true})).toBeVisible();const second=f.db.prepare("SELECT * FROM attempts WHERE enrollment_id=? AND number=2").get(e.enrollmentId)!;expect(second.score).toBe(null);expect(second.submitted).toBe(0);expect(f.db.prepare("SELECT COUNT(*) AS n FROM certificates WHERE enrollment_id=?").get(e.enrollmentId)!.n).toBe(0);expect(data(f.call("learner-a","learning_get_attempt",{attemptId:second.id})).contentWithheld).toBe(true);
  await action("human_save_answer",()=>page.getByRole("radio",{name:"Correct second",exact:true}).check());await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByText("Câu trả lời trước · Lượt 1",{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/original-incorrect-only-retry.png",fullPage:true});await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");
  await expect(page.getByRole("button",{name:"Confirm and submit my answers",exact:true})).toBeEnabled();await action("human_submit_attempt",()=>page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click());await expect(page.getByRole("radio",{name:"Correct second",exact:true})).toBeDisabled();expect(f.db.prepare("SELECT score FROM attempts WHERE id=?").get(second.id)!.score).toBe(100);expect(f.db.prepare("SELECT * FROM attempts WHERE id=?").get(prior.id)).toEqual(prior);expect(f.db.prepare("SELECT COUNT(*) AS n FROM certificates WHERE enrollment_id=?").get(e.enrollmentId)!.n).toBe(1);console.log("QUIZ RETRY ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
