import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author reviews unlimited/submission feedback settings and literal messages; learner fails then retries through human UI without leaking keys into bridge",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4360",title="Original UI quiz settings",message="<img src=x onerror=alert(1)> Review the original explanation.";
 const value={...structuredClone(courses["learning-vi"]),title,language:"en",quiz:{passScore:100,maxAttempts:1,questions:[{id:"ui-quiz-question",prompt:"Choose the original correct answer",options:["Correct","Incorrect"],correct:0}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-quiz-settings",course:value}));data(f.call("editor","learning_publish_course",{courseId:"ui-quiz-settings"}));
 const first=f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-quiz-settings' AND version=1").get()!.content;
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});
 async function login(user:string){await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill(user);await page.getByLabel("Password",{exact:true}).fill(user+"-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();}
 const write=(tool:string)=>page.waitForResponse(response=>response.url().endsWith("/api/human/invoke")&&response.request().postDataJSON()?.toolName===tool);
 try{
  await app.listen({port:4360,host:"127.0.0.1"});await login("editor");await page.getByRole("button",{name:"Administration",exact:true}).click();const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();
  const editor=page.getByRole("region",{name:"Course authoring",exact:true});await editor.getByLabel("Pass score percentage",{exact:true}).fill("0");await expect(editor.getByLabel("Pass score percentage",{exact:true})).toHaveValue("0");await editor.getByLabel("Pass score percentage",{exact:true}).fill("100");
  await editor.getByLabel("Unlimited quiz attempts",{exact:true}).check();await expect(editor.getByLabel("Maximum attempts",{exact:true})).toBeDisabled();await editor.getByLabel("Answer release",{exact:true}).selectOption("after_submission");await editor.getByLabel("Custom fail message",{exact:true}).fill(message);await editor.getByLabel("Custom pass message",{exact:true}).fill("Original reviewed pass message");
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");await expect(page.getByLabel("Không giới hạn lượt thử quiz",{exact:true})).toBeChecked();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/quiz-reviewed-settings.png",fullPage:true});await page.getByLabel("Ngôn ngữ giao diện",{exact:true}).selectOption("en");
  let response=write("learning_update_course");await editor.getByRole("button",{name:"Save draft",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(row.getByRole("button",{name:"Publish",exact:true})).toBeEnabled();response=write("learning_publish_course");await row.getByRole("button",{name:"Publish",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(row).toContainText("Published version 2");
  expect(f.db.prepare("SELECT content FROM course_versions WHERE course_id='ui-quiz-settings' AND version=1").get()!.content).toBe(first);
  const e=data(f.call("learner-a","learning_enroll",{courseId:"ui-quiz-settings"}));for(const lesson of value.lessons)data(f.call("learner-a","human_complete_lesson",{enrollmentId:e.enrollmentId,lessonId:lesson.id},"human"));
  await page.getByRole("button",{name:"Sign out",exact:true}).click();await login("learner-a");await page.getByRole("button",{name:"My learning",exact:true}).click();const own=page.locator(".learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await own.getByRole("button",{name:"Continue learning",exact:true}).click();await page.getByRole("button",{name:"Start assessment",exact:true}).click();await expect(page.getByRole("heading",{name:"Assessment · Attempt 1",exact:true})).toBeVisible();
  response=write("human_save_answer");await page.getByRole("radio",{name:"Incorrect",exact:true}).check();expect((await(await response).json()).ok).toBe(true);response=write("human_submit_attempt");await page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(page.getByText(message,{exact:true})).toBeVisible();await expect(page.locator('img[src="x"]')).toHaveCount(0);
  const attemptId=f.db.prepare("SELECT id FROM attempts WHERE enrollment_id=? AND number=1").get(e.enrollmentId)!.id as string,bridge=data(f.call("learner-a","learning_get_attempt",{attemptId}));expect(bridge.feedback).toEqual([]);expect(bridge.resultMessage).toBe(null);expect(f.db.prepare("SELECT status FROM enrollments WHERE id=?").get(e.enrollmentId)!.status).toBe("in_progress");
  await page.getByRole("button",{name:"Start assessment",exact:true}).click();await expect(page.getByRole("heading",{name:"Assessment · Attempt 2",exact:true})).toBeVisible();response=write("human_save_answer");await page.getByRole("radio",{name:"Correct",exact:true}).check();expect((await(await response).json()).ok).toBe(true);response=write("human_submit_attempt");await page.getByRole("button",{name:"Confirm and submit my answers",exact:true}).click();expect((await(await response).json()).ok).toBe(true);await expect(page.getByText("Original reviewed pass message",{exact:true})).toBeVisible();
  expect(f.db.prepare("SELECT COUNT(*) AS n FROM certificates WHERE enrollment_id=?").get(e.enrollmentId)!.n).toBe(1);expect(f.db.prepare("SELECT COUNT(*) AS n FROM attempts WHERE enrollment_id=?").get(e.enrollmentId)!.n).toBe(2);console.log("QUIZ SETTINGS ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
