
import {test,expect} from "@playwright/test";
import {fixture,data} from "../helpers.ts";
import {courses} from "../../src/server/seed.ts";
import {createApp} from "../../src/server/app.ts";
import {resolve} from "node:path";
test("author practices unsaved shuffled multi/dropdown quiz in EN/VI, restarts snapshot and previews manual review without any domain write",async({page})=>{
 test.setTimeout(90000);const f=fixture(),origin="http://127.0.0.1:4363",title="Original interactive preview";
 const course={...structuredClone(courses["learning-vi"]),title,language:"en",quiz:{passScore:80,maxAttempts:3,shuffleOptions:true,answerRelease:"after_submission",questions:[{id:"multi",prompt:"Original practice question",options:["Alpha","Beta","Gamma","Delta"],correct:0,correctIndices:[0,2],partialCredit:true,feedbackSelected:["Original Alpha practice feedback","","",""],feedbackNotSelected:["","","Original Gamma practice feedback",""]},{id:"blank",kind:"blanks",prompt:"Original mixed blanks",options:[],correct:0,prompts:["Original city","Original word"],correctAnswers:["Paris","Áp dụng"],blankChoiceCounts:[3,0],blankChoiceOptions:["Paris","London","Berlin"]}]}};
 data(f.call("editor","learning_create_course",{courseId:"ui-quiz-preview",course}));data(f.call("editor","learning_publish_course",{courseId:"ui-quiz-preview"}));
 const before={course:f.db.prepare("SELECT * FROM courses WHERE id='ui-quiz-preview'").get(),attempts:f.db.prepare("SELECT * FROM attempts").all(),enrollments:f.db.prepare("SELECT * FROM enrollments").all(),certificates:f.db.prepare("SELECT * FROM certificates").all(),audit:f.db.prepare("SELECT * FROM audit").all(),revision:f.service.context("editor","library:demo").revision};
 const {app}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve("dist")});let writes=0;page.on("request",request=>{if(request.method()==="POST"&&request.url().endsWith("/api/human/invoke"))writes++;});
 try{
  await app.listen({port:4363,host:"127.0.0.1"});await page.goto(origin);await page.getByLabel("Account",{exact:true}).fill("editor");await page.getByLabel("Password",{exact:true}).fill("editor-dev");await page.getByRole("button",{name:"Sign in",exact:true}).click();await page.getByRole("button",{name:"Administration",exact:true}).click();
  const row=page.locator(".admin-courses .learning-row").filter({has:page.getByRole("heading",{name:title,exact:true})});await row.getByRole("button",{name:"Edit draft",exact:true}).click();const editor=page.getByRole("region",{name:"Course authoring",exact:true});await editor.getByLabel("First quiz question",{exact:true}).fill("Unsaved original practice question");await editor.getByRole("button",{name:"Preview draft",exact:true}).click();
  const preview=editor.getByRole("region",{name:"Interactive quiz preview",exact:true});await expect(preview).toContainText("Unsaved original practice question");await preview.getByRole("checkbox",{name:"Alpha",exact:true}).check();await preview.getByLabel("Original city",{exact:true}).selectOption({label:"Paris"});await preview.getByLabel("Original word",{exact:true}).fill("Áp dụng");await preview.getByRole("button",{name:"Save response",exact:true}).click();await preview.getByRole("button",{name:"Calculate practice result",exact:true}).click();await expect(preview.getByRole("status")).toHaveText("Practice result: 75% · Practice failed");await expect(preview).toContainText("Original Alpha practice feedback");await expect(preview).toContainText("Original Gamma practice feedback");
  await preview.getByRole("button",{name:"Restart preview with current draft",exact:true}).click();await expect(preview.getByRole("status")).toHaveCount(0);await expect(preview.getByRole("checkbox",{name:"Alpha",exact:true})).not.toBeChecked();await expect(preview.getByRole("button",{name:"Calculate practice result",exact:true})).toBeDisabled();
  await editor.getByRole("button",{name:"Preview draft",exact:true}).click();const questionTwo=editor.getByRole("group",{name:"Question 2",exact:true});await questionTwo.getByLabel("Question type",{exact:true}).selectOption("long_answer");await questionTwo.getByLabel("Assessment rubric",{exact:true}).fill("Original preview rubric");await editor.getByRole("button",{name:"Preview draft",exact:true}).click();
  await preview.getByRole("checkbox",{name:"Alpha",exact:true}).check();await preview.getByRole("checkbox",{name:"Gamma",exact:true}).check();await preview.getByLabel("Your own written response",{exact:true}).fill("Original practice explanation");await preview.getByRole("button",{name:"Save response",exact:true}).click();await preview.getByRole("button",{name:"Calculate practice result",exact:true}).click();await expect(preview.getByRole("status")).toHaveText("Preview awaits human assessment; no simulated essay score.");await expect(preview).not.toContainText("Original Alpha practice feedback");
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Interface language",{exact:true}).selectOption("vi");const localized=page.getByRole("region",{name:"Xem thử câu hỏi tương tác",exact:true});await expect(localized.getByRole("status")).toContainText("không tạo điểm bài viết giả định");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:"artifacts/original-interactive-quiz-preview.png",fullPage:true});
  expect(writes).toBe(0);expect(f.db.prepare("SELECT * FROM courses WHERE id='ui-quiz-preview'").get()).toEqual(before.course);expect(f.db.prepare("SELECT * FROM attempts").all()).toEqual(before.attempts);expect(f.db.prepare("SELECT * FROM enrollments").all()).toEqual(before.enrollments);expect(f.db.prepare("SELECT * FROM certificates").all()).toEqual(before.certificates);expect(f.db.prepare("SELECT * FROM audit").all()).toEqual(before.audit);expect(f.service.context("editor","library:demo").revision).toBe(before.revision);console.log("QUIZ PREVIEW ASSERTIONS COMPLETE");
 }finally{await page.close();app.server.closeAllConnections();await app.close();f.db.close();}
});
