import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createApp} from '../../src/server/app.ts';
import {scormLearningFixture} from '../scorm-learning-fixture.ts';
import {interopPackage} from '../scorm-interop-fixture.ts';
for(const edition of ['2004-2','2004-3','2004-4'] as const)test(edition+': built first-checkpoint response provenance survives type change, lost ACK, Close and resume',async({page})=>{
  const script=`const api=parent.API_1484_11,base='cmi.interactions.0',entry=document.getElementById('entry');
    const same=()=>api.GetValue(base+'.type')==='numeric'&&api.GetValue(base+'.learner_response')==='answer'&&api.GetLastError()==='0'&&api.GetValue(base+'.correct_responses.0.pattern')==='answer'&&api.GetLastError()==='0';
    if(api.GetValue('cmi.entry')==='resume'){if(!same())throw Error('Bound response resume mismatch');entry.textContent='Bound responses resumed';const correct=document.createElement('button');correct.textContent='Replace using numeric type';document.body.append(correct);correct.onclick=()=>{if(api.SetValue(base+'.learner_response','42')!=='true'||api.SetValue(base+'.correct_responses.0.pattern','1[:]2')!=='true'||api.Commit('')!=='true')throw Error('Numeric replacement rejected');entry.textContent='Numeric replacements saved';correct.remove();};}
    else{for(const [key,value]of [['id','urn:pear:bound'],['type','choice'],['learner_response','answer'],['correct_responses.0.pattern','answer']])if(api.SetValue(base+'.'+key,value)!=='true')throw Error('Initial choice rejected');entry.textContent='Choice responses ready';const button=document.createElement('button');button.textContent='Retain responses under numeric type';document.body.append(button);button.onclick=()=>{for(let n=0;n<5000;n++)if(api.SetValue(base+'.type',n%2?'choice':'sequencing')!=='true')throw Error('Type history rejected');if(api.SetValue(base+'.type','numeric')!=='true'||!same()||api.SetValue('cmi.exit','suspend')!=='true'||api.Commit('')!=='true')throw Error('Bound checkpoint rejected');entry.textContent='Bound responses queued';button.remove();};}`;
  const f=await scormLearningFixture(undefined,interopPackage(edition,'pipwerks',script));f.enroll();
  const origin='http://127.0.0.1:5580',{app,scormContentApp:content}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve('dist'),scormContent:{origin:'http://localhost:5581',runtimeBundle:readFileSync('dist/scorm/runtime.js')}});
  try{await content!.listen({port:5581,host:'127.0.0.1'});await app.listen({port:5580,host:'127.0.0.1'});await page.goto(origin);await page.getByLabel('Account',{exact:true}).fill('learner-a');await page.getByLabel('Password',{exact:true}).fill('learner-a-dev');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'My learning',exact:true}).click();
    await page.locator('.learning-row').filter({has:page.getByRole('heading',{name:'Original SCORM course',exact:true})}).getByRole('button',{name:'Continue learning',exact:true}).click();
    const player=page.getByLabel('Enrolled SCORM player',{exact:true}),outer=page.frameLocator('iframe[title="Isolated SCORM engine player"]'),sco=outer.frameLocator('iframe[title="SCORM SCO"]');await player.getByLabel('I consent to SCORM progress tracking for this enrollment.',{exact:true}).check();await player.getByRole('button',{name:/Introduction/}).click();await expect(sco.getByText('Choice responses ready',{exact:true})).toBeVisible();await expect(player.getByRole('status')).toContainText('saved by the server');
    await expect.poll(()=>{const r=JSON.parse(f.db.prepare('SELECT runtime_state FROM scorm_sco_attempts').get()!.runtime_state as string).interactions?.[0];return r===undefined;}).toBe(true);
    const revision=Number(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision),receipts=Number(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n);let dropped=false,original='';await page.route('**/launch/*/checkpoint',async route=>{const payload=route.request().postData()!;if(!dropped){dropped=true;original=payload;const response=await route.fetch();expect(response.ok()).toBe(true);expect(Array.isArray(JSON.parse(payload).interactionWrites)).toBe(true);expect(JSON.parse(payload).interactionWrites).toHaveLength(5);await route.abort();}else{expect(payload).toBe(original);await route.continue();}});
    await sco.getByRole('button',{name:'Retain responses under numeric type',exact:true}).click();await expect(sco.getByText('Bound responses queued',{exact:true})).toBeVisible();await expect(outer.getByRole('status')).toContainText('has not been acknowledged');const retry=player.getByRole('button',{name:'Retry engine checkpoint',exact:true});await retry.scrollIntoViewIfNeeded();await expect(retry).toBeInViewport();await retry.click();await expect(player.getByRole('status')).toContainText('saved by the server');expect(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision).toBe(revision+1);expect(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n).toBe(receipts+1);await page.unroute('**/launch/*/checkpoint');
    const close=player.getByRole('button',{name:'Close SCO and choose another',exact:true});await close.scrollIntoViewIfNeeded();await expect(close).toBeInViewport();await close.click();await expect(close).toHaveCount(0);await player.getByRole('button',{name:/Introduction/}).click();await expect(sco.getByText('Bound responses resumed',{exact:true})).toBeVisible();expect(Object.keys(JSON.parse(f.db.prepare('SELECT result FROM scorm_engine_checkpoints ORDER BY rowid DESC LIMIT 1').get()!.result as string).responseBindings).length).toBe(2);
    // The resumed nested frame can remain below the viewport after the shell Close.
    const frame=page.locator('iframe[title="Isolated SCORM engine player"]');await frame.scrollIntoViewIfNeeded();await expect(frame).toBeInViewport();
    await sco.getByRole('button',{name:'Replace using numeric type',exact:true}).click();await expect(sco.getByText('Numeric replacements saved',{exact:true})).toBeVisible();await expect(player.getByRole('status')).toContainText('saved by the server');await expect.poll(()=>Object.keys(JSON.parse(f.db.prepare('SELECT result FROM scorm_engine_checkpoints ORDER BY rowid DESC LIMIT 1').get()!.result as string).responseBindings).length).toBe(0);expect(f.db.prepare('SELECT count(*) n FROM scorm_completion_proofs').get()!.n).toBe(0);
  }finally{await page.close();content!.server.closeAllConnections();app.server.closeAllConnections();await app.close();f.db.close();}
});
