import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createApp} from '../../src/server/app.ts';
import {scormLearningFixture} from '../scorm-learning-fixture.ts';
import {interopPackage} from '../scorm-interop-fixture.ts';
for(const edition of ['2004-2','2004-3','2004-4'] as const)test(edition+': built unreloadable checkpoint refusal recovers without losing ACK/retry/resume state',async({page})=>{
  const script=`const api=parent.API_1484_11,base='cmi.interactions.0',resume=api.GetValue('cmi.entry')==='resume',entry=document.getElementById('entry');
    if(resume){if(api.GetValue(base+'.type')!=='numeric'||api.GetValue(base+'.learner_response')!=='42')throw Error('Exact recovered state');entry.textContent='Recovered response verified';}
    else{if(api.SetValue(base+'.id','urn:pear:reload')!=='true'||api.SetValue(base+'.type','choice')!=='true'||api.SetValue(base+'.learner_response','answer')!=='true')throw Error('Initial response');entry.textContent='Response ready';const button=document.createElement('button');button.textContent='Recover type change';document.body.append(button);button.onclick=()=>{
      for(let i=0;i<4097;i++)if(api.SetValue(base+'.type','choice')!=='true'||api.SetValue(base+'.learner_response','uncommitted')!=='true')throw Error('Noncompactable journal setup');if(api.SetValue(base+'.learner_response','uncommitted')!=='true'||api.SetValue(base+'.type','numeric')!=='true'||api.GetLastError()!=='0'||api.GetValue(base+'.learner_response')!=='uncommitted')throw Error('Type change storage');
      if(api.Commit('')!=='false'||api.GetLastError()!=='391'||api.Terminate('')!=='false'||api.GetLastError()!=='111')throw Error('Unreloadable snapshot queued');
      if(api.SetValue(base+'.learner_response','42')!=='true'||api.Commit('')!=='true')throw Error('Recovery rejected');entry.textContent='Recovered response verified';button.remove();};}`;
  const f=await scormLearningFixture(undefined,interopPackage(edition,'pipwerks',script));f.enroll();
  const origin='http://127.0.0.1:5540',{app,scormContentApp:content}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve('dist'),scormContent:{origin:'http://localhost:5541',runtimeBundle:readFileSync('dist/scorm/runtime.js')}});
  try{await content!.listen({port:5541,host:'127.0.0.1'});await app.listen({port:5540,host:'127.0.0.1'});await page.goto(origin);await page.getByLabel('Account',{exact:true}).fill('learner-a');await page.getByLabel('Password',{exact:true}).fill('learner-a-dev');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'My learning',exact:true}).click();
    await page.locator('.learning-row').filter({has:page.getByRole('heading',{name:'Original SCORM course',exact:true})}).getByRole('button',{name:'Continue learning',exact:true}).click();
    const player=page.getByLabel('Enrolled SCORM player',{exact:true}),outer=page.frameLocator('iframe[title="Isolated SCORM engine player"]'),sco=outer.frameLocator('iframe[title="SCORM SCO"]');await player.getByLabel('I consent to SCORM progress tracking for this enrollment.',{exact:true}).check();await player.getByRole('button',{name:/Introduction/}).click();await expect(sco.getByText('Response ready',{exact:true})).toBeVisible();await expect(player.getByRole('status')).toContainText('saved by the server');
    const revision=Number(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision);await sco.getByRole('button',{name:'Recover type change',exact:true}).click();await expect(sco.getByText('Recovered response verified',{exact:true})).toBeVisible();await expect.poll(()=>Number(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision)).toBe(revision+1);await expect(player.getByRole('status')).toContainText('saved by the server');
    const receipts=Number(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n);let dropped=false,original='';await page.route('**/launch/*/checkpoint',async route=>{const payload=route.request().postData()!;if(!dropped){dropped=true;original=payload;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort();}else{expect(payload).toBe(original);await route.continue();}});
    await sco.getByRole('button',{name:'Store licensed progress',exact:true}).click();await expect(outer.getByRole('status')).toContainText('has not been acknowledged');const retry=player.getByRole('button',{name:'Retry engine checkpoint',exact:true});await retry.scrollIntoViewIfNeeded();await expect(retry).toBeInViewport();await retry.click();await expect(player.getByRole('status')).toContainText('saved by the server');expect(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision).toBe(revision+2);expect(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n).toBe(receipts+1);await page.unroute('**/launch/*/checkpoint');
    const close=player.getByRole('button',{name:'Close SCO and choose another',exact:true});await close.scrollIntoViewIfNeeded();await expect(close).toBeInViewport();await close.click();await expect(close).toHaveCount(0);await player.getByRole('button',{name:/Introduction/}).click();await expect(sco.getByText('Recovered response verified',{exact:true})).toBeVisible();expect(f.db.prepare('SELECT count(*) n FROM scorm_completion_proofs').get()!.n).toBe(0);
  }finally{await page.close();content!.server.closeAllConnections();app.server.closeAllConnections();await app.close();f.db.close();}
});
