import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createApp} from '../../src/server/app.ts';
import {scormLearningFixture} from '../scorm-learning-fixture.ts';
import {interopPackage} from '../scorm-interop-fixture.ts';
for(const edition of ['2004-2','2004-3','2004-4'] as const)for(const enrolled of [false,true])test(edition+' '+(enrolled?'enrolled':'practice')+': local checkpoint refusal blocks Close and preserves correction/retry/resume',async({page})=>{
  const script=`const api=parent.API_1484_11,base='cmi.interactions.0',entry=document.getElementById('entry');
    if(api.GetValue('cmi.entry')==='resume'){if(api.GetValue(base+'.type')!=='numeric'||api.GetValue(base+'.learner_response')!=='42')throw Error('Resume mismatch');entry.textContent='Corrected response resumed';}
    else{const invalid=document.createElement('button');invalid.textContent='Leave an unsaved type change';document.body.append(invalid);invalid.onclick=()=>{for(const [key,value]of [['id','urn:pear:local'],['type','choice'],['learner_response','answer']])if(api.SetValue(base+'.'+key,value)!=='true')throw Error('Type write');for(let i=0;i<4097;i++)if(api.SetValue(base+'.type','choice')!=='true')throw Error('Journal setup');if(api.SetValue(base+'.type','numeric')!=='true')throw Error('Numeric type');entry.textContent='Unsaved response retained';invalid.remove();};const correct=document.createElement('button');correct.textContent='Correct response and save';document.body.append(correct);correct.onclick=()=>{if(api.GetValue(base+'.learner_response')!=='answer'||api.GetLastError()!=='0'||api.SetValue(base+'.learner_response','42')!=='true'||api.SetValue('cmi.exit','suspend')!=='true'||api.Commit('')!=='true')throw Error('Local recovery');entry.textContent='Corrected response ready';correct.remove();};}`;
  const f=await scormLearningFixture(undefined,interopPackage(edition,'pipwerks',script));if(enrolled)f.enroll();
  const origin='http://127.0.0.1:5560',{app,scormContentApp:content}=await createApp({db:f.db,origin,developmentAuth:true,staticRoot:resolve('dist'),scormContent:{origin:'http://localhost:5561',runtimeBundle:readFileSync('dist/scorm/runtime.js')}});
  try{await content!.listen({port:5561,host:'127.0.0.1'});await app.listen({port:5560,host:'127.0.0.1'});await page.goto(origin);await page.getByLabel('Account',{exact:true}).fill('learner-a');await page.getByLabel('Password',{exact:true}).fill('learner-a-dev');await page.getByRole('button',{name:'Sign in',exact:true}).click();
    if(enrolled){await page.getByRole('button',{name:'My learning',exact:true}).click();await page.locator('.learning-row').filter({has:page.getByRole('heading',{name:'Original SCORM course',exact:true})}).getByRole('button',{name:'Continue learning',exact:true}).click();}else await page.getByRole('button',{name:'Imported packages',exact:true}).click();
    const player=enrolled?page.getByLabel('Enrolled SCORM player',{exact:true}):page.getByRole('region',{name:'SCORM engine packages',exact:true}),outer=page.frameLocator('iframe[title="Isolated SCORM engine player"]'),sco=outer.frameLocator('iframe[title="SCORM SCO"]'),close=player.getByRole('button',{name:enrolled?'Close SCO and choose another':'Close engine package',exact:true});
    await player.getByLabel(enrolled?'I consent to SCORM progress tracking for this enrollment.':"I consent to this engine package's separate reported tracking.",{exact:true}).check();await player.getByRole('button',{name:enrolled?/Introduction/:'Play or resume engine package'}).click();await expect(player.getByRole('status')).toContainText('saved by the server');
    const revision=Number(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision),receipts=Number(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n);
    await sco.getByRole('button',{name:'Leave an unsaved type change',exact:true}).click();await close.scrollIntoViewIfNeeded();await expect(close).toBeInViewport();await close.click();await expect(outer.getByRole('status')).toContainText('has not been acknowledged');await expect(close).toBeEnabled();await expect(page.locator('iframe[title="Isolated SCORM engine player"]')).toHaveCount(1);expect(f.db.prepare('SELECT closed FROM scorm_engine_launches').get()!.closed).toBe(0);expect(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision).toBe(revision);expect(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n).toBe(receipts);
    await sco.getByRole('button',{name:'Correct response and save',exact:true}).click();await expect(sco.getByText('Corrected response ready',{exact:true})).toBeVisible();const retry=player.getByRole('button',{name:'Retry engine checkpoint',exact:true});await retry.scrollIntoViewIfNeeded();await expect(retry).toBeInViewport();await retry.click();await expect(player.getByRole('status')).toContainText('saved by the server');expect(f.db.prepare('SELECT revision FROM scorm_sco_attempts').get()!.revision).toBe(revision+1);expect(f.db.prepare('SELECT count(*) n FROM scorm_engine_checkpoints').get()!.n).toBe(receipts+1);
    await close.scrollIntoViewIfNeeded();await expect(close).toBeInViewport();await close.click();await expect(close).toHaveCount(0);await player.getByRole('button',{name:enrolled?/Introduction/:'Play or resume engine package'}).click();await expect(sco.getByText('Corrected response resumed',{exact:true})).toBeVisible();expect(f.db.prepare('SELECT count(*) n FROM scorm_completion_proofs').get()!.n).toBe(0);
  }finally{await page.close();content!.server.closeAllConnections();app.server.closeAllConnections();await app.close();f.db.close();}
});
