import express from 'express';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StreamableHTTPServerTransport} from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {Bounds} from '@orchard/bridge-contract';
export async function startMcp(policy,port=4313){const app=express(),sessions=new Map();app.use((req,res,next)=>{if(req.headers.host!==`127.0.0.1:${req.socket.localPort}`&&req.headers.host!==`localhost:${req.socket.localPort}`)return res.sendStatus(403);if(req.headers.origin)return res.sendStatus(403);const match=/^Bearer ([A-Za-z0-9_-]+)$/.exec(req.headers.authorization??'');const c=match&&policy.authenticate(match[1]);if(!c)return res.sendStatus(401);req.client=c;next();});app.use(express.json({limit:'64kb'}));
 const target={targetId:z.string(),pageInstanceId:z.string()};const call=z.object({requestId:z.string(),documentId:z.string(),toolName:z.string(),arguments:z.record(z.unknown()),expectedRevision:z.number().int().nonnegative().nullable(),idempotencyKey:z.string().nullable()}).strict();
 app.all('/mcp',async(req,res)=>{try{const sid=req.headers['mcp-session-id'];if(sid){const s=sessions.get(sid);if(!s||s.client!==req.client.id)return res.sendStatus(404);return await s.transport.handleRequest(req,res,req.body);}if(req.method!=='POST')return res.sendStatus(400);const server=new McpServer({name:'coconut',version:'0.1.0'});for(const [name,schema]of Object.entries({host_list_targets:{},host_get_context:target,host_list_tools:target,host_call_tool:{...target,call}})){server.registerTool(name,{inputSchema:schema},async(args,extra)=>{const result=await policy.execute(req.client,name,args,extra.signal);return {structuredContent:result,content:[{type:'text',text:JSON.stringify(result)}],isError:!result.ok};});}
 const transport=new StreamableHTTPServerTransport({sessionIdGenerator:()=>randomUUID(),onsessioninitialized:id=>{if(sessions.size>=Bounds.sessions){// Contract: reject rather than silently evict a live session.
 server.close().catch(()=>{});return res.sendStatus(429);}sessions.set(id,{client:req.client.id,transport,server});}});transport.onclose=()=>{for(const [id,s]of sessions)if(s.transport===transport)sessions.delete(id);};await server.connect(transport);await transport.handleRequest(req,res,req.body);}catch{if(!res.headersSent)res.sendStatus(400);}});
 const listener=await new Promise((resolve,reject)=>{const s=app.listen(port,'127.0.0.1',error=>error?reject(error):resolve(s));s.on('error',reject);});return {port:listener.address().port,close:async()=>{for(const s of sessions.values())await s.server.close();await new Promise(resolve=>listener.close(resolve));}};
}
