import {validReply,safeSchema} from './validation.mjs';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import Ajv from 'ajv';
export const ok=(data,revision=null)=>({ok:true,revision,data,error:null});
export const fail=(code,message=code,retryable=false)=>({ok:false,revision:null,data:null,error:{code,message,retryable}});
export const canonical=x=>JSON.stringify(x,(_,v)=>v && typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
const ajv=new Ajv({strict:false});
export class Policy {
 constructor(dispatch,{timeout=10000}={}) {this.dispatch=dispatch;this.timeout=timeout;this.targets=new Map();this.clients=new Map();this.pending=new Map();this.audit=[];this.uiUntil=0;this.tools=new Map();}
 heartbeat(){this.uiUntil=Date.now()+4000;}
 pair(name,scopes,targetIds,ttl=3600000){if(!name||!scopes.every(s=>['read','write'].includes(s))||!targetIds.every(id=>this.targets.has(id)))throw Error('Invalid pairing');const token=randomBytes(32).toString('base64url');const id=randomUUID();this.clients.set(createHash('sha256').update(token).digest('hex'),{id,name,scopes,targetIds,expires:Date.now()+Math.min(ttl,3600000)});return {id,token,expires:Date.now()+Math.min(ttl,3600000)};}
 authenticate(token){const c=this.clients.get(createHash('sha256').update(token).digest('hex'));return c&&c.expires>Date.now()?c:null;}
 revoke(id){for(const [key,c] of this.clients)if(c.id===id)this.clients.delete(key);for(const [key,a]of this.pending)if(a.client.id===id){a.resolve(false);this.pending.delete(key);}}
 bind(t){this.invalidate(t.targetId);this.targets.set(t.targetId,t);}
 invalidate(id){this.targets.delete(id);this.tools.delete(id);for(const [key,a]of this.pending)if(a.target.targetId===id){a.resolve(false);this.pending.delete(key);}}
 allowed(c,t){return c?.id==='sidebar'||c?.targetIds.includes(t.targetId);}
 current(t,c){const now=this.targets.get(t.targetId);return now&&canonical(now)===canonical(t)&&this.allowed(c,now)&&(c.id==='sidebar'||[...this.clients.values()].some(x=>x===c&&x.expires>Date.now()));}
 decide(id,allow){const a=this.pending.get(id);if(!a)return false;this.pending.delete(id);a.resolve(allow===true&&Date.now()<a.expires&&this.uiUntil>Date.now()&&this.current(a.target,a.client));return true;}
 async page(t,op,call,signal){if(signal?.aborted)return fail('CANCELLED');let timer,abort;try{const result=await Promise.race([this.dispatch(t,op,call,signal),new Promise(resolve=>{timer=setTimeout(()=>resolve(fail('TIMEOUT')),this.timeout);abort=()=>resolve(fail('CANCELLED'));signal?.addEventListener('abort',abort,{once:true});})]);if(!validReply(result,op))return fail('INVALID_ARGUMENT','Invalid page response');if(!result.ok&&['UNAUTHORIZED','FORBIDDEN'].includes(result.error.code))this.invalidate(t.targetId);return result;}catch(e){return fail('TARGET_CLOSED',String(e));}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
 async execute(c,name,args,signal){let result;try{result=await this.perform(c,name,args,signal);}catch(e){result=fail('INVALID_ARGUMENT',String(e));}this.audit.push({at:Date.now(),client:c?.name??'unknown',tool:name,ok:result.ok,code:result.error?.code??null});if(this.audit.length>200)this.audit.shift();return result;}
 async perform(c,name,args,signal){if(signal?.aborted)return fail('CANCELLED');if(!c)return fail('UNAUTHORIZED');if(!args||typeof args!=='object'||Array.isArray(args))return fail('INVALID_ARGUMENT');if(name==='host_list_targets')return Object.keys(args).length?fail('INVALID_ARGUMENT'):ok({targets:[...this.targets.values()].filter(t=>this.allowed(c,t))});
 if(!['host_get_context','host_list_tools','host_call_tool'].includes(name))return fail('UNSUPPORTED');const t=this.targets.get(args.targetId);if(!t)return fail('TARGET_CLOSED');if(!this.allowed(c,t)||!c.scopes.includes('read'))return fail('FORBIDDEN');if(args.pageInstanceId!==t.pageInstanceId)return fail('STALE_CONTEXT');
 if(name!=='host_call_tool'){const r=await this.page(t,name==='host_get_context'?'getContext':'describe',null,signal);if(!this.current(t,c))return fail('STALE_CONTEXT');if(r.ok&&name==='host_get_context'&&(r.data.appId!==t.appId||r.data.documentId!==t.documentId)){this.invalidate(t.targetId);return fail('STALE_CONTEXT');}if(r.ok&&name==='host_list_tools'){if(r.data.protocolVersion!=='0.1'||r.data.appId!==t.appId)return fail('UNSUPPORTED');this.tools.set(t.targetId,r.data.tools);}return r;}
 const call=args.call;if(!call||Object.keys(call).sort().join(',')!=='arguments,documentId,expectedRevision,idempotencyKey,requestId,toolName'||typeof call.requestId!=='string'||call.documentId!==t.documentId||!call.arguments||Array.isArray(call.arguments))return fail('INVALID_ARGUMENT');
 // Page effect declarations never grant read authority: every domain invoke requires approval in this POC.
 const descriptor=this.tools.get(t.targetId)?.find(x=>x.name===call.toolName);if(!descriptor)return fail('UNSUPPORTED');if(!safeSchema(descriptor.inputSchema))return fail('UNSUPPORTED','Tool schema is outside the host-safe subset');if(!/^[A-Za-z0-9_-]{1,64}$/.test(descriptor.name)||!ajv.validate(descriptor.inputSchema,call.arguments))return fail('INVALID_ARGUMENT');
 if(descriptor.effect!=='read'&&(!Number.isInteger(call.expectedRevision)||call.expectedRevision<0||typeof call.idempotencyKey!=='string'||!call.idempotencyKey))return fail('INVALID_ARGUMENT');if(!c.scopes.includes('write'))return fail('FORBIDDEN');if(this.uiUntil<Date.now())return fail('APPROVAL_DENIED','Trusted approval UI is inactive');
 const frozen=JSON.parse(canonical(call));const id=randomUUID();let timer,abort;const approved=await new Promise(resolve=>{this.pending.set(id,{id,client:c,target:{...t},call:frozen,expires:Date.now()+this.timeout,resolve});timer=setTimeout(()=>{this.pending.delete(id);resolve(false);},this.timeout);abort=()=>{this.pending.delete(id);resolve(false);};signal?.addEventListener('abort',abort,{once:true});});clearTimeout(timer);signal?.removeEventListener('abort',abort);if(signal?.aborted)return fail('CANCELLED');if(!this.current(t,c))return fail('STALE_CONTEXT');if(!approved)return fail('APPROVAL_DENIED');const context=await this.page(t,'getContext',null,signal);if(!context.ok)return context;if(context.data.documentId!==frozen.documentId||context.data.appId!==t.appId||!this.current(t,c))return fail('STALE_CONTEXT');if(this.uiUntil<Date.now())return fail('APPROVAL_DENIED');return this.page(t,'invoke',frozen,signal);
 }
 snapshot(){return {targets:[...this.targets.values()],approvals:[...this.pending.values()].map(a=>({id:a.id,client:a.client.name,target:a.target,call:a.call,expires:a.expires})),audit:this.audit,clients:[...this.clients.values()].map(({id,name,expires,scopes,targetIds})=>({id,name,expires,scopes,targetIds}))};}
}
export const sidebar={id:'sidebar',name:'Sidebar',scopes:['read','write']};
